### DISCUSSION TITLE
docker stack help

### DISCUSSION THREAD

**Discussion by vidhya199** [NginxProxyManager/nginx-proxy-manager#1302] [General]
Working with docker stack i have docker stack as below its not working pales suggest me changes .. i dont want a bind because its generate unnamed volumes.

```yml
version: '3.4'

volumes:
   nfsdata:
      driver: local
      driver_opts:
        type: "nfs"
        o: "addr=192.168.0.140,rw,nfsvers=4,async"
        device: ":/mnt/data/volumes/nginx-proxy-manager/data"
        
   nfsletsencrypt:
      driver: local
      driver_opts:
        type: "nfs"
        o: "addr=192.168.0.140,rw,nfsvers=4,async"
        device: ":/mnt/data/volumes/nginx-proxy-manager/letsencrypt"
        
   nfsmysql:
      driver: local
      driver_opts:
        type: "nfs"
        o: "addr=192.168.0.140,rw,nfsvers=4,async"
        device: ":/mnt/data/volumes/nginx-proxy-manager/mysql"
     
networks:
  nginx_network:
    driver: overlay
    attachable: true

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - nfsdata:/data
      - nfsmysql:/data/mysql
      - nfsletsencrypt:/etc/letsencrypt
    networks:
      - nginx_network
  db:
    image: 'jc21/mariadb-aria:10.4'
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - nfsmysql:/var/lib/mysql
    networks:
      - nginx_network
```

**Comment by vidhya199** [comment]
NO worries.. got the solution ... check this out... will help other people.. and my suggetion to you please make document on this ... how to dpeloy with docker stack ... add below code on your website... will help a lot off people who is looking for docker stack with nfs....its work for me.... 


```yml
version: '3.4'

volumes:
   nfsdata:
      driver: local
      driver_opts:
        type: "nfs"
        o: "addr=192.168.0.140,rw,nfsvers=4,async"
        device: ":/mnt/data/volumes/nginx-proxy-manager/data"
        
   nfsletsencrypt:
      driver: local
      driver_opts:
        type: "nfs"
        o: "addr=192.168.0.140,rw,nfsvers=4,async"
        device: ":/mnt/data/volumes/nginx-proxy-manager/letsencrypt"
     
networks:
  nginx_network:
    driver: overlay
    attachable: true

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - nfsdata:/data
      - nfsletsencrypt:/etc/letsencrypt
    networks:
      - nginx_network
  db:
    image: 'jc21/mariadb-aria:10.4'
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - /mnt/data/volumes/nginx-proxy-manager/data/mysql:/var/lib/mysql
    networks:
      - nginx_network
```
