### DISCUSSION TITLE
Incorrect request IP address received by proxy

### DISCUSSION THREAD

**Discussion by chaptergy** [NginxProxyManager/nginx-proxy-manager#1724] [FAQs / Instructions]
It might happen that you create an access list, but it's always forbidden. Or you look at the access logs and all requests are from the same IP address. This is because docker proxies all requests sent to the container, and replaces the IP address with it's own. There are multiple ways to fix this.

> Note: If you Nginx Proxy Manager instance is outside your local network, you will _never_ be able to get the local IP of the device, only the public IP address.

## Option 1: Disable the docker userland proxy
The userland proxy is doing exactly what's described above. Furthermore disabling this proxy will probably increase the throughput of your proxy. Disabling it by default is actually [considered by the docker team](https://github.com/moby/moby/issues/14856).

> Note: This option is not available in a Docker rootless installation, on Docker for Mac and Docker for Windows

On the host running the docker containers create a new file (or edit it if it exists) `/etc/docker/daemon.json`. Then add the following json data:

```json
{
    "userland-proxy": false
}
```
Restart the docker daemon by running 
```
sudo systemctl restart docker
```

## Option 2: Set the specific ports to host mode

Changing the ports where the IP address should be preserved to host mode is also an option. Just change this in your `docker-compose` file 
```yml
ports:
  - '80:80'
  - '443:443'
```
to
```yml
ports:
      - target: 443
        published: 443 # Outside port
        mode: host
        protocol: tcp
      - target: 80
        published: 80 # Outside port
        mode: host
        protocol: tcp
```

## Option 3: Set the entire container to host mode

You can also set your entire container to network mode `host`. But this way you will no longer be able to map and expose ports, but port `80`, `81` and `443` will always be used. As you can't un-expose the admin panel, this method is not suggested.

```yml
services:
  app:
    ...
    network_mode: host  # This is relevant
    ....
```
