### DISCUSSION TITLE
How to proxy to localhost app ?

### DISCUSSION THREAD

**Discussion by sucrecacao** [NginxProxyManager/nginx-proxy-manager#1837] [Q&A]
Hello,

I have only one server which runs nginx proxy manager and a simple web app running on `localhost:5000`

Is it possible to create a proxy from `$my_server_ip_address` -> `localhost:5000` ?

For now I'm exposing my web on `$my_server_ip_address:5000` and use proxy manager to proxy `$my_server_ip_address:80` and `$my_server_ip_address:443` to `$my_server_ip_address:5000` and handle SSL certificate. Is this an OK configuration? I though it would be cleaner to not expose my web app at all to the web.

**Comment by cmj2002** [comment]
NPM runs in a docker container, which has its own ip address. So set the forward host as `localhost:5000` in NPM won't work. Actually, if you set the forward host to `localhost:81`, NPM will proxy its own admin UI.

My solution is Setting a docker network and set the gateway (the host of docker) as forward host.

For example, I am hosting a service on port `8888` , so my `docker-compose.yml` is:

```
version: '3'
services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: 'nginx'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./NginxProxyManager/data:/data
      - ./NginxProxyManager/letsencrypt:/etc/letsencrypt
    networks:
      backend:
        ipv4_address: 172.16.0.4
 
networks:
  backend:
    ipam:
      config:
      - subnet: 172.16.0.0/24
```

And set the forward host in NPM to `172.16.0.1`, port `8888`.
