### DISCUSSION TITLE
Django Static Files

### DISCUSSION THREAD

**Discussion by EfraimGENC** [NginxProxyManager/nginx-proxy-manager#1981] [Q&A]
Hi everyone,
I'm publishing my django project as docker container with these settings below:

_Scheme: `http`
Forward Hostname / IP: `my_django_container_name`
Port: `8000`_

It works fine. Thanks for NPM :)

**However, I need to publish/show my static files. My static file folder paths are:**

- In server: `/home/apps/my_django/staticfiles`
- In container: `/app/staticfiles`

I tried both of paths above with `alias` tag in `Custom Nginx Configuration` like this:
```
location /static/ {
    alias /app/staticfiles/;
}
```
but I'm getting `404 Not Found openresty` error only.
Is there anyone who has idea to fix this?

Thanks for all..

**Comment by proDreams** [comment]
Same problem, is there a solution?

**Comment by EfraimGENC** [comment]
Don't forget to link your Django project's static/media folder to the NPM container. The locations you define in NPM can only be accessed in this way.

### Mount static folder on docker compose file
```yaml
services:
  npm_app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm_app
    restart: unless-stopped
    ports:
      ...
    environment:
      ...
    volumes:
      - ./data/npm/data:/data
      - ./data/npm/letsencrypt:/etc/letsencrypt
      
      # HERE MOUNTING STATIC FILES ON YOUR NPM CONTAINER TO ACCESS AS ALIAS
      - ./path/of/your/django/media:/data/django/media
      - ./path/of/your/django/static:/data/django/static
      ...
```
_Official `docker-compose.yml` file of NPM is [here](https://nginxproxymanager.com/setup/#using-mysql-mariadb-database)._


### Then you can configurate like:
```
location /static/ {
    alias /data/django/static/;
}

location /media/ {
    alias /data/django/media/;
}
```

Thats it!


### BONUS:
There are many bots that attack WordPress because it is the most common CMS in the world. In order for your Django project to be less affected by these, you can add the following settings to return 404 to the addresses that these bots frequently attack, before the request reaches your Django project.
```
# Block PHP and ASP file requests
location ~* \.(php|asp)$ {
    return 404;
}

# Block specific paths of WordPress
location ~* ^/(wp-admin|wp-login\.php|wp-content|wp-includes|wp-json|wp-cron\.php) {
    return 404;
}

# Block other common malicious bot paths
# xmlrpc\.php|admin|login|user|config can be included
location ~* ^/(xmlrpc\.php) {
    return 404;
}
```
