### DISCUSSION TITLE
How to access the web ui over SSL ?

### DISCUSSION THREAD

**Discussion by Rajstopy** [NginxProxyManager/nginx-proxy-manager#2204] [Q&A] [answered]
Dear all,

I've set up a nginx-proxy-manager instance in my Docker environnement. Everything looks good except I found nowhere how to access web UI over SSL.

I plan to use this RP in my DMZ and accessing the web UI over HTTP is definitely not a good idea...

Did I miss something ?

Here is my docker-compose short example...

Any help would be much appreciated!

```
version: '3'
services:      
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    depends_on:
      - code
    restart: always
    
    image: jlesage/nginx-proxy-manager
    ports:
      - "8181:8181"
      - "8080:8080"
      - "445:4443"
    volumes:
      - "/mnt/docker/nginx:/config:rw"
    networks:
      - proxy
      
networks:
  proxy:
    driver: bridge
```
