### DISCUSSION TITLE
Can you do something like this

### DISCUSSION THREAD

**Discussion by redimongo** [NginxProxyManager/nginx-proxy-manager#2375] [Q&A]
So we have a docker container that looks like this:

```
version: '3'
services:
  nextjs: 
    build: ./DRN1Git
  nginx: 
    build: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot/www:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
```

And we also have inside nginx the following
default.conf
```
# Cache zone
proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=STATIC:10m inactive=7d use_temp_path=off;

upstream nextjs {
  server nextjs:3000;
}

server {
  listen 80 default_server;

  server_name local.drn1.com.au;

  server_tokens off;

  gzip on;
  gzip_proxied any;
  gzip_comp_level 4;
  gzip_types text/css application/javascript image/svg+xml;

  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection 'upgrade';
  proxy_set_header Host $host;
  proxy_cache_bypass $http_upgrade;

  # BUILT ASSETS (E.G. JS BUNDLES)
  # Browser cache - max cache headers from Next.js as build id in url
  # Server cache - valid forever (cleared after cache "inactive" period)
  location /_next {
    proxy_cache STATIC;
    proxy_pass http://nextjs;
  }

  location /.well-known/acme-challenge/ {
        root /var/www/certbot;
  }

  location /.well-known/ {
        return 301 https://$host$request_uri;
  }
  # STATIC ASSETS (E.G. IMAGES)
  # Browser cache - "no-cache" headers from Next.js as no build id in url
  # Server cache - refresh regularly in case of changes
  location /static {
    proxy_cache STATIC;
    proxy_ignore_headers Cache-Control;
    proxy_cache_valid 60m;
    proxy_pass http://nextjs;
  }

  # DYNAMIC ASSETS - NO CACHE
  location / {
    proxy_pass http://nextjs;
  }
}

server {
  #listen 443 default_server;
  listen 443 default_server ssl http2;
  listen [::]:443 ssl http2;
  
  server_name local.drn1.com.au;
  ssl_certificate /etc/nginx/ssl/live/local.drn1.com.au/fullchain.pem;
  ssl_certificate_key /etc/nginx/ssl/live/local.drn1.com.au/privkey.pem;
  server_tokens off;

  gzip on;
  gzip_proxied any;
  gzip_comp_level 4;
  gzip_types text/css application/javascript image/svg+xml;

  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection 'upgrade';
  proxy_set_header Host $host;
  proxy_cache_bypass $http_upgrade;

  # BUILT ASSETS (E.G. JS BUNDLES)
  # Browser cache - max cache headers from Next.js as build id in url
  # Server cache - valid forever (cleared after cache "inactive" period)
  location /_next {
    proxy_cache STATIC;
    proxy_pass http://nextjs;
  }

  # STATIC ASSETS (E.G. IMAGES)
  # Browser cache - "no-cache" headers from Next.js as no build id in url
  # Server cache - refresh regularly in case of changes
  location /static {
    proxy_cache STATIC;
    proxy_ignore_headers Cache-Control;
    proxy_cache_valid 60m;
    proxy_pass http://nextjs;
  }

  # DYNAMIC ASSETS - NO CACHE
  location / {
    proxy_pass http://nextjs;
  }
}
```

is this possible to do with your proxy manager?
