### DISCUSSION TITLE
Combined Docker Compose setup with WordPress

### DISCUSSION THREAD

**Discussion by LarsEjaas** [NginxProxyManager/nginx-proxy-manager#2475] [Q&A]
I am struggling to set up NGINX Proxy Manager with WordPress.

Is there any way to run both NGINX Proxy Manager and WordPress services in the same docker-compose file or can anyone explain why this is not working?

I would expect to be able to proxy the WordPress service from the NGINX Proxy Manager admin but I can't seem to access WordPress by referencing the service name when setting up the proxy host.

If I setup other services inside my docker-compose file I can access and proxy the service just fine.

(see below docker-compose file - I can proxy `duplicati` without issues).

Is this because of a conflict as both NGINX-proxy-manager is using 80/tcp and is there any workaround for this?

I am running the setup on Oracle-cloud and have my instance restricted only publicly to expose ports 80,443 and 81.

Example setup (this is not working):

```
version: "3.9"
services:
  webserver:
    container_name: example_webserver
    image: "jc21/nginx-proxy-manager:latest"
    ports:
      - 80:80 # Public HTTP Port
      - 81:81 # Admin Web Port
      - 443:443 # Public HTTPS Port
    environment:
      DISABLE_IPV6: 'true'
    volumes:
      - src:/data
      - certs:/etc/letsencrypt
    #Ensure proxy manager survives crashes
    restart: unless-stopped

  db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: headless_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - db_data:/config
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]

  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: headless_phpmyadmin
    depends_on:
      - db
    environment:
      UPLOAD_LIMIT: 512M
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    restart: always
    ports:
      - ${MANAGE_PORT}:${MANAGE_PORT}

   wordpress:
    image: wordpress:latest
    container_name: example_wordpress
    depends_on:
      - db
    ports:
      - ${WORDPRESS_PORT}:80
    restart: always
    build:
      context: .
      dockerfile: WordPress.Dockerfile
    command: /bin/bash -c "set -ex; composer update --prefer-dist; exec docker-entrypoint.sh apache2-foreground"
    environment:
      VIRTUAL_HOST: http://example.com:8080/
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WPSITEURL', 'http://example.com:8080/' );
        define( 'WPHOME','http://example.com:8080/' );
    volumes:
      - wp_data:/var/www/html
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./apache/ports.conf:/etc/apache2/ports.conf

  duplicati:
    image: ghcr.io/linuxserver/duplicati:latest
    container_name: headless_duplicati
    environment:
      - PUID=0
      - PGID=0
      # Timezone of the server: See: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for alternatives
      - TZ=Europe/London
      - CLI_ARGS= --webservice-password=${WORDPRESS_DB_PASSWORD}
    volumes:
      - /config:/config
      - backups:/backups
      - wp_data:/source/wp_data
    ports:
      - ${BACKUP_PORT}:${BACKUP_PORT}
    restart: unless-stopped

  cli:
    image: wordpress:cli
    container_name: headless_cli
    user: xfs
    restart: on-failure
    #tty - will keep the container running
    tty: true
    volumes:
      - wp_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    depends_on:
      wordpress:
        condition: service_started
      #condition service_healty will make sure we wait until
      #after the database is initialized to start this container
      db:
        condition: service_healthy

volumes:
  db_data:
    name: example_db_data
  wp_data:
    name: example_wp_data
  src:
    name: example_src
  certs:
    name: example_certs
  backups:
    name: example_backups
```

**Comment by LarsEjaas** [comment]
Finally found a way to run this. Took some trial and error, and had to read a bit about Docker networking. But this is a working setup if anyone else is looking for something similar:

```yml
version: "3.9"
services:
  webserver:
    container_name: webserver
    image: "jc21/nginx-proxy-manager:latest"
    ports:
      - 80:80 # Public HTTP Port
      - 81:81 # Admin Web Port
      - 443:443 # Public HTTPS Port
    volumes:
      - src:/data
      - certs:/etc/letsencrypt
    #Ensure proxy manager survives crashes
    restart: unless-stopped
    networks:
      - default

  db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - db_data:/config
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
    networks:
      - internal

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    depends_on:
      - db
    restart: always
    build:
      context: .
      dockerfile: WordPress.Dockerfile
    command: /bin/bash -c "set -ex; composer update --prefer-dist; exec docker-entrypoint.sh apache2-foreground"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_TITLE: ${WORDPRESS_SITE_TITLE}
      WORDPRESS_ADMIN_EMAIL: ${ADMIN_EMAIL}
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WPSITEURL', ${WORDPRESS_SITE_URL} );
        define( 'WPHOME', ${WORDPRESS_SITE_URL} );
    expose:
      - ${WORDPRESS_PORT}
    volumes:
      - wp_data:/var/www/html
    networks:
      - default
      - internal

networks:
  default:
    external:
      name: proxy-network

  internal:
    driver: bridge

volumes:
  db_data:
    name: headless_db_data
  wp_data:
    name: headless_wp_data
  src:
    name: headless_src
  certs:
    name: headless_certs
  backups:
    name: headless_backups
```

The trick is to use an internal bridge-network for the different containers that need to communicate internally, and then setup the default network as external and then only use this for containers that needs to be exposed externally. 

For the full context, my `WordPress.Dockerfile` looks like this:

```bash
# syntax=docker/dockerfile:1.4.3
FROM wordpress:latest

# install Composer
COPY --from=composer /usr/bin/composer /usr/bin/composer

# update Composer to latest version
RUN composer self-update

COPY . .

EXPOSE 80

```
