### DISCUSSION TITLE
Nginx Proxy Manger cannot connect to another server on the network

### DISCUSSION THREAD

**Discussion by Mephisto090** [NginxProxyManager/nginx-proxy-manager#2666] [Q&A]
Hej,

I have the following problem the Nginx Proxy Manager (NPM) cannot redirect to another server. (Network structure: See picture)

[Network](https://i.stack.imgur.com/wOr67.png)

This is not a problem in the same Docker Desktop system. The redirects work without any problems and I can call Paperless with paperless.domain.tdl.
However, if I now try to address the Apache server on the Raspberry Pi, I get a variety of errors depending on how I configure the subdomain in the NPM.
In the Fritzbox I forwarded ports 80 and 443 internally to 180 and 1443 to the Windows server (192.168.178.70) on which NPM is running.

[Paperless works without any problems](https://i.stack.imgur.com/2dHtB.png)

[502 Bad Gateway](https://i.stack.imgur.com/FhguS.png) In this variant I get a 502 Bad Gateway

[ERR_TOO_MANY_REDIRECTS](https://i.stack.imgur.com/dhXIJ.png) In this variant I get a ERR_TOO_MANY_REDIRECTS

I tried it in Docker with Host or with the Bridge Network mode

Docker-Compose from NPM:
```
version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '180:80' # Public HTTP Port
      - '1443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "user"
      DB_MYSQL_PASSWORD: "password"
      DB_MYSQL_NAME: "database"
      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: 'true'
      TZ: 'Europe/Berlin'
      CONTAINER_DEBUG: 'true'
    volumes:
      - ./data:/data
      - ./config:/config
      - letsencrypt:/etc/letsencrypt
      - logs:/data/logs
    depends_on:
      db:
        condition: service_healthy
    networks:
      - npm-proxy
      - default

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    container_name: nginx-db
    environment:
      MYSQL_ROOT_PASSWORD: 'root_password'
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      
    
volumes:
  letsencrypt:
  logs:
  
networks:
  npm-proxy:
    name: npm-proxy
    driver: host # or with bridge
    attachable: true
    external: true
```

There is a ping and wget connection from the container to the Raspberry (192.168.178.44).

how can I successfully redirect the subdomain from the Nginx server to the Raspberry?

Thank you
