### DISCUSSION TITLE
NPM not connected to database, but still working

### DISCUSSION THREAD

**Discussion by manshurtigh** [NginxProxyManager/nginx-proxy-manager#2732] [Q&A] [answered]
Hi!

I want to start to say that all of my proxied sites are working as intentional. However, when I login to the Nginx Proxy Manager Admin GUI it is connected to the wrong database. The logs are posted below:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/01_perms.sh
/package/admin/s6-overlay-3.1.4.1/etc/s6-rc/scripts/cont-init: 20: /package/admin/s6-overlay-3.1.4.1/etc/s6-rc/scripts/cont-init: /etc/cont-init.d/01_perms.sh: not found
cont-init: info: /etc/cont-init.d/01_perms.sh exited 127
cont-init: info: running /etc/cont-init.d/01_s6-secret-init.sh
/package/admin/s6-overlay-3.1.4.1/etc/s6-rc/scripts/cont-init: 20: /package/admin/s6-overlay-3.1.4.1/etc/s6-rc/scripts/cont-init: /etc/cont-init.d/01_s6-secret-init.sh: Permission denied
cont-init: info: /etc/cont-init.d/01_s6-secret-init.sh exited 126
cont-init: warning: some scripts exited nonzero
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service prepare: starting
❯ Checking folder structure ...
❯ Enabling IPV6 in hosts: /etc/nginx/conf.d
  ❯ /etc/nginx/conf.d/default.conf
  ❯ /etc/nginx/conf.d/include/letsencrypt-acme-challenge.conf
  ❯ /etc/nginx/conf.d/include/ssl-ciphers.conf
  ❯ /etc/nginx/conf.d/include/assets.conf
  ❯ /etc/nginx/conf.d/include/block-exploits.conf
  ❯ /etc/nginx/conf.d/include/proxy.conf
  ❯ /etc/nginx/conf.d/include/ip_ranges.conf
  ❯ /etc/nginx/conf.d/include/force-ssl.conf
  ❯ /etc/nginx/conf.d/include/resolvers.conf
  ❯ /etc/nginx/conf.d/production.conf
❯ Enabling IPV6 in hosts: /data/nginx
  ❯ /data/nginx/proxy_host/12.conf
  ❯ /data/nginx/proxy_host/11.conf
  ❯ /data/nginx/proxy_host/5.conf
  ❯ /data/nginx/proxy_host/22.conf
  ❯ /data/nginx/proxy_host/23.conf
  ❯ /data/nginx/proxy_host/16.conf
  ❯ /data/nginx/proxy_host/17.conf
  ❯ /data/nginx/proxy_host/14.conf
  ❯ /data/nginx/proxy_host/20.conf
  ❯ /data/nginx/proxy_host/6.conf
  ❯ /data/nginx/proxy_host/13.conf
  ❯ /data/nginx/proxy_host/25.conf
  ❯ /data/nginx/proxy_host/8.conf
  ❯ /data/nginx/proxy_host/19.conf
  ❯ /data/nginx/proxy_host/18.conf
  ❯ /data/nginx/proxy_host/15.conf
  ❯ /data/nginx/proxy_host/10.conf
  ❯ /data/nginx/proxy_host/21.conf
  ❯ /data/nginx/proxy_host/2.conf
  ❯ /data/nginx/proxy_host/7.conf
-------------------------------------
 _   _ ____  __  __
| \ | |  _ \|  \/  |
|  \| | |_) | |\/| |
| |\  |  __/| |  | |
|_| \_|_|   |_|  |_|
-------------------------------------
s6-rc: info: service prepare successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service frontend: starting
s6-rc: info: service backend: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service frontend successfully started
s6-rc: info: service backend successfully started
s6-rc: info: service legacy-services: starting
❯ Starting backend ...
❯ Starting nginx ...
s6-rc: info: service legacy-services successfully started
[3/22/2023] [11:08:17 AM] [Global   ] › ℹ  info      No valid environment variables for database provided, using default SQLite file '/data/database.sqlite'
[3/22/2023] [11:08:23 AM] [Migrate  ] › ℹ  info      Current database version: none
[3/22/2023] [11:08:23 AM] [Setup    ] › ℹ  info      Logrotate Timer initialized
[3/22/2023] [11:08:25 AM] [Setup    ] › ℹ  info      Logrotate completed.
[3/22/2023] [11:08:25 AM] [IP Ranges] › ℹ  info      Fetching IP Ranges from online services...
[3/22/2023] [11:08:25 AM] [IP Ranges] › ℹ  info      Fetching https://ip-ranges.amazonaws.com/ip-ranges.json
[3/22/2023] [11:08:26 AM] [IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v4
[3/22/2023] [11:08:26 AM] [IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v6
[3/22/2023] [11:08:26 AM] [SSL      ] › ℹ  info      Let's Encrypt Renewal Timer initialized
[3/22/2023] [11:08:26 AM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[3/22/2023] [11:08:26 AM] [IP Ranges] › ℹ  info      IP Ranges Renewal Timer initialized
[3/22/2023] [11:08:26 AM] [Global   ] › ℹ  info      Backend PID 125 listening on port 3000 ...
```

The logs tell me there is `No valid environment variables for database provided, using default SQLite file '/data/database.sqlite'`. However, I do not understand why. This has been working for a couple of months. 

Below is my configuration via docker-compose:
```
version: "3"

####################################################################################
# SECRETS
####################################################################################

secrets:
  NPM_DB_MYSQL_USER:
    file: $DOCKERDIR/services/npm/secrets/npm-db-mysql_user.txt
  NPM_DB_MYSQL_USER_PASSWORD:
    file: $DOCKERDIR/services/npm/secrets/npm-db-mysql_user_password.txt
  NPM_DB_MYSQL_ROOT_PASSWORD:
    file: $DOCKERDIR/services/npm/secrets/npm-db-mysql_root_password.txt
  NPM_CF_DDNS_API_KEY:
    file: $DOCKERDIR/services/npm/secrets/npm-cf-ddns-api-key.txt

####################################################################################
# SERVICES
####################################################################################

services:

##########################################
# Reverse Proxy
##########################################

### NPM DATABASE ###
  npm-db:
    image: "mariadb:latest"
    container_name: "npm-db"
    restart: "unless-stopped"
    environment:
      MARIADB_USER_FILE: /run/secrets/NPM_DB_MYSQL_USER
      MARIADB_PASSWORD_FILE: /run/secrets/NPM_DB_MYSQL_USER_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/NPM_DB_MYSQL_ROOT_PASSWORD
      MARIADB_DATABASE: "npm"
    volumes:
      - $DOCKERDIR/services/npm/db/data/mysql:/var/lib/mysql
    secrets:
      - NPM_DB_MYSQL_USER
      - NPM_DB_MYSQL_USER_PASSWORD
      - NPM_DB_MYSQL_ROOT_PASSWORD
    networks:
      - inside

### NPM APPLICATION ###
  npm-app:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: "npm-app"
    restart: "unless-stopped"
    ports:
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "81:81" # Admin Web Port
    environment:
      # These are the settings to access your db
      # You can set any environment variable from a file by appending __FILE (double-underscore FILE) to the environmental variable name in this application.
      DB_MYSQL_HOST: "npm-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER__FILE: /run/secrets/NPM_DB_MYSQL_USER
      DB_MYSQL_PASSWORD__FILE: /run/secrets/NPM_DB_MYSQL_USER_PASSWORD
      DB_MYSQL_NAME: "npm"
      # If you would rather use Sqlite uncomment this
      # and remove all DB_MYSQL_* lines above
      # DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - $DOCKERDIR/services/npm/app/data:/data
      - $DOCKERDIR/services/npm/app/letsencrypt:/etc/letsencrypt
      - $DOCKERDIR/services/npm/app/letsencrypt:/var/log/letsencrypt
    secrets:
      - NPM_DB_MYSQL_USER
      - NPM_DB_MYSQL_USER_PASSWORD
    depends_on:
      npm-db:
        condition: service_started
      npm-db-gui:
        condition: service_started
    networks:
      - inside
      - outside

####################################################################################
# NETWORKS
####################################################################################
networks:
  inside:
    external: true
  outside:
    external: true
```

I also use adminer and can access the database just fine with it. This got me very confused, because the reverse proxy is working for all sites and at the same time I can only login to the NPM Admin GUI via the default credentials.

I have tried to restart NPM several times without any success.

Can someone help me to understand what is going on?
