### DISCUSSION TITLE
node --abort_on_uncaught_exception --max_old_space_size=250 index.js

### DISCUSSION THREAD

**Discussion by si-hb** [NginxProxyManager/nginx-proxy-manager#2745] [Q&A]
Whenever I run `docker compose up -d` and then `htop`,

I always see a list of these processes:

![image](https://user-images.githubusercontent.com/1800110/227657185-a337a900-eaba-4a9c-a58b-321ac92eaf87.png)

Stop the container and those processes go away. I've tried this on a Digital Ocean VM and a local machine, both running Ubuntu 22.04

Is this something I need to worry about? I haven't seen any other post mentioning this, so I'm wondering if it's something I'm doing wrong. Here's my docker-compose.yml file:

```
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

```
