### DISCUSSION TITLE
Unexpected warning: The "SERVER_IP" variable is not set

### DISCUSSION THREAD

**Discussion by vdrover** [NginxProxyManager/nginx-proxy-manager#2959] [Q&A]
When I run docker/npm from command line as a daemon, I get the following warning:

`WARN[0000] The "SERVER_IP" variable is not set. Defaulting to a blank string.`

I don't see a `SERVER_IP` reference in the npm docs, nor if i inspect the image from the cli. 

Here is my compose snippet for npm. Any thoughts on what's throwing the warning?

```
  npm:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    networks:
      npm_proxy:
        ipv4_address: 192.168.92.54 
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - $DOCKERDIR/appdata/npm/config:/config 
      - $DOCKERDIR/appdata/npm/letsencrypt:/etc/letsencrypt
      - $DOCKERDIR/appdata/npm/data:/data
    environment:
      DB_SQLITE_FILE: "/config/database.sqlite"
      DISABLE_IPV6: 'true'
      PUID: $PUID
      PGID: $PGID
```
