### DISCUSSION TITLE
nextcloudpi behind proxy works only with ip not with hostname

### DISCUSSION THREAD

**Discussion by dietrest** [NginxProxyManager/nginx-proxy-manager#3171] [General]
I've created NPM and nextcloudpi with the following compose file:
```
 version: '3.8'

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data/resolv.conf:/etc/resolv.conf
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - proxy

  nextcloudpi:
    container_name: nextcloudpi
    image: ownyourbits/nextcloudpi
    restart: always
    volumes:
      - /srv/md0/nc-docker/resolv.conf:/etc/resolv.conf
      - /srv/md0/nc-docker:/data

    networks:
      - proxy

networks:
    proxy:
        external: true
```

the docker net proxy I've created to get always the same IP Rangeand  and resolv.conf linked extern to edit it easyly. The Standard: nameserver 127.0.0.11 doesn't work, I need 172.25.0.1 for the net 172.25.0.0. Otherwise the Containers don' have Internet.
My Provider gave me a Audicodes500 that I have to use to let the Internet in. Everything else in my LAN is Connected to my Fritzbox 7590 that is connected to the Audiocodes. The fritzbox is configured as DMZ in the Audiocodes so that everything is foerwarded to the fritzbox.
the external hostname is obtained from duckdns.org.
my docker net proxy: 
root@debian-server:/srv/md0/nc-nginx-proxy# docker network inspect proxy
[
    {
        "Name": "proxy",
        "Id": "dd0645555d27c6d0d738a86ceb690c01473779eccdeddc7a537532414bc7aa42",
        "Created": "2023-08-27T17:55:16.106469637+02:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.25.0.0/16",
                    "Gateway": "172.25.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "cfaf8140d7464d5cbb61d46b4bc4b193b39e2c4a9cc189a12e59c98a69074a31": {
                "Name": "nc-nginx-proxy-app-1",
                "EndpointID": "2ace49efdce2c4d01086e7ab637e7424ef3a35fdfd64db095b87933cf7a4be70",
                "MacAddress": "02:42:ac:19:00:03",
                "IPv4Address": "172.25.0.3/16",
                "IPv6Address": ""
            },
            "d86dad56fbddd8a307fdf88f15ded130aed6fbd55fd9245a83925021e40dd2df": {
                "Name": "nextcloudpi",
                "EndpointID": "9d9940387f8a76d33e83f1144ddae7e2f97f991ca0d68d44e2c55774eb8a69ab",
                "MacAddress": "02:42:ac:19:00:02",
                "IPv4Address": "172.25.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]

![grafik](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/78085524/d057a27b-ea42-49a9-9113-fe293845fe79)

 With this created proxy host the nextcloud works, but if I change the IP to the Hostname "nextcloudpi" 
I get a 502 error.
