### DISCUSSION TITLE
Unable to connect to Database after fresh install

### DISCUSSION THREAD

**Discussion by empx92** [NginxProxyManager/nginx-proxy-manager#3203] [Q&A]
Hello Community,
i have a problem with connection to the db and i don't know why, so maybe someone has the clue and could help me please.

docker-compose.yml
```
version: "3.5"
services:
  npm-app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm-app
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm-user"
      DB_MYSQL_PASSWORD: "safePW"
      DB_MYSQL_NAME: "npm-db"
      # Uncomment the line below if IPv6 is not enabled on your host
      DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    networks:
      - npm-nw
      - npm-internal

  db:
    image: 'mariadb:latest'
    container_name: npm-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'safePW'
      MYSQL_DATABASE: 'npm-db'
      MYSQL_USER: 'npm-user'
      MYSQL_PASSWORD: 'safePW'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - npm-internal

networks:
  npm-internal:
  npm-nw:
    external: true
```
docker log only says that it's not possible to connect the user to the db.
As the log is also written in the npm-app and npm-db container the connection between app and db should be fine.
I know there are many of those errors in the discussions but i didn't find any solution.
