### DISCUSSION TITLE
Best Practive to use Docker Network fails

### DISCUSSION THREAD

**Discussion by excelsi** [NginxProxyManager/nginx-proxy-manager#3416] [Q&A] [answered]
I tried this recommendation 
https://nginxproxymanager.com/advanced-config/#best-practice-use-a-docker-network

Resulting in this Docker Compose File:

```
version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
networks:
  default:
    external: true
    name: scoobydoo
```

I got this error :
ERROR: The Compose file './docker-compose.yml' is invalid because:
networks.default value Additional properties are not allowed ('name' was unexpected)

These are my networks:
NETWORK ID     NAME      DRIVER    SCOPE
cc876b184788   bridge    bridge    local
774e845c5f59   host      host      local
a736dc513621   none      null      local

Any help?
Thanks!
