### DISCUSSION TITLE
PHP website

### DISCUSSION THREAD

**Discussion by ignacio82** [NginxProxyManager/nginx-proxy-manager#3446] [Q&A]
I'm trying to move away from my synology webstation to a solultion using NginxProxyManager. I have a php website in the volume `nfs-wwwhome`  and I want to be able to access it with the url `my.website.com` this is my docker-compose:

```
version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "myuser"
      DB_MYSQL_PASSWORD: "MYPASSWORD"
      DB_MYSQL_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
      PGID: 100
      PUID: 1026
      TZ: America/Los_Angeles
    volumes:
      - nfs-nginx-data:/data
      - nfs-nginx-letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
    links:
      - ignacio      
      
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'MYPASSWORD'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'MYPASSWORD'
    volumes:
      - nfs-nginx-mysql:/var/lib/mysql

  ignacio:
    image: php:latest
    restart: unless-stopped
    volumes:
      - nfs-wwwhome:/var/www
      

volumes:
  nfs-nginx-data:
    external: true
  nfs-nginx-letsencrypt:
    external: true
  nfs-nginx-mysql:
    external: true   
  nfs-wwwhome:  
    external: true 
```

Could you point me in the right direction to accomplish this?
