### DISCUSSION TITLE
ACCESS LIST ISSUE, Failed many attempts to TroubleShoot.

### DISCUSSION THREAD

**Discussion by VittiVicci** [NginxProxyManager/nginx-proxy-manager#3462] [Q&A]
Hi all, ive run into a strange issue. Im running NPM in a LXC container on ProxMox. Everything appears to be working for the moment with working Proxy Hosts and Certificates being retrieved. My issue involves my access list. 

I go to create a access list using either Auth or Access. When i enter information in the input box, and hit add..... nothing happens. It adds a blank box as if it registered my input but inserted none of the information. I hit save and a box pops up saying : "You must specify at least 1 Authorization or Access rule. I have looked through the DOCKER LOGS for my NPM-APP and NPM-DB and their seems to be no relevant information. The Console in the Browser Inpect reveals nothing. The only thing remotely close to an error log that i could find was in my FALLBACK_ERROR .log

```

2024/01/16 18:50:04 [error] 176#176: *7 connect() failed (111: Connection          refused) while connecting to upstream, client: 192.168.14.240, server:   nginxproxymanager, request: "POST /api/tokens HTTP/1.1", upstream:   "http://127.0.0.1:3000/tokens", host: "192.168.14.133:81", referrer:   "http://192.168.14.133:81/login"
    2024/01/16 18:54:01 [error] 176#176: *14 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.14.240, server: nginxproxymanager, request: "POST /api/tokens HTTP/1.1", upstream: "http://127.0.0.1:3000/tokens", host: "192.168.14.133:81", referrer: "http://192.168.14.133:81/login"
    root@DockerV2:/var/lib/docker/volumes/npm_npm-data/_data/logs# docker exec npm-app ss -tulwn | grep 3000

```
Exec'ing into the container and Curling port 3000 shows no connection issues:

```
    [root@docker-c1e359b2f34a:/app]# curl http://127.0.0.1:3000
    {"status":"OK","version":{"major":2,"minor":10,"revision":4}}
```

This is how the access list popup appears after i attempt to add Auth and/or IPs:

![Screenshot from 2024-01-16 15-27-42](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/94736732/c5f976cd-8929-4235-8ffe-f04c2febdefa)

![Screenshot from 2024-01-16 15-27-26](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/94736732/f5637f7a-5fa6-46be-a6c3-59a728110d7c)

My docker-compose.yaml:

```
    version: "3"
    volumes:
      nextcloud-data:
      nextcloud-db:
      npm-data:
      npm-ssl:
      npm-db:

    networks:
      frontend:
        # add this if the network is already existing!
        # external: true
      backend:

    services:
      nextcloud-app:
        image: nextcloud
        container_name: cloud
        restart: always
        volumes:
          - nextcloud-data:/var/www/html
        environment:
          - MYSQL_PASSWORD=replace
          - MYSQL_DATABASE=nextcloud
          - MYSQL_USER=nextcloud
          - MYSQL_HOST=nextcloud-db
        networks:
          - frontend
          - backend

      nextcloud-db:
        image: mariadb
        container_name: cloud-db
        restart: always
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
        volumes:
          - nextcloud-db:/var/lib/mysql
        environment:
          - MYSQL_ROOT_PASSWORD=replace
          - MYSQL_PASSWORD=replace
          - MYSQL_DATABASE=nextcloud
          - MYSQL_USER=nextcloud
        networks:
          - backend

      npm-app:
        image: jc21/nginx-proxy-manager:latest
        container_name: npm-app
        restart: always
        ports:
          - "80:80"
          - "81:81"
          - "443:443"
        environment:
          - DB_MYSQL_HOST=npm-db
          - DB_MYSQL_PORT=3306
          - DB_MYSQL_USER=npm
          - DB_MYSQL_PASSWORD=replace
          - DB_MYSQL_NAME=npm
       volumes:
          - npm-data:/data
          - npm-ssl:/etc/letsencrypt
       networks:
          - frontend
          - backend

       npm-db:
         image: jc21/mariadb-aria:latest
         container_name: npm-db
         restart: always
         environment:
          - MYSQL_ROOT_PASSWORD=replace
          - MYSQL_DATABASE=npm
          - MYSQL_USER=npm
          - MYSQL_PASSWORD=replace
        volumes:
          - npm-db:/var/lib/mysql
        networks:
          - backend
```
Ive been using a combo of CGPT, Google and reddit to try and figure this problem out. Other things ive tried: Different Browser, Incognito Mode, Earlier versions of NPM, Verified correct login access to DB on the Backend. Im at a loss. Im not sure what to do next to get my access list functioning properly. If anyone has suggestions as to what other logs to look at, or even a solution, i would be an incredibly happy self-hoster!
