### DISCUSSION TITLE
Can't reach other containers via hostname

### DISCUSSION THREAD

**Discussion by maurxce** [NginxProxyManager/nginx-proxy-manager#3487] [Q&A] [answered]
Hey, I've been wanting to cut back on exposed ports and thus wanted to use hostnames in my proxy hosts.

I have encountered one problem with hostnames so far:
```
$ docker exec <pingvin id> ping nginx
PING nginx (172.21.0.2): 56 data bytes
64 bytes from 172.21.0.2: seq=0 ttl=64 time=0.102 ms
```
```
$ docker exec <nginx id> ping pingvin
OCI runtime exec failed: exec failed: unable to start container process: exec: "ping": executable file not found in $PATH: unknown
$ docker exec <nginx id> curl pingvin:3000
curl: (7) Failed to connect to pingvin port 3000 after 1 ms: Couldn't connect to server
```

Edit: with ip's:
```
# vv nginx ip
root@dev:~# docker exec <pingvin id> ping 172.21.0.2
PING 172.21.0.2 (172.21.0.2): 56 data bytes
64 bytes from 172.21.0.2: seq=0 ttl=64 time=0.222 ms
```
```
# vv pingvin ip
root@dev:~# docker exec <nginx id> curl 172.21.0.3:3000
curl: (7) Failed to connect to 172.21.0.3 port 3000 after 0 ms: Couldn't connect to server
```

Same issue appears when trying to curl `:80` instead. I find it pretty weird that one container can reach the other, but not the other way around.

My compose.yml:
```yaml
services:
  nginx:
    image: jc21/nginx-proxy-manager:2.11.0
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
```
```yaml
services:
  pingvin:
    image: stonith404/pingvin-share:v0.21.5
    restart: unless-stopped
    volumes:
      - ./data:/opt/app/backend/data
      - ./public:/opt/app/frontend/public
    networks:
      - nginx_proxy   

networks:
  nginx_proxy:
    external: true
```
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/91284394/d0d6152d-6f24-4cee-9476-2622787de518)

Can someone help me figure this out?

**Comment by lastsamurai26** [comment]
First issue what is see is that your npm network is proxy not nginx_proxy so pleae put your pingvin container to the  proxy  network ;)

**Reply by maurxce** [reply]
the `nginx_` is a prefix from the directory name it's created in, it's the same network

**Reply by lastsamurai26** [reply]
ok then try this 
docker network list

if there two networks like nginx_proxy and proxy  then you have 2 networks which are different 

i prefere to create the network outside of the compose file,

**Reply by maurxce** [reply]
```
$ docker network ls | grep "proxy"
8aa7fa012547   nginx_proxy         bridge    local
```
both are in the same network, pingvin can communicate with npm, but not the other way around

**Reply by lastsamurai26** [reply]
ok  i see 

can you try to add 
container_name: pingvin

to your compose of pingvin ;-) maybe this helps 
because normally docker created via compose  will make  the following 
folderOfCompose_servicename 

Since I do not know in your case what the folder is in which this compose file is located, it may be due to this

**Reply by maurxce** [reply]
tried `container_name` and `hostname`, neither of those did anything sadly.
Somehow I also destroyed npm again. Second time in 24 hours that I can't log in anymore, because I get a bad request (502) :/

**Reply by lastsamurai26** [reply]
I really suspect that something is wrong with your docker installation or with the network, if necessary create it manually outside compose

**Reply by maurxce** [reply]
I let npm regenerate the `data` dir and copied my nginx config back in, the website won't show it, but it's still applied. Good enough for testing currently.

I created a network using the cli, but I still experience the same issue.
I'll probably set up a plain nginx container after work to verify that it's actually a problem with npm

**Reply by maurxce** [reply]
Well, seems like a plain nginx container doesn't generate the necessary files to work? So idk if I can test it

**Reply by lastsamurai26** [reply]
It really is bewitching with you. I have now set up both COntainers 5 times and it has worked for me every time :'( unfortunately I can't really help you because I don't know what's wrong with you, I'm just a user too

**Reply by maurxce** [reply]
No worries, I really appreciate the help.

Would you mind sharing your exact configuration? Maybe I'll be able to work it out from there

**Reply by lastsamurai26** [reply]
sure why not 
i created a network 
docker networtk create npm_proxy  --subnet=172.123.0.0/16
```
version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    hostname: proxymanager
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      - '8000:8000'
      - '8001:8001'
      - '9443:9443'
      - '32144:32144'
    environment:
      DISABLE_IPV6: 'false'
    networks:
        proxy:
          ipv4_address: 172.18.1.253
    volumes:
      - /opt/containers/npm/data:/data
      - /opt/containers/npm/letsencrypt:/etc/letsencrypt
      - /opt/containers/npm/templates/_hsts.conf:/app/templates/_hsts.conf:ro
      - /etc/timezone:/etc/timezone:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
networks:
  npm_proxy:
    external: true
```
after start this container opening the http://ip:81 
create a domain for your NPM like rpwm.domain.de on http 127.0.0.1 81 
change in the compose 
```
      - '81:81' # Admin Web Port
```
to 
```
  # - '81:81' # Admin Web Port 
```

and recreate the container 

```
version: '3.8'
services:
  pingvin-share:
    image: stonith404/pingvin-share
    restart: unless-stopped
    container_name: pingvin
    volumes:
      - "/opt/containers/pingvin/data:/opt/app/backend/data"
      - "/opt/containers/pingvin/public:/opt/app/frontend/public/img"
    networks:
      - npm_proxy
networks:
  npm_proxy:
    external: true
```

start the container 
go to your npm create a new proxy as pingvin.domain.de on http pingvin 3000 


now i hope it should work

**Reply by maurxce** [reply]
I just tried using *my* config on my local pc, but I'm still encountering the same issue. So it's probably not related to the docker installation.
I'll see if I can try out your config soon

**Reply by maurxce** [reply]
Thanks! I Just tried your config on my local pc, and it seems to work for me. I'm not sure yet why mine didn't work though.

**Reply by maurxce** [reply]
I just changed my existing config to almost exactly match the structure of yours, with the exception of the network, port order and volumes:
```yaml
services:
  nginx:
    image: jc21/nginx-proxy-manager:2.11.0
    restart: unless-stopped
    hostname: proxymanager
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
```
```yaml
services:
  pingvin:
    image: stonith404/pingvin-share:v0.21.5
    restart: unless-stopped
    container_name: pingvin
    volumes:
      - ./data:/opt/app/backend/data
      - ./public:/opt/app/frontend/public
    networks:
      - nginx_proxy   

networks:
  nginx_proxy:
    external: true
```
I have tested this exact network setup with the config you provided and it worked fine, using it in my configs gives me a 502 bad gateway. I have absolutely no idea what is happening here.
