### DISCUSSION TITLE
Getting 502 Bad Gateway error on nginx proxy manager with gunicorn

### DISCUSSION THREAD

**Discussion by talhaanwarch** [NginxProxyManager/nginx-proxy-manager#3504] [General]
I am currently using [nginx proxy manager][1] in conjunction with Gunicorn:

```bash
gunicorn main_app.wsgi:application --bind 0.0.0.0:8000
```

Everything functions properly when I select HTTP, as shown in the image. However, the only drawback is that static files are not loading because they cannot be located, resulting in a "Not Found: /static/" error.

Upon switching to HTTPS, a 502 gateway error is encountered. The following error is logged:

```bash
my-portfolio-app | [2024-01-27 18:26:18 +0000] [8] [INFO] Starting gunicorn 21.2.0
my-portfolio-app | [2024-01-27 18:26:18 +0000] [8] [INFO] Listening at: http://0.0.0.0:8000 (8)
my-portfolio-app | [2024-01-27 18:26:18 +0000] [8] [INFO] Using worker: sync
my-portfolio-app | [2024-01-27 18:26:18 +0000] [10] [INFO] Booting worker with pid: 10
my-portfolio-app | [2024-01-27 18:27:23 +0000] [8] [CRITICAL] WORKER TIMEOUT (pid:10)
my-portfolio-app | [2024-01-27 23:27:23 +0500] [10] [INFO] Worker exiting (pid: 10)
my-portfolio-app | [2024-01-27 18:27:23 +0000] [8] [ERROR] Worker (pid:10) exited with code 1
my-portfolio-app | [2024-01-27 18:27:23 +0000] [8] [ERROR] Worker (pid:10) exited with code 1.
```

When running the application via 
```
python manage.py runserver 0.0.0.0:8000
``` 

with the scheme set to HTTP, everything works as expected, and static images are loaded. However, I prefer to use Gunicorn.

here are my docker-compose files.   
**Django docker-compose file**
```
version: '3'
services:
  django_app:
    container_name: my-portfolio-app
    volumes:
      - static_vol:/app/sub_app/static
    env_file:
      - .env
    build:
      context: .
   
    depends_on:
      - postgres
    networks:
      - mynetwork
```

**Nginx-proxy-manager docker-compose file**
```
version: '3.8'
services:
  app:
    container_name: my-nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - mynetwork

networks:
  mynetwork:
    name: mynetwork
    driver: bridge
```
**Screenshot of nginx-proxy-manager**

[![enter image description here][2]][2]

[1]: https://github.com/NginxProxyManager/nginx-proxy-manager
[2]: https://i.stack.imgur.com/TI1c2.png
