### DISCUSSION TITLE
Access Lists with Real Local IPs

### DISCUSSION THREAD

**Discussion by csm10495** [NginxProxyManager/nginx-proxy-manager#3523] [Q&A]
Hey folks, 

I'm trying to use Access Lists to bock access to certain websites from outside of 192.168.0.0/24. In theory this would block access outside my home network:

![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/5749838/8a2c449a-48aa-43eb-8065-e0428610b145)

When trying to access, i get: 

![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/5749838/954a49b1-99f6-4a73-ab30-59da28f9e463)

In the nginx access log i see: 
```
[03/Feb/2024:23:29:57 +0000] - - 403 - GET https REDACTED "/" [Client 192.168.80.1] [Length 182] [Gzip 3.23] [Sent-to host.docker.internal] "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36" "-"
```

The client ip seems to be one from the internal docker network instead of my actual system's ip: `192.168.0.49`. I'm guessing if I added the ip from the log it would work, but that defeats the purpose of the feature for me.

I'm using docker-compose with a yml like so:

```
services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' 
      - '443:443'
      - '81:81'
    environment:
      - PUID=1000
      - GUID=1000

    volumes:
      - z_drive_npm_data:/data
      - z_drive_npm_letsencrypt:/etc/letsencrypt
```

What type of network settings can I use to be able to use Access Lists to block 'real ips' instead of docker-internal ones?
