### DISCUSSION TITLE
How would I implement this nginx config to route Minecraft servers

### DISCUSSION THREAD

**Discussion by TwinNature** [NginxProxyManager/nginx-proxy-manager#3670] [Q&A]
Hey!!

I use NPM for a few web servers im running locally, but I also wanted to use it to route my minecraft server domains

I found [this NGINX custom config](https://github.com/Racer159/minecraft-reverse-proxy) to do this, but I was unsure about how to implement this into NPM

Should I create a stream then edit the config or should I simply copy this config and put it into "custom nginx configuration" when creating a normal proxy host

I'm not very familiar with NGINX and am quite spoiled by the easy to use GUI of NPM

any help would be greatly appreciated

**Comment by SagaciousFish** [comment]
Haven't looked into your config yet, but I've been using NPM and set up a MC server.
What I did was:
1. Use the NPM -> Hosts -> Streams feature to pass through the 25565 traffic.
2. have a proxy host mc.xxx.xxx to your NPM server.
3. Minecraft server is available @ mc.xxx.xxx
Not sure if this is the right/elegant way to do this task, but it works.

**Comment by Wetzel402** [comment]
I'm having trouble getting this to work.  Here is what I have.

1.  Streams setup for 25565 tcp/udp and 19132 udp
2.  Host setup for mc.xxx.xxx forwarding to 192.168.1.176:80 (local ip of my NPM instance
3.  In Minecraft entering the server address mc.xxx.xxx but not finding the server.

Does this look the same as yours?

**Reply by SagaciousFish** [reply]
The NPM IP you mentioned (192.168.1.176) seems awfully like a LAN address, you might need to make sure that your traffic — from your client, to DNS (where mc.xxx.xxx is resolved), to your NPM IP — is valid. This would likely require a public IP rather than a LAN one. (:80 port is insignificant for this case)

**Reply by Wetzel402** [reply]
My docker host has DuckDNS, NPM, and MC.  The host machine is at 192.168.1.176 in my LAN.  Currently DuckDNS and NPM proxy for a variety of containers so I was hoping to have it accomplish that for MC also.

**Reply by Wetzel402** [reply]
Here is my current configuration...

NPM is on the backend network and I access my other proxied containers via container name in NPM

```
version: '3.5'

services:
  minecraft:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"  # Java edition
      - "25575:25575" # RCON
      - "19132:19132/udp" # Bedrock edition
    restart: unless-stopped
    environment:
      MEMORY: "4G"
      TZ: "America/Chicago"
      EULA: "TRUE"
      DIFFICULTY: "peaceful"
      MODE: "creative"
      TYPE: PAPER
      ###############################################################################
      # Geyser and Floodgate plugins allow bedrock players to play on a java server #
      # ViaVersion allows newer clients to play on older servers without error      #
      ###############################################################################
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
        https://hangarcdn.papermc.io/plugins/ViaVersion/ViaVersion/versions/5.0.1/PAPER/ViaVersion-5.0.1.jar
      SERVER_NAME: "My World"
      MOTD: "Welcome!"
      ONLINE_MODE: true
      ALLOW_FLIGHT: true
      ALLOW_CHEATS: true
      MAX_PLAYERS: 6
      ICON: "icon.png"
    volumes:
      - /share/ContainerStation/minecraft-paper:/data
    networks:
      backend:
        ipv4_address: 10.10.0.220
      minecraft:
        ipv4_address: 172.29.60.220
networks:
  backend:
    name: backend
    external: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24
          gateway: 10.10.0.1
  minecraft:
    name: minecraft
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.29.60.0/24
          gateway: 172.29.60.1
```

The full container name is minecraft-minecraft-1...

![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/4612307/835bcb5f-496d-4796-ae65-40f18da56bfc)
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/4612307/3966f020-2b6a-4b4a-9ffc-774a13c8b7a5)

I'm able to connect via LAN using the host IP but using the URL over WAN doesn't work for me.

**Comment by SagaciousFish** [comment]
🤯 For everyone who has arrived, I hope this clears up any confusion.

As a background, I'm only hosting a Java Edition server, hence I did not stream 19132/UDP and 19133/TCP. However, I assume the technique is the same and should transfer easily.

I have to admit that I've "cheated" a bit for the following reasons:
1. My Minecraft server and NPM container are on the same host machine.
2. I've set this host machine to resolve all my domains.

Nonetheless, the technique should transfer even if you are using a different setup, as long as the following conditions are met:
1. Since NPM is controlling the stream, all traffic should go to the NPM container and therefore to its host machine first (by DNS or IP access).
2. Since you are forwarding the stream to your Minecraft server, the `Forward Host` and `Forward Port` should lead to your Minecraft server.
3. As for the stream's `Incoming Port`, this should be the port your game client is trying to access, which should be 25565 for the Java Edition and 19132/UDP and 19133/TCP for the Bedrock Edition.


A few touch that I would have to remind:
1. Since you will try to access `NPM:gaming-port`, remember to expose the gaming ports in your Docker run/Docker compose configuration, and of course, also your server.
2. ~In my configuration, demonstrated in the graph below, I did not have to expose and consume the 25565 port of the machine by utilizing Docker networks. Your case might vary. (This made my life a lot easier by allowing me not to remember which port was allocated to any other service and what's left to use. (yes, I have a terrible habit of abusing my server))~ not so important

Finally, the graph of my setup:
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/39843121/58d8b5d3-657f-4dba-8eb9-ef3904a4e010)

**Reply by handsome-steve** [reply]
Did you guys ever end up getting this to work? I've pretty much done the same but seem to be struggling, I'm using cloudflare as well, the A record is set to proxied.

**Reply by Wetzel402** [reply]
I never did and gave up for now.  Good luck!

**Comment by UWSCIA** [comment]
Unifi UDM Pro
create a DNS record to point to Nginx Proxy Manager

NGINX PROXY MANAGER
create Proxy Host

- domain name: minecraft.mydomain.com
- scheme: http
- ip: YOUR NGINX PROXY MANGERS IP
- port: YOUR NGINXX PROXY MANGERS PORT default is 81
- SAVE

create stream for java edition

- port: PORT OF MINECRAFT SERVER default is 25565
- forward host: IP OF MINECRAFT SERVER
- forward port: PORT OF MINECRAFT SERVER default is 25565
- SAVE

create stream for bedrock edition

- port: PORT OF MINECRAFT SERVER default is 19132
- forward host: IP OF MINECRAFT SERVER
- forward port: PORT OF MINECRAFT SERVER default is 19132
- SAVE

**Reply by Tenny131** [reply]
I love you, so simple and it just works. Thank you so much.

**Comment by derekthecool** [comment]
@UWSCIA thanks for your super detailed response! I'm assuming a router port forward is still necessary with this setup though right?
I'm having trouble reaching my home server using port 25565 even after setting up port forwarding. Perhaps I'm missing something or maybe ISP is blocking it.

In the meantime I've found a work around to at least get my server available for use using ngrok
```yaml
services:
  mc:
    image: itzg/minecraft-server:latest
    pull_policy: always
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok-minecraft
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mc
    command:
      - "tcp"
      - "--log=stdout"
      - "mc:25565"
    ports:
      - 4040:4040
```

Which just hooks up an ngrok container and connects it to the mc minecraft container.
Ngrok connection point can be found by checking `docker compose logs ngrok` or by going to the web interface on port 4040.
