### DISCUSSION TITLE
NPM does not route to Wordpress Site

### DISCUSSION THREAD

**Discussion by flo12ferrari12** [NginxProxyManager/nginx-proxy-manager#3743] [Q&A]
Hi all,

I have a Proxmox server running on which one instance contains an NPM in Docker. Another instance contains Wordpress in a Docker container. 

There are already several domains that reach out to me on different services. 
However, I have the problem that I cannot reach my Wordpress instance externally. 

Internally it works. when i open http://192.168.1.230:8080
the domain kunst.datenreich.eu points to my NPM. This is configured as follows: 

![grafik](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/125958087/3b2e62cc-d253-465f-87f9-ed272b6bbd4d)

![grafik](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/125958087/c781b8a2-0a52-40e9-8f94-55188fe47c72)

If I call the Ip internally, the website call works. 
When I call kunst.datenreich.eu the url is exchanged as follows: https://kunst.datenreich.eu:8080 and the following site is displayed: 

Does anyone here know what else I can do to make the website accessible? 
unfortunately i have only found a few posts so far and no solution to my problem

**Comment by veletron2** [comment]
Exact same issue here, Spent 2 days now trying to solve it. Various suggestions online re making new bridge network and shoving all containers in it, and then instead of specifying the IP addr, specify the wordpress container name. None of said suggestions work.

I get the feeling that using this proxy manager to access other containers on the same host is simply not supported

**Comment by jbcodemonkey** [comment]
Put the wordpress container on the same network as NPM and use the container name as the 'forward hostname' and 80 as the port. Docker resolves contanernames automatically within a network to the internal ips and communicates via the internal ports.

**Comment by thommonz** [comment]
Having the same issue and not making headway.
I have several containers in docker running various applications. Wordpress is in one, MySQL is in the other. Configured Wordpress to use the MySQL container by selecting the host machines IP address as the database location.
I also have Emby media server in another container. I have created a subdomain 'media' and NPM happily points traffic to the correct container using a proxy host entry that has the local IP address and port. 

I put Drupal in a container and pointed port NPM at it on port 8088. (Works like a charm)
As I would rather work with Wordpress, I'm currently researching and testing to try and get it to work rather than start re-learning Drupal which is far more complicated IMO.

**Reply by veletron2** [reply]
Mine is setup thus for WP. Note that I am using https via LetsEncrypt

![image](https://github.com/user-attachments/assets/724155b1-2955-40a7-a649-b43506eb31d6)

And in advanced tab:

location / {
    proxy_pass http://192.168.20.3:20080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_redirect off;
}

My wordpress runs on my docker host: 192.168.20.3 port 20080

In wordpress web config you MUST configure:

![image](https://github.com/user-attachments/assets/955ca3a4-58b7-4854-88cc-d8416762c697)

I don't know if this still works, but instead of the above, one used to be able to force the issue in wp-config.php

define('WP_HOME','https://test.com/blog/');
define('WP_SITEURL','https://test.com/blog/');

The WP config.php file should auto detect that its behind a proxy and do the 'right thing', but you can force the issue if it does not.

**Reply by thommonz** [reply]
Thanks for that suggestion. It's several steps closer, but still not the solution for me.
Point of note for any other following this thread/discussion is that in order to edit the wp-config.php (using Portainer) is to start the Wordpress container, open a console, run 'apt update' the 'apt install nano' or (some such other editor) - then edit the file and restart the container!

So, having followed the advice provided above, things appear to be working however the Wordpress site is not displaying correctly (pages are shown as text).

**Reply by veletron2** [reply]
When you say 'showing as text' do you mean you see seeing the php code rather than the code getting rendered as a page by the server?? You may need to post an example. If you are using the stock WP container the above should not be possible.

**Reply by thommonz** [reply]
Not seeing the PHP code, the page is only displaying items as text. 
There is not even a link to the Login Page.
I've tried making different changes to the WP_HOME and WP_SITEURL and restarting the container - without success.

**Comment by veletron2** [comment]
Sounds like the CSS is not being picked up correctly, or it cant pull
content from your database? Note that the likes of wp-config.php should be
within a folder thats mounted. Bind mount or volume. You can edit the files
within via your host as well as via the running image.

I assume this is an empty (default) wordpress to begin with. This is the
best way - start empty then import an existing site (if any).

**Reply by thommonz** [reply]
Yes, its starting from scratch - which I'm happy to do..  
Updating and building the site will be relatively easy (its not a large site - I'm just a hobbyist) but so much easier to do when the container/wordpress works nicely. (In the original post, I mentioned that the Drupal route is an option, but with a steeper learning curve)

**Reply by thommonz** [reply]
I'm happy with the Database connection as the Wordpress installation (which worked) picked it up and subsequent installation runs picked up the database existed and had to be emptied - so console login to the MySQL container to remove tables & a refresh did the trick. Thus wordpress is picking up the database in the correct location.

**Comment by thommonz** [comment]
Solved!
What worked for me. (Others mileage may vary)

Using Portainer in order to have a graphic interface with Docker, 
In the left hand navigation panel, click on Templates - Application.
Scroll through to 'Wordpress' (likely to be the last page) and click on 'Copy as Custom' which is on the right hand side.

This will create a custom application template. Fill in the required Title and Description and edit changes to the docker compose file.
This has two sections, one for the database it will create and place in a container, the other for the wordpress container.
(In the database or db area, change the MYSQL_ROOT_PASSWORD to something you can remember.) Basically that sets up the database environment root user. I also commented our the MYSQL_USER line. I then changed the WORDPRESS_DB_HOST to db:3306, WORDPRESS_DB_USER to root and the WORDPRESS_DB_PASSWORD to the MYSQL_PASSWORD.

Security Note: This may not be the wisest way to set up users and password. For me, this application sits on a firewalled device and is only there to run a couple of light applications.

Deploying the stack creates a couple of containers. Initially I had to check the log files of the DB container to ensure the database was running before being concerned with the Wordpress one. (Another learning for me is that I'm picking that this will ensure the database container is available BEFORE the wordpress one as a dependency of sorts...  IDK but makes sense that after a reboot of the host machine, they will come up in order.)

Then edit the configuration of the Wordpress container to port map my host port of 8080 to 80 in the container.

Test that 192.168.x.x:8080 loads the Wordpress install and then point the NPM proxy host to 192.168.x.x on port 8080 for the domain and in the TLS menu, set Force HTTPS to On.

Open a browser and go to the domain and finish the Wordpress install!

Many thanks for the ideas - point of clarity is that the issue is NOT with NPM, rather with Wordpress and how its installed in Docker.

**Reply by veletron2** [reply]
Glad you got it working. FWIW, this is my (anonymised) stack for WP incl DB, backup of the database and wpdata using 'docker volume backup' - stored out on my NAS weekly, and a commented out phpmyadmin container. DB passwords in plain text here for simplicity.

```
services:
  db:
    container_name: wordpress-XXX-db
    image: mariadb:latest
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db:/var/lib/mysql
      - db-backup:/tmp/dumps
    labels:
      - docker-volume-backup.archive-pre=/bin/sh -c 'mariadb-dump -uroot -pXXX wordpress-XXX > /tmp/dumps/wordpress-XXX.sql'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=XXX
      - MYSQL_DATABASE=wordpress-XXX
      - MYSQL_USER=wordpress-XXX
      - MYSQL_PASSWORD=XXX
    expose:
      - 3306

  #phpmyadmin:
    #container_name: wordpress-XXX-dbadmin
    #depends_on:
    # - db
    #image: phpmyadmin
    #user: 1002:1000
    #restart: always
    #ports:
    #  - "20081:80"
    #environment:
    #  PMA_HOST: db
    #  MYSQL_ROOT_PASSWORD: XXX
    #  UPLOAD_LIMIT: 1000000000

  wordpress:
    container_name: wordpress-XXX-web
    image: wordpress:latest
    volumes:
      - wpdata:/var/www/html
    labels:
      - docker-volume-backup.stop-during-backup=wordpress-XXX
    restart: always
    ports:
      - 20080:80
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress-XXX
      - WORDPRESS_DB_PASSWORD=XXX
      - WORDPRESS_DB_NAME=wordpress-XXX

  backup:
    container_name: wordpress-XXX-backup
    image: offen/docker-volume-backup:v2
    restart: always
    environment:
      BACKUP_FILENAME: wordpress-backup-%Y-%m-%dT%H-%M.tar.gz
      BACKUP_PRUNING_PREFIX: wordpress-backup-
      BACKUP_RETENTION_DAYS: '21'
      BACKUP_CRON_EXPRESSION: "0 0 * * MON"
      BACKUP_COMPRESSION: "gz"
      BACKUP_STOP_DURING_BACKUP_LABEL: wordpress-XXX
    volumes:
      - wpdata:/backup/wpdata:ro
      - db-backup:/backup/db:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /share/Backups/NAS-to-PC/DOCKER_VOLUME_BACKUPS/wordpress-XXX:/archive

volumes:
  db:
  db-backup:    
  wpdata:

```
