### DISCUSSION TITLE
how to reverse onlyoffice， ws is not work well

### DISCUSSION THREAD

**Discussion by aisyun** [NginxProxyManager/nginx-proxy-manager#3858] [Q&A]
how to reverse onlyoffice， ws is not work well

**Comment by lastsamurai26** [comment]
can you show us your docker compose for onlyoffice ? 
```
services:
  onlyoffice-documentserver:
    container_name: onlyoffice-documentserver
    hostname: onlyoffice-documentserver
    depends_on:
      - onlyoffice-postgresql
      - onlyoffice-rabbitmq
    image: onlyoffice/documentserver:latest
    env_file:
      - stack.env
    stdin_open: true
    restart: always
    stop_grace_period: 60s
    volumes:
       - com_data:/var/www/onlyoffice/Data
       - com_log:/var/log/onlyoffice
       - com_cache:/var/lib/onlyoffice/documentserver/App_Data/cache/files
       - com_files:/var/www/onlyoffice/documentserver-example/public/files
       - com_fonts:/usr/share/fonts
       - com_custom_fonts:/usr/share/fonts/truetype/custom
       - com_lib:/var/lib/onlyoffice
       - com_redis:/var/lib/redis
       - com_rabbitmq:/var/lib/rabbitmq
       - com_postgres:/var/lib/postgresql
       - /opt/containers/nginxproxy/letsencrypt/live/npm-12/privkey.pem:/var/www/onlyoffice/Data/certs/onlyoffice.key:ro
       - /opt/containers/nginxproxy/letsencrypt/live/npm-12/cert.pem:/var/www/onlyoffice/Data/certs/onlyoffice.crt:ro
    networks:
        onlydocs:
        proxy:
```
```
SSL_CERTFICATE_PATH=/var/www/onlyoffice/Data/certs/onlyoffice.crt
POSTGRES_DB=*****
POSTGRES_USER=*****
POSTGRES_HOST_AUTH_METHOD=trust
AMQP_URI=amqp://guest:guest@onlyoffice-rabbitmq
JWT_ENABLED=true
JWT_SECRET=********
JWT_HEADER=Authorization
JWT_IN_BODY=true
```

in NPM i use port 443
