### DISCUSSION TITLE
Its posibble set domain IP address and exposed port?

### DISCUSSION THREAD

**Discussion by chuchy4ever** [NginxProxyManager/nginx-proxy-manager#3882] [Q&A]
Hi,

i have a question. 

i have docker compose file

```
version: '3.9'

services:
  web:
    container_name: web
    image: ghcr.io/chuchy4ever/example:master
    restart: always
    volumes:
      - data:/srv/www/data
    expose:
      - 3000
    networks:
      default:
        ipv4_address: 172.19.0.100
volumes:
  data:

networks:
  default:
    external: true
    name: nginx-proxy
```

can I set mydomain.cz to point to the internal address 172.19.0.100 and port 3000? and at the same time mydomain.cz was accessible from a public address?

thanks
