### DISCUSSION TITLE
What is a good way to put NPM in a dark theme "dark mode"?

### DISCUSSION THREAD

**Discussion by Dvalin21** [NginxProxyManager/nginx-proxy-manager#3921] [Q&A]
Just as the title states.

**Comment by dacagi** [comment]
This is kind of documented [here](https://docs.theme-park.dev/themes/nginx-proxy-manager/#docker), and was discussed in [issue 707](https://github.com/NginxProxyManager/nginx-proxy-manager/issues/707#issuecomment-1201806010). In summary, you bind mount a script to NPM which then modifies the required frontend files and allows using ThemePark.dev themes.

The script you have to get is [here](https://raw.githubusercontent.com/themepark-dev/theme.park/refs/heads/develop/docker-mods/nginx-proxy-manager/root/etc/cont-init.d/98-themepark).


You place it somewhere that you can bind to the container. Ensure to assign it execution permission.

Eg: container files under /appdata/npm
```
cd /appdata/npm
wget https://raw.githubusercontent.com/themepark-dev/theme.park/refs/heads/develop/docker-mods/nginx-proxy-manager/root/etc/cont-init.d/98-themepark
chmod +x 98-themepark
```

Now in your compose file, you have to add an environment variable with the desired theme and an additional bind mount pointing to the script file.
```
...
environment:
  TP_THEME: dark
...
volumes:
  /appdata/npm/98-themepark:/etc/cont-init.d/98-themepark
```

And that's it.

For reference, here is my complete compose.yml using SQLite and dracula theme.
```
services:
  npm-lite:
    image: jc21/nginx-proxy-manager:2.11.3
    container_name: npm-lite
    hostname: npm-lite
    
    environment:
      DISABLE_IPV6: true
      DB_SQLITE_FILE: /data/database.sqlite
      TP_THEME: dracula
    
    volumes:
      - /port/dock/npm-lite/config.json:/app/config/production.json
      - /port/dock/npm-lite/data:/data
      - /port/dock/npm-lite/letsencrypt:/etc/letsencrypt
      - /port/dock/npm-lite/98-themepark:/etc/cont-init.d/98-themepark
    
    ports:
      - 80:80
      - 443:443
      - 81:81
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 30s
      timeout: 3s
```


Huge thanks to all the people involved in the original discussion!

Edit: I just modified the download URL for the themepark script. Thanks @rodrigomdomingos for noticing!
