### DISCUSSION TITLE
NGINX to NGINX Proxy Manager

### DISCUSSION THREAD

**Discussion by Partymann2000** [NginxProxyManager/nginx-proxy-manager#3936] [Q&A]
I have set up an NGINX web server with several configurations. In the `etc/nginx/sites-available/` directory, I have stored various configuration files for different sites that are accessible under subdomains of x.example.com (on the default port).

Here are my stored files:

dailyrewardplus.conf
dev.conf
...and others.
Everything works as desired. Now I have stopped the NGINX server, installed the NGINX Proxy Manager and started it in Docker.

How can I now access my subpages? These are configured in NGINX with the subdomains, but when I search for them in the Proxy Manager, it can't find them because NGINX is offline. Also, I can't run NGINX in parallel, otherwise the same port will be used.

(the docker and the nginx server on teh same servers, this is a conf from my `etc/nginx/sites-available/`

```
server {
    listen 148.251.48.2:80;
    server_name hosting.xenority.com;
    server_tokens off;
    return 301 https://$server_name$request_uri;
}

server {
    listen 148.251.48.2:443 ssl http2;
    server_name hosting.xenority.com;

    root /var/www/wemx/public;
    index index.php;

    access_log /var/log/nginx/wemx.app-access.log;
    error_log  /var/log/nginx/wemx.app-error.log error;

    # allow larger file uploads and longer script runtimes
    client_max_body_size 100m;
    client_body_timeout 120s;

    sendfile off;

    # SSL Configuration - Replace the example <domain> with your domain
    ssl_certificate /etc/letsencrypt/live/hosting.xenority.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/hosting.xenority.com/privkey.pem;
    ssl_session_cache shared:SSL:10m;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384";
    ssl_prefer_server_ciphers on;

    # See https://hstspreload.org/ before uncommenting the line below.
    # add_header Strict-Transport-Security "max-age=15768000; preload;";
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Robots-Tag none;
    add_header Content-Security-Policy "frame-ancestors 'self'";
    add_header X-Frame-Options DENY;
    add_header Referrer-Policy same-origin;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/run/php/php8.1-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param PHP_VALUE "upload_max_filesize = 100M \n post_max_size=100M";
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTP_PROXY "";
        fastcgi_intercept_errors off;
        fastcgi_buffer_size 16k;
        fastcgi_buffers 4 16k;
        fastcgi_connect_timeout 300;
        fastcgi_send_timeout 300;
        fastcgi_read_timeout 300;
        include /etc/nginx/fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}
```

This is my docker-compose.yml

```
version: "3"
services:
  app:
    image: jc21/nginx-proxy-manager:2.11.3
    restart: always
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./config.json:/app/config/production.json
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    environment:
    # if you want pretty colors in your docker logs:
    - FORCE_COLOR=1
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
    volumes:
      - ./data/mysql:/var/lib/mysql


```
