### DISCUSSION TITLE
I got an error saying "getaddrinfo EAI_AGAIN mysql"

### DISCUSSION THREAD

**Discussion by er-16** [NginxProxyManager/nginx-proxy-manager#3937] [Q&A]
Hi everyone,
I got an error saying "getaddrinfo EAI_AGAIN mysql" after running docker compose up. I don't know what I'm doing wrong. Is it supposed to use the "db" parameter instead of a custom one?
Here is my `compose.yaml` file:
```
services:
  nginx:
    image: jc21/nginx-proxy-manager:2.11.3
    hostname: nginx
    container_name: nginx
    depends_on:
      - mysql
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2gb
        reservations:
          cpus: "0.5"
          memory: 1gb
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      # PUID: 1000
      # PGID: 1000
      DB_MYSQL_HOST: mysql
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: nginx
      DB_MYSQL_PASSWORD: nginx
      DB_MYSQL_NAME: nginx
      # DISABLE_IPV6: true
      # X_FRAME_OPTIONS: deny # sameorigin
    volumes:
      - ${PWD}/nginx/data/:/data/
      # - ${PWD}/nginx/custom:/data/nginx/custom/
      - ${PWD}/nginx/letsencrypt/:/etc/letsencrypt/
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
      - 81:81

  mysql:
    image: mysql:8.4.2
    hostname: mysql
    container_name: mysql
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2gb
        reservations:
          cpus: "0.5"
          memory: 1gb
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABSE: nginx
      MYSQL_USER: nginx
      MYSQL_PASSWORD: nginx
    volumes:
      - ${PWD}/mysql/:/var/lib/mysql/

networks:
  proxy:
    name: proxy
    driver: bridge
```

**Comment by tigran-sargsyan-w** [comment]
DB_MYSQL_HOST: mysql is perfectly fine — Docker Compose service names can be used as DNS names. The service does not have to be named db.

The actual problem in your compose file is that the two containers are not on the same Docker network.

nginx is explicitly attached to:

```
networks:
  - proxy
```

but the mysql service has no networks: entry, so Compose places it on the project's default network.

As a result, the nginx container cannot resolve the hostname mysql, which explains:

`getaddrinfo EAI_AGAIN mysql
`
Attach MySQL to the same network:

```
mysql:
  image: mysql:8.4.2
  # ...
  networks:
    - proxy
```

You also have a typo here:

`MYSQL_DATABSE: nginx`

It should be:

`MYSQL_DATABASE: nginx`

Then recreate the stack:

```
docker compose down
docker compose up -d
```

You can verify Docker DNS resolution from the NPM container with:
`
docker compose exec nginx getent hosts mysql`

If it returns the MySQL container IP, the networking part is fixed.
