### DISCUSSION TITLE
Set up Https with NPM - SSL_ERROR

### DISCUSSION THREAD

**Discussion by alex-1987** [NginxProxyManager/nginx-proxy-manager#3985] [Q&A]
I'm trying to set up HTTPS for my service on my home server to allow access from outside. 

My plan is to install Seafile and a few other services, but first, I'm starting with the default Nginx Proxy Manager login page to get things working.
I followed a YouTube tutorial on setting up HTTPS and created a Debian virtual machine (VM) with Docker. I made the following nginx.yml file:
```
services:
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    container_name: nginx-proxy
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "db_nginx"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    depends_on:
      - db_nginx

  db_nginx:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    container_name: db_nginx
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - ./nginx/mysql:/var/lib/mysql
```
I set up two dynamic DNS (DDNS) records using dynu.com:
- alexfl.ddnsfree.com
- alexflhttps.ddnsfree.com

Both are pointing to my public IP address. On my modem, I configured IPv4 port mapping for ports 80 and 443 (TCP) and forwarded them to my OPNsense firewall IP: 192.168.18.111

In OPNsense, I created NAT rules to forward these ports to my Proxmox VM, which runs the Debian server with the Nginx Proxy Manager. IP: 10.0.0.150

_Picture Attached_

In Nginx Proxy Manager, I created an SSL certificate using DNS challenge verification through [Dynu.com](www.dynu.com) for my subdomains. I then set up two proxy hosts:

```
**alexfl.ddnsfree.com**
Source: http://nginx-proxy:81/
SSL: None (HTTP only)
Access: Public
Status: Online
```
```
**alexflhttps.ddnsfree.com**
Source: http://nginx-proxy:81/
SSL: Let's Encrypt
Access: Public
Status: Online
```
The website [alexfl.ddnsfree.com](http://alexfl.ddnsfree.com/) is accessible,
[alexflhttps.ddnsfree.com](https://alexflhttps.ddnsfree.com/) gives the error SSL_ERROR_RX_RECORD_TOO_LONG. 

I’ve checked many websites and tried several fixes, but I haven’t found a solution yet.

Has anyone some help for me?

thanks

![Port-Modem](https://github.com/user-attachments/assets/d22837cd-e2b6-4602-b50b-d50f5f316d5d)
![Port-OPN](https://github.com/user-attachments/assets/d89ef07e-d26c-4b0b-8a22-f7524ff5a467)
