### DISCUSSION TITLE
Unexpected error occurred:  OSError: [Errno 5] Input/output error

### DISCUSSION THREAD

**Discussion by akaii78** [NginxProxyManager/nginx-proxy-manager#4257] [Q&A]
Hi all,

I can't get my docker NPM working.
Here is my docker compose:
```
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      - '21:21'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - /docker_data/npm/backups:/backups
      - /docker_data/npm/letsencrypt:/etc/letsencrypt
      - /docker_data/npm/data:/data
    depends_on:
      - db
    networks:
      ai:

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - /docker_data/npm/mysql:/var/lib/mysql
    networks:
      ai:

networks:
  ai:
    external: true
    driver: overlay
```
And I keep getting error like this in my npm container:
```
An unexpected error occurred:
OSError: [Errno 5] Input/output error: '../../archive/npm-2/cert1.pem' -> '/etc/letsencrypt/live/npm-2/cert.pem'
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/letsencrypt-log/letsencrypt.log or re-run Certbot with -v for more details
```

Here are my host permissions on data, letsencrypt and mysql folders:
```
ll |grep mysql
drwxr-xr-x  6 dhcpcd   lxd      4096 Dec 26 19:35 mysql
ll |grep data
drwxr-xr-x  7 www-data www-data 4096 Dec 26 19:35 data
drwxr-xr-x  7 www-data www-data 4096 Dec 26 19:58 letsencrypt
id dhcpcd
uid=100(dhcpcd) gid=65534(nogroup) groups=65534(nogroup)
```
I would appreciate help guys.
At this point, I'm even wondering that might come from the fact that db and npm are on another swarm node from each other....... :)
