### DISCUSSION TITLE
Sadly this proxy manager does not work when needing to proxy to other containers within the same docker (eg wordpress)

### DISCUSSION THREAD

**Discussion by veletron2** [NginxProxyManager/nginx-proxy-manager#4263] [General]
As per the title - does not work for proxying a wordpress container that is running on the same docker.

Tried basically everything re suggestions for including both the proxy manager and wordpress container in the same docker network. I simply get error 502 from the proxy manager when trying to visit the URL - I assume that the proxy manager cannot 'see' the docker container.

I have tried forwarding to localhost, 127.0.0.1, 192.168.20.3 (the docker host IP), the docker network internal IP, the docker image name,  everything all to no avail. My wordpress is accessible locally just fine via http://192.168.20.3:20080

I can proxy to other machines on my network just fine - eg my home assistant VM - as such, the proxy manager its self is working fine - it just wont proxy to other dockers.

Loads of chatter about error 502 when accessing a wordpress container via a proxy in the forums, unfortunately - none of them actually solved. If anyone has an idea how I might make this work, I am all ears!

![image](https://github.com/user-attachments/assets/ab698d0c-14b8-4972-9721-eba9e0c6493d)

**Comment by jbcodemonkey** [comment]
With NPM and the Wordpress container on the same network, try using the container name as the 'forward hostname' and the internal listening port of the container (should be 80).

Within a docker network, container names resolve automatically and use the internal IPs and ports. Docker purposefully prevents containers from accessing other containers via their external ips/ports for security reasons, which sounds like what you are running into in your example.

I've been setting up NPM for the last two days, and most of my proxy hosts are referencing containername:internalport. With that in place and working, you don't even need to publish the external ports for the container and access it exclusively via NPM.

**Comment by veletron2** [comment]
Hi

I got this working shortly after pulling all my hair out and posting the message above!

In case its of assistance to others, below is how. Note that I am currently just using mappings as its on a NAS and easier to edit config if its in a file share I can see from PC. You will prob want to use docker-managed volumes instead. I am using Portainer to install, and doing so within a stack.

Assumptions:

- You have already setup the eg A records in your DNS to point at your public IP
- You are using a letsencrypt certificate
- You configured your router to forward port 443 to your docker_host_ip
- If you are using an http challenge for lets-encrypt, you have also forwarded port 80 to your docker_host_ip
- If you are using a DNS challenge, your DNS provider supports this and is supported within the acme lets encrypt client

**1) Install jc21/nginx-proxy-manager via the compose file below:**

```
services:
  webserver:
    container_name: nginx-reverse-proxy
    image: "jc21/nginx-proxy-manager:latest"
    ports:
      - 80:80 # Public HTTP Port
      - 81:81 # Admin Web Port
      - 443:443 # Public HTTPS Port
    volumes:
      - /share/Docker/nginx-reverse-proxy/data:/data
      - /share/Docker/nginx-reverse-proxy/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
```
    
 _The networks section creates a new network called frontend which is later also used by the wordpress stack_   
    
**2) Install Wordpress and its database via compose file below:**
 
 
```
services:
  db:
    container_name: wordpress-container-db
    image: mariadb:latest
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - /share/Docker/wordpress-localstore/wordpress-store-database:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=your-root-pass
      - MYSQL_DATABASE=wordpress-db-name
      - MYSQL_USER=wordpress-db-user
      - MYSQL_PASSWORD=your-db-pass
    expose:
      - 3306
    networks:
      - internal
  wordpress:
    container_name: wordpress-container-web
    image: wordpress:latest
    volumes:
      - /share/Docker/wordpress-local-store/wordpress-store-wpdata:/var/www/html
    ports:
      - 20080:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress-db-user
      - WORDPRESS_DB_PASSWORD=wordpress-db-pass
      - WORDPRESS_DB_NAME=wordpress-db-name
    networks:
      - nginx-reverse-proxy_frontend
      - internal

networks:
  nginx-reverse-proxy_frontend:
    external: true

  internal:
    driver: bridge
```

_There are two networks here, the nginx-reverse-proxy_frontend is the full name of the network created by the nginx compose file, that the wordpress stack also uses. This is specified as external: true indicating that it pre-exists. The 'internal' network is so that WP can communicate with its database. The full name for this ends up as: wordpress-container-web_internal_
    
**3) Bring Up the containers (stacks) and configure wordpress**

- Launch the proxy and the WP Containers (stacks)
- Browse to docker_host_ip:20080
- Install wordpress
- Login to wordpress
- visit settings
- Ensure that the Site URL matches that which you will use for the nginx-proxy incl the https:// (note that if you need to change it then you'll need to install phpmyadmin so you can get at the database (or just trash the volumes and start again!)

**4) Configure nginx**

- Browse to the nginx config page http://docker_host_ip:81
- Create a user and login
- In nginx-proxy-manager Generate a certificate for your URL
- In proxy manager, configure your new host thus:

![image](https://github.com/user-attachments/assets/836511d7-60ea-4838-85c5-5ce63bb851c1)

- the 'Forward Hostname / IP' is simply the name of the wordpress container - not an IP address and obv its port on the docker-host.
- Switch to the ssl tab, and select the certificate you created earlier, choose the 'force ssl' option
- Switch to the advanced tab and paste in the following:

```
location / {
    proxy_pass http://docker-host-ip:20080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_redirect off;
}
```

![image](https://github.com/user-attachments/assets/7fa6e474-8ad9-4b80-adcd-656a4e422cd2)

Setting the above *should* cause the proxy detection in wp-config.php to work, if it does not, edit wp-config.php and force the issue yourself, search for $_SERVER['HTTPS'] = 'on'; and then bung this in explicitly outwith the 'if' (note that I did not need this in the end)

**5) Troubleshooting**

- Most of the 'issues' I encountered were because I kinda half did the above initially the whole thing is finicky!
- If you get it wrong, the browser will likely cache the issue and then even when you get it right it wont blinking work properly
- Hit F12 to start developer tools, switch to the 'Network' tab, check 'Disable Cache' and reload the offending page. Once its loaded right you can re-enable the cache and close developer tools.

Hope this helps someone pull out less hair than I did.
