### DISCUSSION TITLE
connect() failed (113: No route to host) while connecting to upstream

### DISCUSSION THREAD

**Discussion by CodeWithCJ** [NginxProxyManager/nginx-proxy-manager#4266] [Q&A]
I am getting below error suddenly

2024/12/29 23:37:49 [error] 198#198: *3 connect() failed (113: No route to host) while connecting to upstream, client: MYIP, server: home.mydomain.buzz, request: "GET / HTTP/1.1", upstream: "http://10.0.0.10:3000/", host: "home.mydomain.buzz"

also "curl ip:port" also not working. basically npm unable to connect to my other services running in docker or inside the server.

below is my compose file and i am running npm via portainer.

```
services:
  app:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /home/ubuntu/SparkyApps/nginx/data:/data
      - /home/ubuntu/SparkyApps/nginx/letsencrypt:/etc/letsencrypt
```

my portainer compose:

```
services:
  portainer:
    image: portainer/portainer-ee
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/SparkyApps/portainer:/data

volumes:
  portainer_data:

```

With the same setup., I have another server in which "curl IP:PORT" works inside docker console of NPM. But in my oracle server, it is not working. I tried removing npm including the volume directories and re-created but still didn't work.
