### ISSUE TITLE
Docker Container can't start

### ISSUE THREAD

**Issue by d33pjs** [NginxProxyManager/nginx-proxy-manager#1091]
I have trouble with current Docker Images.

sha256:29aa3e4dbb2b1d58fcb69bb4d73745bc20c48ace12e4b9565d359caabbc16dc3 is working as expected:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01_s6-secret-init.sh: executing... 
[cont-init.d] 01_s6-secret-init.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Disabling IPV6 in hosts
❯ Disabling IPV6 in hosts: /etc/nginx/conf.d
  ❯ /etc/nginx/conf.d/include/letsencrypt-acme-challenge.conf
  ❯ /etc/nginx/conf.d/include/block-exploits.conf
  ❯ /etc/nginx/conf.d/include/proxy.conf
  ❯ /etc/nginx/conf.d/include/ip_ranges.conf
  ❯ /etc/nginx/conf.d/include/ssl-ciphers.conf
  ❯ /etc/nginx/conf.d/include/resolvers.conf
  ❯ /etc/nginx/conf.d/include/force-ssl.conf
  ❯ /etc/nginx/conf.d/include/assets.conf
  ❯ /etc/nginx/conf.d/production.conf
  ❯ /etc/nginx/conf.d/default.conf
Disabling IPV6 in hosts
❯ Disabling IPV6 in hosts: /data/nginx
  ❯ /data/nginx/default_host/site.conf
  ❯ /data/nginx/proxy_host/5.conf
  ❯ /data/nginx/proxy_host/3.conf
  ❯ /data/nginx/proxy_host/4.conf
  ❯ /data/nginx/proxy_host/1.conf

sqlite does not support inserting default values. Set the `useNullAsDefault` flag to hide this warning. (see docs http://knexjs.org/#Builder-insert).
[5/11/2021] [1:35:00 PM] [Migrate  ] › ℹ  info      Current database version: none
[5/11/2021] [1:35:01 PM] [IP Ranges] › ℹ  info      Fetching IP Ranges from online services...
[5/11/2021] [1:35:01 PM] [IP Ranges] › ℹ  info      Fetching https://ip-ranges.amazonaws.com/ip-ranges.json
[5/11/2021] [1:35:01 PM] [IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v4
[5/11/2021] [1:35:01 PM] [IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v6
[5/11/2021] [1:35:01 PM] [SSL      ] › ℹ  info      Let's Encrypt Renewal Timer initialized
[5/11/2021] [1:35:01 PM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[5/11/2021] [1:35:01 PM] [IP Ranges] › ℹ  info      IP Ranges Renewal Timer initialized
[5/11/2021] [1:35:01 PM] [Global   ] › ℹ  info      Backend PID 222 listening on port 3000 ... 
```

But this:
sha256:c9e7873e57504243f42daadf4ae43bd6274a6895f9cf7b5315024acf216a8f6e
and this (both pulled the last cpuple of days with "latest" tag)
sha256:ebe0f248625b27f2fced38dee520f1ead5ded7b954dfa8202306d7e5c9f1a0a0

give the following error on "docker-compose up -d":

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01_s6-secret-init.sh: executing... 
[cont-init.d] 01_s6-secret-init.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
./run: line 27: awk: command not found
Disabling IPV6 in hosts
❯ Disabling IPV6 in hosts: /etc/nginx/conf.d
  ❯ /etc/nginx/conf.d/include/letsencrypt-acme-challenge.conf
  ❯ /etc/nginx/conf.d/include/block-exploits.conf
  ❯ /etc/nginx/conf.d/include/proxy.conf
  ❯ /etc/nginx/conf.d/include/ip_ranges.conf
  ❯ /etc/nginx/conf.d/include/ssl-ciphers.conf
  ❯ /etc/nginx/conf.d/include/resolvers.conf
  ❯ /etc/nginx/conf.d/include/force-ssl.conf
  ❯ /etc/nginx/conf.d/include/assets.conf
  ❯ /etc/nginx/conf.d/production.conf
  ❯ /etc/nginx/conf.d/default.conf
Disabling IPV6 in hosts
❯ Disabling IPV6 in hosts: /data/nginx
  ❯ /data/nginx/default_host/site.conf
  ❯ /data/nginx/proxy_host/5.conf
  ❯ /data/nginx/proxy_host/3.conf
  ❯ /data/nginx/proxy_host/4.conf
  ❯ /data/nginx/proxy_host/1.conf
nginx: error while loading shared libraries: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
sqlite does not support inserting default values. Set the `useNullAsDefault` flag to hide this warning. (see docs http://knexjs.org/#Builder-insert).		
[5/11/2021] [1:33:34 PM] [Migrate  ] › ℹ  info      Current database version: none
./run: line 27: awk: command not found
Disabling IPV6 in hosts
❯ Disabling IPV6 in hosts: /etc/nginx/conf.d
[... loop ...]
```

I think, there are two errors:
`libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory`
and
`./run: line 27: awk: command not found`

My docker-compose.yaml:
```
version: "3"

networks:
  default:
    external:
      name: mynetwork

services:
  nginxprxmgr:
    #image: jc21/nginx-proxy-manager:latest # latest, hub.docker.com/r/jc21/nginx-proxy-manager/tags
    image: jc21/nginx-proxy-manager@sha256:29aa3e4dbb2b1d58fcb69bb4d73745bc20c48ace12e4b9565d359caabbc16dc3 
    container_name: nginxprxmgr
    restart: unless-stopped
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '81:81'
    environment:
      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: 'true'
    volumes:
      # Make sure this config.json file exists as per instructions above:
      - /mnt/data/nginx-proxy-manager/config.json:/app/config/production.json
      - /mnt/data/nginx-proxy-manager/data:/data
      - npmetc:/etc
      #- /mnt/data/nginx-proxy-manager/etc:/etc
      - /mnt/data/nginx-proxy-manager/letsencrypt:/etc/letsencrypt

volumes:
  npmetc:
```

- Ubuntu 20.04.2 LTS (5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux)
- Docker version 20.10.6, build 370c289
- docker-compose version 1.25.0, build unknown
