### ISSUE TITLE
Passing SSL certs to Meshcentral

### ISSUE THREAD

**Issue by unsounddabbit** [NginxProxyManager/nginx-proxy-manager#1144]
**Is your feature request related to a problem? Please describe.**
I love your conatiner and am new to Docker and Nginx.  I'm tying to get Meshcentral to work with your image, but I seem to be hitting a wall.  The issue is that nginx needs to pass the ssl cert to meshcentral.  The documentation in the link below on page 32 describes a sample file of nginx.conf.  I found this file in the container at /etc/nginx/nginx.conf, but yours is highly configured.    

https://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2UserGuide.pdf

**Describe the solution you'd like**
I would like to be able to set the environmental veriables to get Nginx to pass SSL to Meshcentral

**Describe alternatives you've considered**
If the nginx.conf file was imported in a way that made it easy to edit and import.  Any assistance on this would be appreciated.  I am a newbie to docker.

**Comment by apainter2** [comment]
I presume your running MeshCentral within a docker container.

You need to ensure that the meshcentral docker-compose environment variables are correct from the onset:

Example docker-compose.yml file:
```
version: '3'
services:
    meshcentral:
        restart: always
        container_name: meshcentral
        image: typhonragewind/meshcentral
        ports:
            - 8086:443  #MeshCentral will moan and try everything not to use port 80, but you can also use it if you so desire, just change the config.json according to your needs
        environment:
            - HOSTNAME=meshcentral.home.sanjiyan.com     #your hostname
            - REVERSE_PROXY=192.168.1.9     #set to your reverse proxy IP if you want to put meshcentral behind a reverse proxy
            - REVERSE_PROXY_TLS_PORT=443
            - IFRAME=false    #set to true if you wish to enable iframe support
            - ALLOW_NEW_ACCOUNTS=false    #set to false if you want disable self-service creation of new accounts besides the first (admin)
            - WEBRTC=true  #set to true to enable WebRTC - per documentation it is not officially released with meshcentral, but is solid enough to work with. Use with caution
        volumes:
            - ./meshcentral/data:/opt/meshcentral/meshcentral-data    #config.json and other important files live here. A must for data persistence
            - ./meshcentral/user_files:/opt/meshcentral/meshcentral-files    #where file uploads for users live
```

The important parts for this are the environment variables:
```
            - HOSTNAME=meshcentral.home.sanjiyan.com     #your hostname
            - REVERSE_PROXY=192.168.1.9     #set to your reverse proxy IP if you want to put meshcentral behind a reverse proxy
            - REVERSE_PROXY_TLS_PORT=443
```

Make sure that `HOSTNAME` points to your FQDN for meshcentral, the `REVERSE_PROXY `variable should be the IP address of the server which you run NPM on, and the `REVERSE_PROXY_TLS_PORT` port number is 443. (the REVERSE_PROXY_TLS_PORT is the port for HTTPS on NPM, which should the 443).

That's the meshcentral configuration, now let us define the NPM configuration:

Within NPM, create a new Proxy Host:

Domain Names: this your your FQDN for MeshCentral
Scheme: https
Forward Hostname/IP: IP address for MeshCentral (this should be the docker host IP address, unless your running MeshCentral docker on a maclvan network
Forward Port: 8086 (as per your meshcentral docker-compose.yml)
Cache Assets: Enable
Websockets Support: Enable, only if you set `WEBRTC=true` within the meshcentral docker-compose.yml file
Block Common Exploits: Enable

As per image:
![mesh1](https://user-images.githubusercontent.com/66255771/120544135-fe386280-c3e4-11eb-826b-f9d0d51c9690.PNG)

SSL Section:
SSL Certificate: Set this to the relevant SSL certificate
Force SSL: Enable
HTTP/2 Support: Enable
HSTS Enabled: Enable

As per image:
![mesh2](https://user-images.githubusercontent.com/66255771/120544262-1f994e80-c3e5-11eb-8da6-d6dc8dedea8a.PNG)



Thats it, meshcentral will now work as it should with NPM and SSL.
