### ISSUE TITLE
FORBIDDEN: Despite Documentation! Creating "Local only" Access List, requires PUBLIC IPs ONLY

### ISSUE THREAD

**Issue by hakunamatata97k** [NginxProxyManager/nginx-proxy-manager#1380]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

Despite what the [documentation](http://nginx.org/en/docs/http/ngx_http_access_module.html) say, adding local IPs, subnets, and local gateway is NOT working in my case!.

i used the following `docker-compose.yaml` file to do the installation: 
```

`  npm-app:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-app
    restart: always
    ports:
        - 80:80
        - 81:81
        - 443:443
    environment:
        - DB_MYSQL_HOST=npm-db
        - DB_MYSQL_PORT=3306
        - DB_MYSQL_USER=npm
        - DB_MYSQL_PASSWORD=PASSWORD
        - DB_MYSQL_NAME=npm
    volumes:
        - npm-data:/data
        - npm-ssl:/etc/letsencrypt
    networks:
        - nginx
  npm-db:
    image: jc21/mariadb-aria:latest
    container_name: nginx-db
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=PASSWORD
        - MYSQL_DATABASE=npm
        - MYSQL_USER=npm
        - MYSQL_PASSWORD=PASSWORD
    volumes:
        - npm-db:/var/lib/mysql
    networks:
        - nginx`

```
**The conf file:**
```

`------------------------------------------------------------
example.domain.com
------------------------------------------------------------
server { 
set $forward_scheme http; 
set $server         "myApp"; 
set $port           80;
listen 80; listen [::]:80;
server_name example.domain.com;
Block Exploits
include conf.d/include/block-exploits.conf;
proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection $http_connection; proxy_http_version 1.1;
access_log /data/logs/proxy-host-2_access.log proxy; error_log /data/logs/proxy-host-2_error.log warn;
location / {
# Access Rules
allow 0.0.0.0/8;
allow 192.168.0.0/24; # according to Wikipedia, this should be  normally sufficient. 
allow 192.168.0.0/16;# extra, 
allow 127.0.0.0/8;
allow 172.16.0.0/12;# according to Wikipedia, this should be  normally sufficient.  
allow 172.19.0.0/16;#extra, the proxy subnet
deny all;

# Access checks must...

satisfy all;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $http_connection;
proxy_http_version 1.1;


# Proxy!
include conf.d/include/proxy.conf;
}
Custom
include /data/nginx/custom/server_proxy[.]conf; }
```

**Nginx Proxy Manager Version**

I pulled the latest docker image: `docker pull jc21/nginx-proxy-manager:latest`

**Expected behavior**

its expected that the page would load without getting 403 ERROR forbidden!!!.

**Screenshots**

**Operating System**

Raspbian Os 64x, docker & Portainer. 

**Additional context**
