### ISSUE TITLE
Connection refused after changing ports

### ISSUE THREAD

**Issue by kopiezzo** [NginxProxyManager/nginx-proxy-manager#1553]
Hi, sorry if it has been asked already, i tried to look up an answer but i couldnt. I would like to remap ports but whenever im trying to do that, i get connection refused on all of my hosts.

This configuration **works**:
```
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm_app
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "MYPASSWORD"
      DB_MYSQL_NAME: "npm"
    volumes:
      - /home/lukasz/docker/npm/data:/data
      - /home/lukasz/docker/npm/letsencrypt:/etc/letsencrypt
    restart: always
```
This configuration (or any other ports i use) **does not work** and shows connection refused on every host:
```
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm_app
    ports:
      - '180:80'
      - '181:81'
      - '1443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "MYPASSWORD"
      DB_MYSQL_NAME: "npm"
    volumes:
      - /home/lukasz/docker/npm/data:/data
      - /home/lukasz/docker/npm/letsencrypt:/etc/letsencrypt
    restart: always
```
I am using it on a dedicated server from Hetzner.

I also get this in the logs after i change the ports:
```
2021/11/03 00:22:42 [error] 315#315: *1 connect() failed (111: Connection refused) while connecting to upstream, client: MYIP, server: nginxproxymanager, request: "GET /api/ HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "MYIP", referrer: "MYIP"
```

**Comment by chaptergy** [comment]
That's most likely because ports below 1024 are system ports and need root privileges to use them. Try ports which are 1024 or higher and see if that fixes the issue. But in general that's exactly how you change the ports

**Comment by lkopiec** [comment]
Thanks but i also tried 3000, 3001, 3002 and such and i have the same connection refused errors as before. The only ones that work are the default ones for me but i would like to change them.

**Comment by chaptergy** [comment]
Could it be that your server has some kind of restriction on which ports you can use? Or has some kind of firewall which blocks the requests? Because what you did is exactly how it _should_ work and works for me.

**Comment by lkopiec** [comment]
Hey so i wanted to test what you said so i launched portainer on port 3001 and it works fine so i guess nothing is blocking the requests. Is there anything left to check before removing and reinstalling npm along with all of its files?

**Comment by chaptergy** [comment]
I currently can't think of anything what could cause this issue. And I am not able to replicate it. When I create a docker-compose file with the data you provided (+ a db container) it works just as expected on port 180/181/1443.

```yml
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm_app
    ports:
      - '180:80'
      - '181:81'
      - '1443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    restart: always

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
```
