### ISSUE TITLE
After Updating to SQLITE problems changing settings.

### ISSUE THREAD

**Issue by MRC-Karel** [NginxProxyManager/nginx-proxy-manager#1643]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes 
- Are you sure you're not using someone else's docker image?
  - Yes 
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
Updated from the mariadb to sqlite using the provided tutorial. All looks ok, but when trying to add an entry it says "internal error". Looks like an issue with SQLITE: ```SQLITE_CONSTRAINT: NOT NULL constraint failed: proxy_host.id```

**Nginx Proxy Manager Version**
v2.9.12

** Docker Compose
```
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
      - '5900:5900'
    environment:
      - DB_SQLITE_FILE=/data/database.sqlite
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    restart: unless-stopped
```

*** Logs
https://pastebin.com/zeAbPriY
