### ISSUE TITLE
workaround for prompting the 'Bad Gateway' when you login after reboot the NPM container

### ISSUE THREAD

**Issue by sshuangliu** [NginxProxyManager/nginx-proxy-manager#1772]
**my env:**

pi 3 B+

**my configuration:**

version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    

**the screenshot:**

![image](https://user-images.githubusercontent.com/38092313/149952458-67a28d55-bcdc-4bce-9084-d4a5b68c50ca.png)

**workaround**

stop the container-------start the container-----login---------input: username: admin@example.com pwd: changeme (you need type the pwd again rathen then autofill by browser)-------prompt 'No relevant user found'------------use the normal credential to login----all works again!!!!

it doesn't work if you restart the  container

![image](https://user-images.githubusercontent.com/38092313/149954851-d07e88e1-7082-422e-be66-5d975b037a1c.png)

**the bug and the workaround can reappear，**
I have no idea about how to check what version the installed NPM  is 

sorry for my poor english
hope this would be useful for you

one more thing:
 I use 'portainer' to manage my container and deploy docker-compose

![image](https://user-images.githubusercontent.com/38092313/149958458-925c59d5-5f6d-4072-a3f1-4b5c80001917.png)

thanks
sam

**Comment by abhishekmj303** [comment]
I'm also having this problem but the workaround did not work for me.
I also use portainer. When I stopped the container and started the container again, it again showed "Bad Gateway".

OS: Ubuntu 20.04
NPM Version: 2.9.15

**Here are my logs of docker container when I stopped and started**:
```
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[1/28/2022] [1:51:44 PM] [Global   ] › ✖  error     ER_ACCESS_DENIED_ERROR: Access denied for user 'npm'@'172.22.0.2' (using password: YES)
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01_perms.sh: executing... 
Changing ownership of /data/logs to 0:0
[cont-init.d] 01_perms.sh: exited 0.
[cont-init.d] 01_s6-secret-init.sh: executing... 
[cont-init.d] 01_s6-secret-init.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
❯ Enabling IPV6 in hosts: /etc/nginx/conf.d
  ❯ /etc/nginx/conf.d/production.conf
  ❯ /etc/nginx/conf.d/include/proxy.conf
  ❯ /etc/nginx/conf.d/include/block-exploits.conf
  ❯ /etc/nginx/conf.d/include/ip_ranges.conf
  ❯ /etc/nginx/conf.d/include/ssl-ciphers.conf
  ❯ /etc/nginx/conf.d/include/assets.conf
  ❯ /etc/nginx/conf.d/include/force-ssl.conf
  ❯ /etc/nginx/conf.d/include/letsencrypt-acme-challenge.conf
  ❯ /etc/nginx/conf.d/include/resolvers.conf
  ❯ /etc/nginx/conf.d/default.conf
❯ Enabling IPV6 in hosts: /data/nginx
[1/28/2022] [1:51:55 PM] [Global   ] › ✖  error     ER_ACCESS_DENIED_ERROR: Access denied for user 'npm'@'172.22.0.2' (using password: YES)
[1/28/2022] [1:51:56 PM] [Global   ] › ✖  error     ER_ACCESS_DENIED_ERROR: Access denied for user 'npm'@'172.22.0.2' (using password: YES)
[1/28/2022] [1:51:57 PM] [Global   ] › ✖  error     ER_ACCESS_DENIED_ERROR: Access denied for user 'npm'@'172.22.0.2' (using password: YES)
[1/28/2022] [1:51:58 PM] [Global   ] › ✖  error     ER_ACCESS_DENIED_ERROR: Access denied for user 'npm'@'172.22.0.2' (using password: YES)
[1/28/2022] [1:51:59 PM] [Global   ] › ✖  error     ER_ACCESS_DENIED_ERROR: Access denied for user 'npm'@'172.22.0.2' (using password: YES)
```
 
**This is my docker-compose file**:
```
version: '3'
services:
        app:
                image: 'jc21/nginx-proxy-manager:latest'
                ports:
                        - '80:80'
                        - '81:81'
                        - '443:443'
                environment:
                        DB_MYSQL_HOST: "db"
                        DB_MYSQL_PORT: 3306
                        DB_MYSQL_USER: "npm"
                        DB_MYSQL_PASSWORD: "npm"
                        DB_MYSQL_NAME: "npm"
                volumes:
                        - ./data:/data
                        - ./letsencrypt:/etc/letsencrypt

        db:
                image: 'jc21/mariadb-aria:latest'
                environment:
                        MYSQL_ROOT_PASSWORD: 'npm'
                        MSQL_DATABASE: 'npm'
                        MYSQL_USER: 'npm'
                        MYSQL_PASSWORD: 'npm'
                volumes:
                        - ./data/mysql:/var/lib/mysql
```

**Comment by kt-solutions** [comment]
For me it worked to have this db-image instead of the latest:

`jc21/mariadb-aria:10.4.15-innodb`

**Comment by bencollinz** [comment]
This didn't work for me either. Updating didn't work either. I'm stuck. It's running but I can't log in. What changed?

**Comment by abhishekmj303** [comment]
@bencollinz this script worked for me : https://github.com/bmcgonag/docker_installs 
Also try rebooting the system before running the script.

**Comment by bencollinz** [comment]
> @bencollinz this script worked for me : https://github.com/bmcgonag/docker_installs Also try rebooting the system before running the script.

That didn't change anything, still get the bad gateway at login and this in logs:
`[3/30/2022] [1:56:25 PM] [Global   ] › ✖  error     connect EHOSTUNREACH 172.19.0.2:3306
[3/30/2022] [1:56:26 PM] [Global   ] › ✖  error     getaddrinfo EAI_AGAIN db
[3/30/2022] [1:56:27 PM] [Global   ] › ✖  error     getaddrinfo EAI_AGAIN db
[3/30/2022] [1:56:28 PM] [Global   ] › ✖  error     getaddrinfo EAI_AGAIN db
[3/30/2022] [1:56:29 PM] [Global   ] › ✖  error     getaddrinfo EAI_AGAIN db`

**Comment by lockheed** [comment]
I have the same problem since 2 or 3 months now, so I was unable to do any configuration change to NPM. Why is the no developer input on this fatal bug?

**Comment by ajcoll5** [comment]
@abhishekmj303 You've got a miss-spelling in your db environment variables - should be **MYSQL_DATABASE** not MSQL_DATABASE.

You might also be missing the config.json file. Under volumes, add the following:

`- ./config.json:/app/config/production.json`

Make sure you create a blank config.json file in your folder BEFORE starting the container - otherwise Docker will assume you want a folder and creates a folder.

**Comment by lockheed** [comment]
Switching to SQLite solved the problem for me. Contrary to the popular belief, SQLite seems to be a more performant option anyway.

**Comment by abhishekmj303** [comment]
> @abhishekmj303 You've got a miss-spelling in your db environment variables - should be **MYSQL_DATABASE** not MSQL_DATABASE.
> 
@ajcoll5 Oh, yeah. This might be the issue I had. Thank You.
> You might also be missing the config.json file. Under volumes, add the following:
> 
> `- ./config.json:/app/config/production.json`
> 
> Make sure you create a blank config.json file in your folder BEFORE starting the container - otherwise Docker will assume you want a folder and creates a folder.

But I think this is not necessary. I'm able to run without this line.

**Comment by truthsword** [comment]
I have this today. Runing npm on RPi container using Portainer Stack. All was good 6 weeks ago. Here is docker-compose:

```
version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '4443:4443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "nm"
      DB_MYSQL_PASSWORD: "nm"
      DB_MYSQL_NAME: "nm"
      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  db:
    image: 'yobasystems/alpine-mariadb:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'nm'
      MYSQL_DATABASE: 'nm'
      MYSQL_USER: 'nm'
      MYSQL_PASSWORD: 'nm'
    volumes:
      - ./data/mysql:/var/lib/mysql
      
```

Updated containers, stopped/started the stack, rebooted the RPI... all no joy.

Using for RP and LE wildcard cert updates. Everything is running, but I cannot enter. 

I saw a procedure for "forgotten" password... has anyone tried that?
