### ISSUE TITLE
connect sqlite with /var/lib/mysql ??

### ISSUE THREAD

**Issue by b4sh1t1** [NginxProxyManager/nginx-proxy-manager#1786]
Hello,

I was using mariadb to connect to discourse forum database in this way;

```
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    network_mode: bridge
    environment:
      MYSQL_ROOT_PASSWORD: 'my-super-safe-pwd'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'my-super-safe-pwd'
    volumes:
      - ./data/mysql:/var/lib/mysql
```

Where network_mode is connected to discourse network in dcoket and npm database to mounted in /var/lib/docker.

but in SQLite i don't know how or it's correct to mount it in same way ?  my current docker-compose 

```
version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    network_mode: bridge    <-- this network has been added to let NPM be in same discourse network, and they now see each others.
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '81:81'
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

```
