### ISSUE TITLE
502 Bad Gateway on login after upgrade to latest version

### ISSUE THREAD

**Issue by X4V1** [NginxProxyManager/nginx-proxy-manager#1793]
Hello,

I'm facing an issue after the upgrade from 2.9.7 to the latest version.
I'm running nginx-proxy-manager in docker on a raspberry pi os (3b+).
Everything was working fine before the update and after the upgrade only the login page stopped working (hosts configured before the upgrade still works)
I'm now getting a 502 Bad Gateway when I try to login. In the chrome debugger and I can see an HTTP call failing (POST /api/tokens)
The db used is maria-aria.
I can see multiple errors in docker logs but I don't understand what could be the cause. 
[log file available here](https://drive.google.com/file/d/1YYXWeQEEj8XHU2pchudR6_wCC5_0ozZC/view?usp=sharing)

my docker-compose looks like this:
```
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - /opt/nginx-proxy-manager/data:/data
      - /opt/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - /opt/nginx-proxy-manager/mysql:/var/lib/mysql
```

Any idea why the login page stopped working ?

UPDATE: downgraded to 2.9.14 and I'm now able to log in.  Probably related to #1769 . Closing issue.
