### ISSUE TITLE
NPM keeps deleting everything after computer is rebooted or Container

### ISSUE THREAD

**Issue by kylelliott** [NginxProxyManager/nginx-proxy-manager#1827]
i have built a docker Container NPM works amazing but i have a problem everytime the compuyer is reboot NPM deletes my users my domain my SSL and have keep setting it all up again 

any ideas why this keep happing would great

**Comment by jc21** [comment]
sounds like you are not mounting or using persistent docker data. The install instructions mention a `volumes` section in the docker-compose.yml file, make sure you have that

**Comment by kylelliott** [comment]
Hi 
I have just checked and I have both 
. /data:data 
. /letsencrypt:/etc/letsencrypt
Sent from myMail for Android Wednesday, 02 February 2022, 00:46am +00:00 from jc21  ***@***.*** :

**Comment by kylelliott** [comment]
Still having a massive problem with data and setting not being saved then if reboot al my setting are gone

**Comment by RafaelSchridi** [comment]
`. /data:data`


Pretty sure you're mapping /home/root/data here, it should be:
`. /data:/data`

**Comment by kylelliott** [comment]
just checked my yml file and . /data:/data and is all correct but still have a problem with it not working saving

**Comment by kylelliott** [comment]
can  i do a remote sesson if that works

**Comment by kylelliott** [comment]
version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

    depends_on:
      - db

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./data/mysql:/var/lib/mysql

**Comment by usmanatron** [comment]
You're mapping your mysql container to `/data/mysql` and NPM to `/data`.  Maybe the two of them aren't happy with sharing like that?
Try changing your MySql volume to `./mysql:/var/lib/mysql`.  That way they all have completely separate directories

**Comment by kylelliott** [comment]
still not working

**Comment by kylelliott** [comment]
can we do teamviewer access

**Comment by kylelliott** [comment]
im really struggling with this

**Comment by filipdot** [comment]
if you have root you can mkdir /opt/nginxpm and make mkdir for data, letsencrypt, mysql and mount it like this:
/opt/nginxpm/data:/data 
and so on.
If you use normal user you can make it under user directory. mkdir in /home/yourusernamehere/nginxpm/data:/data
And same for letsencrypt, mysql.

**Comment by kylelliott** [comment]
> if you have root you can mkdir /opt/nginxpm and make mkdir for data, letsencrypt, mysql and mount it like this:
> /opt/nginxpm/data:/data 
> and so on.
> If you use normal user you can make it under user directory. mkdir in /home/yourusernamehere/nginxpm/data:/data
> And same for letsencrypt, mysql.

I'm using Windows docker

**Comment by Mightyinks** [comment]
I'm having the same exact problem and no matter what I try, it doesn't work. I am also on windows docker. 

version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./data/mysql:/var/lib/mysql

**Comment by kylelliott** [comment]
at least im not the only person with problem using window docker and NPM

**Comment by fwuffyboi** [comment]
Heya! i also have this problem, sometimes it resets, other times it doesn't. My docker-compose.yml: 
```version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt```
  
I'm on a raspberry pi 4B+ 4GB ram running debian 11. i notice a data and letsencrypt folder in my home/{username} dir as well as my /home/{username}/NginxPM folder (it should be in the NginxPM folder.) not too sure what's causing this...
Has this been fixed?

**Comment by MHassanNadeem** [comment]
Did anyone figure out the cause for this? I am running nginx proxy manager on windows docker with WSL2 and experiencing the same issue. The logs on the mounted volume persist but it forgets everything else. `database.sqlite` is also empty.

**Comment by fwuffyboi** [comment]
> Heya! i also have this problem, sometimes it resets, other times it doesn't. My docker-compose.yml: 
> ```version: '3'
> services:
>   app:
>     image: 'jc21/nginx-proxy-manager:latest'
>     restart: always
>     ports:
>       - '80:80'
>       - '81:81'
>       - '443:443'
>     volumes:
>       - ./data:/data
>       - ./letsencrypt:/etc/letsencrypt```
>   
> I'm on a raspberry pi 4B+ 4GB ram running debian 11. i notice a data and letsencrypt folder in my home/{username} dir as well as my /home/{username}/NginxPM folder (it should be in the NginxPM folder.) not too sure what's causing this...
> Has this been fixed?

I just realized I never updated this.
my issue has gone away now, I believe it was due to me messing up where I was storing and starting my container so it's data would be in weird places. for the docker compose I recommend doing something like 
/home/user/npm/data:/data for volumes instead of something like ./ since that can be strange, or at least it was in my case.

**Comment by filipdot** [comment]
> /home/user/npm/data:/data for volumes instead of something like ./ since that can be strange, or at least it was in my case.

./ -> it mean "put your staff here"
eg:
./data:/data
/myfolderishere/data:/data

you define your stuff, not blindly copy paste ^^

**Comment by fwuffyboi** [comment]
> > /home/user/npm/data:/data for volumes instead of something like ./ since that can be strange, or at least it was in my case.
> 
> ./ -> it mean "put your staff here"
> eg:
> ./data:/data
> /myfolderishere/data:/data
> 
> you define your stuff, not blindly copy paste ^^

I know how paths work

**Comment by XoneDB4** [comment]
I had the same issue and solved it with the help of ChatGPT.

**Issue:**
After restarting the Nginx Proxy Manager (NPM) container, all custom settings (including the admin user) were lost. Although the MariaDB data persisted on disk, NPM was starting before the database was fully initialized, which caused it to revert to default configurations.

**Root Cause:**
NPM was attempting to connect to MariaDB before the database was ready. Additionally, the default health-check for MariaDB was triggering "Access denied" warnings because it didn't include the root password.

**The Fix:**

1. Added a Health Check for MariaDB:

Modified the MariaDB service in the docker-compose.yml file to include a health-check. The health-check uses the command:

```
test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p'PASSWORD'"]
```

This ensures that MariaDB is fully ready and authenticated before NPM starts.

2. Updated NPM Service to Depend on MariaDB Health:

Updated the depends_on configuration for the NPM service to wait until MariaDB is healthy before starting:

```
depends_on:
  mariadb:
    condition: service_healthy
```

**Outcome:**

With these changes, NPM now waits for a fully initialized and responsive MariaDB instance before starting up, preventing it from resetting its settings on container restart.

**Full Docker Compose:**

```
version: '3'

services:
  mariadb:
    image: 'jc21/mariadb-aria:latest'
    container_name: nginx-proxy-database
    environment:
      MYSQL_ROOT_PASSWORD: 'PASSWORD'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'PASSWORD'
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - frontend
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p'PASSWORD'"]
      interval: 10s
      retries: 5
      start_period: 20s

  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      DB_MYSQL_HOST: "mariadb"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "PASSWORD"
      DB_MYSQL_NAME: "npm"
      DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
    driver: bridge
```
