### ISSUE TITLE
unable to login to NPM

### ISSUE THREAD

**Issue by Swimbiggs** [NginxProxyManager/nginx-proxy-manager#1832]
Hi,

While I am able to get to the NPM page, when I try to sign in I get Bad Gateway

Setup:
Running a Raspberry Pi 4 with Debian - arm7 and the following is on top:
- Portainer
- Hassio
- OMV
- Jellyfin
- NextCloud

Guide followed: [https://nginxproxymanager.com/setup/#running-the-app](url)

docker-compose.yaml

```
version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '4443:4443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  db:
    image: 'yobasystems/alpine-mariadb:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./data/mysql:/var/lib/mysql

```

Log error:

```
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[2/6/2022] [10:19:01 AM] [Global   ] › ✖  error     ER_ACCESS_DENIED_ERROR: Access denied for user 'npm'@'172.21.0.3' (using password: YES)
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01_perms.sh: executing... 
Changing ownership of /data/logs to 0:0
[cont-init.d] 01_perms.sh: exited 0.
[cont-init.d] 01_s6-secret-init.sh: executing... 
[cont-init.d] 01_s6-secret-init.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Disabling IPV6 in hosts
❯ Disabling IPV6 in hosts: /etc/nginx/conf.d
  ❯ /etc/nginx/conf.d/include/proxy.conf
  ❯ /etc/nginx/conf.d/include/block-exploits.conf
  ❯ /etc/nginx/conf.d/include/ip_ranges.conf
  ❯ /etc/nginx/conf.d/include/ssl-ciphers.conf
  ❯ /etc/nginx/conf.d/include/assets.conf
  ❯ /etc/nginx/conf.d/include/force-ssl.conf
  ❯ /etc/nginx/conf.d/include/letsencrypt-acme-challenge.conf
  ❯ /etc/nginx/conf.d/include/resolvers.conf
  ❯ /etc/nginx/conf.d/default.conf
  ❯ /etc/nginx/conf.d/production.conf
Disabling IPV6 in hosts
❯ Disabling IPV6 in hosts: /data/nginx
[2/6/2022] [10:19:44 AM] [Global   ] › ✖  error     ER_ACCESS_DENIED_ERROR: Access denied for user 'npm'@'172.21.0.3' (using password: YES)
[2/6/2022] [10:19:45 AM] [Global   ] › ✖  error     ER_ACCESS_DENIED_ERROR: Access denied for user 'npm'@'172.21.0.3' (using password: YES)
[2/6/2022] [10:19:46 AM] [Global   ] › ✖  error     ER_ACCESS_DENIED_ERROR: Access denied for user 'npm'@'172.21.0.3' (using password: YES)
```
