### ISSUE TITLE
Not listening on port 81

### ISSUE THREAD

**Issue by ScottBeeson** [NginxProxyManager/nginx-proxy-manager#1917]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
I've followed the directions at https://nginxproxymanager.com/setup/#running-the-app 3 times. Each time restoring to a snapshot on the VM. Every time after I'm done, nothing is listening on port 81. I can access Nginx on port 80, but no NPM on 81. Doing a netstat shows nothing listening on port 81.

**Nginx Proxy Manager Version**
Good question, I can't get there :)

**To Reproduce**
1. Go to https://nginxproxymanager.com/setup/#running-the-app
2. Follow directions
3. Try to access http://[ipaddress]:81

**Expected behavior**
Presented with a webpage

**Screenshots**
n/a

**Operating System**
Ubuntu 20.04.4 LTS

**Additional context**
Here is the exact `docker-compose.yml` that I'm currently using (this is iteration 3).  The first two times I didn't change anything from the yml from the setup instructions.

```
version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    # Uncomment the next line if you uncomment anything in the section
    environment:
      # Uncomment this if you want to change the location of 
      # the SQLite DB file within the container
      DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: 'true'

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
```
