### ISSUE TITLE
Bug: Internal Error

### ISSUE THREAD

**Issue by avatar-lavventura** [NginxProxyManager/nginx-proxy-manager#1931]
I keep having `Internal Error` even the corresponding port is open, how could I fix it?

<img width="496" alt="image" src="https://user-images.githubusercontent.com/18537398/158054139-108879f7-8e7a-4351-8942-0cf6003f5e08.png">

**Comment by AnthoBalitrand** [comment]
Can you check your letsencrypt logs file ? 
It is probably because the letsencrypt challenge needed to validate you are the owner of the domain is failing. 
Do you have an existing DNS record pointing to your nginx server for the hostname you are using on this new proxy host ?

**Comment by avatar-lavventura** [comment]
@AnthoBalitrand I was trying to build it into an instance on digitial ocean.

*docker-compose.yml*:

```yaml
docker-compose.yml
version: "3"
services:
  app:
    image: "jc21/nginx-proxy-manager:latest"
    restart: always
    ports:
      # These ports are in format <host-port>:<container-port>
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "81:81" # Admin Web Port
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  db:
    image: "jc21/mariadb-aria:latest"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
    volumes:
      - ./data/mysql:/var/lib/mysql
```

----

*setup.sh*

```bash
#!/bin/bash

mkdir -p ~/docker
cp docker-compose.yml ~/docker
cd ~/docker
sudo chmod 666 /var/run/docker.sock
sudo systemctl restart docker
docker-compose up -d
docker ps
```

I open the ports here:

<img width="1232" alt="image" src="https://user-images.githubusercontent.com/18537398/159118742-6e5493cd-145a-4987-bda6-c37622fd6d86.png">


But I keep facing with the same error when I try to forward port for 5000.
