### ISSUE TITLE
port appended 

### ISSUE THREAD

**Issue by jiangge** [NginxProxyManager/nginx-proxy-manager#1953]
> Please try the `jc21/nginx-proxy-manager:github-develop` docker image, which has these headers removed and comment whether this is problem is fixed.

Hello jc21,

It's not been fixed yet, the docker-compose.yml is as follows:

```
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:github-develop'
    #image: 'jc21/nginx-proxy-manager:2.9.11'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./newdata:/data
      - ./newletsencrypt:/etc/letsencrypt
      #- ./data:/data
      #- ./letsencrypt:/etc/letsencrypt

```

_Originally posted by @jiangge in https://github.com/NginxProxyManager/nginx-proxy-manager/issues/1717#issuecomment-1078474293_
