### ISSUE TITLE
version 2.9.15 to 2.9.18 docker upgrade broke npm

### ISSUE THREAD

**Issue by DWShuo** [NginxProxyManager/nginx-proxy-manager#1996]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

Was running the docker image for version 2.9.15
Upgraded the docker image to 2.9.18 via `docker-compose pull && docker-compose up -d`
No WebUI, and website behind NPM shows  Error 521 

**Nginx Proxy Manager Version**

Cant access login page

**To Reproduce**
1. Running version 2.9.15
2. docker-compose down
3. docker-compose pull && docker-compose up -d

**Expected behavior**

192.168.0.100:81/ should show login page

**Operating System**

Ubuntu 21.10 inside LXC

**Additional context**

Error from docker log nginx-docker_app_1
```
nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/npm-1/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/npm-1/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
```

docker-compose.yml file since 2.9.15
```
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypts
```
File tree

```
|-- data
|   |-- access
|   |-- custom_ssl
|   |-- database.sqlite
|   |-- letsencrypt-acme-challenge
|   |-- logs
|   |   |-- default-host_access.log
|   |   |-- default-host_error.log
|   |   |-- fallback_access.log
|   |   |-- fallback_error.log
|   |   |-- proxy-host-1_access.log
|   |   `-- proxy-host-1_error.log
|   `-- nginx
|       |-- dead_host
|       |-- default_host
|       |   `-- site.conf
|       |-- default_www
|       |-- dummycert.pem
|       |-- dummykey.pem
|       |-- proxy_host
|       |   `-- 1.conf
|       |-- redirection_host
|       |-- stream
|       `-- temp
|-- docker-compose.yml
`-- letsencrypt
```
