### ISSUE TITLE
NPM Admin Panel timeout on Port 81

### ISSUE THREAD

**Issue by Ente** [NginxProxyManager/nginx-proxy-manager#2026]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
I've setup NPM on AWS.
Suddenly, I can't access the admin panel via port 81. Keeps returning a timeout.
I actually tried setting up the docker container several times, but ending up with the same results all the time.

I also checked AWS, if the port might be blocked there, but it's not.
Also I noticed, that `curl -is http://localhost:81` returns content. But when I'm trying it outside the machine, it returns nothing and again ends up with a timeout.

My docker-compose.yml is the following: 

```yml
version: '3'

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./data/mysql:/var/lib/mysql
```

Someone encountered the same and got a solution? Or might this be a AWS configuration problem on my behalf?

**Nginx Proxy Manager Version**
N/A

**To Reproduce**
visit [npm]:81

**Expected behavior**
Being able to access the admin interface via port 81

**Screenshots**
-

**Operating System**
Debian 10

**Additional context**
docker version: 18.09.1
