### ISSUE TITLE
Trying to point to npm itself to a sub domain

### ISSUE THREAD

**Issue by Horuyuki** [NginxProxyManager/nginx-proxy-manager#2091]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes / No

**Describe the bug**

Installed npm using docker. Used compose to run it. Opened port 81 so I could configure it via ip:81. Now I have an admin account, I want to put it under my domain: npm.example.com Added wild card with the token in cloudflare. ![](https://i.imgur.com/KQ0kLDL.png) Problem is I cannot appoint the correct proxy host for this to work.

**Nginx Proxy Manager Version**

v2.9.18

**To Reproduce**
![](https://i.imgur.com/5q8qMnU.png)
```
NETWORK ID     NAME          DRIVER    SCOPE
a2369a124003   bridge        bridge    local
2112b23fd832   host          host      local
aa8b1f598b48   none          null      local
3a2a6f6aad9c   npm_default   bridge    local
```
Docker network list. Tried npm_default in the forward hostname, 127.0.0.1, localhost.
**Expected behavior**
Go to  npm.example.com and see the npm login panel. I am met with error 520 instead.

**Screenshots**

Did include some.

**Operating System**

Ubuntu 20.04

Compose File:
```
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt 
  ```
Cloudflare DNS settings:
![](https://i.imgur.com/t0G9SNZ.png)
