### ISSUE TITLE
ssl_client_certificate

### ISSUE THREAD

**Issue by aaronbolton** [NginxProxyManager/nginx-proxy-manager#2102]
I would like the ability to use client certificate authentication so I believe I need to add 

  `ssl_client_certificate /etc/nginx/client_certs/ca.crt;`

and the relevant ca.crt to my trusted CA where would be the best Custom Nginx Config to place this and also would this be a consideration for the UI at some point?

**Comment by aaronbolton** [comment]
Does this keep the setting between updates then? as I found I can go in to each and change and random setting on/off then it fixes it for that host

**Comment by poaudet** [comment]
If you have set your volume to be persistent (eg: you have a folder on your host to store your /data/ folder from the container) you should be good!

see Quick Setup:
```
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
```
