### ISSUE TITLE
Can NPM ignore nginx: [emerg] host not found in upstream error?

### ISSUE THREAD

**Issue by Horuyuki** [NginxProxyManager/nginx-proxy-manager#2116]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes 
- Are you sure you're not using someone else's docker image?
  - Yes 
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

**Nginx Proxy Manager Version**

NPM shows error at container up and won't start.

**To Reproduce**
1. back up docker compose directory data with autorestic
2. restore the exact same files with autorestic
3. restart npm
4. [error log](https://pastebin.com/xEpJYnP0)
This is the errored line: 
```
    proxy_pass       http://nextcloud:80/remote.php/dav;
```

**Expected behavior**

Just start right up, same container and host machine.

**Screenshots**
no

**Operating System**
ubuntu 20.04

**Additional context**
latest pulled docker version.
```
~/npm$ sudo docker compose pull
[+] Running 1/1
 ⠿ app Pulled
```
```
 "NPM_BUILD_VERSION=2.9.18",
```

compose file:

```
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      #- '81:81'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    container_name: npm
```

My current solution is to bomb the whole data folder and manually add back each domain, but that is a huge hassle, why doesn't the exact same data directory work?

EDIT:
Once I removed that conf file, the next conf files just continues to show the same error.
