### ISSUE TITLE
1024 worker_connections are not enough

### ISSUE THREAD

**Issue by kizza42** [NginxProxyManager/nginx-proxy-manager#2166]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
Over the past few days, I am increasingly getting dropouts when accessing my proxied services. I have tried restarting the container which does seem to temporarily alleviate the issue but after 40-50 mins I start getting dropouts again. The Error logs are full of entries like:
`1024 worker_connections are not enough`

The issue only occurs with comms via NPM, If I direct access the services, there are no dropouts.

**Nginx Proxy Manager Version**
v2.9.18

**To Reproduce**
1. Spin up container
2. Have it server a few *Arrr sites + Home assistant etc. Total 8 Proxy hosts + 1 Stream for Torrents

**Expected behavior**
Is there a way to tune this? Provide more worker connections?

**Screenshots**
_Services are monitored via their domain name/NPM and via local IP. Only the proxied hosts experience drops in comms. Direct monitoring of the hosted services via direct IP shows no drops from the individual hosts._
![image](https://user-images.githubusercontent.com/12605257/180593119-22a32a91-bbdd-472f-9e03-9db07b6a27d9.png)

**Operating System**
Docker running on a Qnap nas via Docker-Compose

**Additional context**
Compose file:
```
version: '3.7'
services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    restart: always
    environment:
      - PUID=1002 # set to UID of your user
      - PGID=100  # set to GID of your user
      - TZ=Australia/Sydney #Set TimeZone
    volumes:
      - /share/CACHEDEV1_DATA/SSD/Docker/NginxProxyManager/data:/data # Config Dir
      - /share/CACHEDEV1_DATA/SSD/Docker/NginxProxyManager/etc/.letsencrypt:/etc/letsencrypt # Config Dir
    ports:
      - '80:80' # <Host Port>:<Container Port> Web Service
      - '443:443' # <Host Port>:<Container Port> Web Service
      - '82:81' # <Host Port>:<Container Port> Dashboard
    networks:
      dockerlan-static:
        ipv4_address: 192.168.0.9
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s

networks:
  dockerlan-static:
    external: true
```
