### ISSUE TITLE
Custom Certificate Import not working- Upload Failed:0

### ISSUE THREAD

**Issue by ghostersk** [NginxProxyManager/nginx-proxy-manager#2191]
EDIT:
The issue was not in docker, but it could not read the certificates, as it was created with sudo... I do not understand why it could not read those files when I could read them without sudo as normal user

-----------
I just installed NPM and try to add my self signed certs. I tried multiple generating methods but none of them works. It is latest Docker installation.
![Screenshot_20220807_134641](https://user-images.githubusercontent.com/68815071/183291217-cd0fbecb-d87f-4c16-8996-a7ad699aa4be.png)

```
version: '3'
networks:
  main:
    external: true
services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    hostname: npm
    environment:
      DISABLE_IPV6: 'true'
    networks:
      main:
        ipv4_address: 10.100.111.253
    ports:
      - '127.0.0.1:80:80'
      - '127.0.0.1:81:81'
      - '127.0.0.1:443:443'
    volumes:
      - /opt/configdockers/npm/data:/data
      - /opt/configdockers/npm/letsencrypt:/etc/letsencrypt
```
I tried to generate Certificates with CA and import cert-key.pem as key and cert.pem as certificate:
```
sslpath=$(pwd)
mycn="localserver"
dnsname="*.local.com"

echo "Generating CA key and cert"
openssl genrsa -aes256 -out $sslpath/cakey.pem 4096
openssl req -new -x509 -sha256 -days 3650 -key $sslpath/cakey.pem \
-out $sslpath/ca.pem 
mkdir -p /usr/local/share/ca-certificates
cp $sslpath/ca.pem /usr/local/share/ca-certificates/ca.crt
sudo update-ca-certificates

echo "Generating RSA Key cert-key.pem"
openssl genrsa -out $sslpath/cert-key.pem 4096
mkdir -p $sslpath/$mycn
echo "Creating CSR: $sslpath/$mycn/cert.csr"
openssl req -new -sha256 -subj "/CN=$mycn" -key $sslpath/cert-key.pem \
-out $sslpath/$mycn/cert.csr
echo "subjectAltName=DNS:$dnsname" > $sslpath/$mycn/extfile.cnf
echo "Creating Certificate $sslpath/$mycn/cert.pem"
openssl x509 -req -sha256 -days 3650 -in $sslpath/$mycn/cert.csr \
-CA $sslpath/ca.pem -CAkey $sslpath/cakey.pem \
-out $sslpath/$mycn/cert.pem -extfile $sslpath/$mycn/extfile.cnf \
-CAcreateserial
```
Also I just tried to generate simple certificate but still same issue:
```
openssl req -x509 -nodes -days 3650 -subj "/C=GB/ST=QC/O=Company, Inc./CN=test.com" -addext "subjectAltName=DNS:*.test.com;test.com" -newkey rsa:2048 -keyout key.key -out cert.crt;
```
No posts here given me any solution. I believe it was said that this is already solved in all of them.
I have suspicion that it cannot upload those certificates, but i cannot find any reason why as there is no error in NPM logs
I tried to run it from localhost:81, 127.0.0.1:81 and from the docker image ip too
