### ISSUE TITLE
Unable to login to Admin UI

### ISSUE THREAD

**Issue by skirven4** [NginxProxyManager/nginx-proxy-manager#2304]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

On version 2.9.18, I am unable to login to the NPM UI. Yes, I can downgrade to 2.9.14 and get it to work, sort of.

**Nginx Proxy Manager Version**

2.9.18

**To Reproduce**
1. Go to the login page at http://<server>:81
2. Enter your Username and Password
3. The login just comes back with either "Bad Gateway" in red text, or simply will not login.
4. Check the logs in your file system path ./data/logs/fallback_error.log

`2.168.0.196, server: nginxproxymanager, request: "POST /api/tokens HTTP/1.1", upstream: "http://127.0.0.1:3000/tokens", host: "nettools.local:81", referrer: "http://nettools.local:81/login"
`

**Expected behavior**

User should be able to login to the system

**Screenshots**

**Operating System**

Raspian OS

**Additional context**

I find this token api error strange. I'm also getting a "Bad Gateway" nginx message on url <host>:81/api, as I tried that after finding an older issue that seemed similar. I also rebuilt my docker-compse.yml. Additionally, the port 3000 is not open in my installation, either at the host, or inside the container.

```
version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:2.9.18'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      - '8089:8089'
      - '57000:57000'
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    # Uncomment the next line if you uncomment anything in the section
    # environment:
      # Uncomment this if you want to change the location of 
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
```
