### ISSUE TITLE
[Chaching] `Ctrl+F5` does not help - New DNS Provider doesn't show up in the frontend after updating docker compose

### ISSUE THREAD

**Issue by knoxell** [NginxProxyManager/nginx-proxy-manager#2314]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  -  No
- Are you sure you're not using someone else's docker image?
  - Yes 
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

I updated my `docker-compose.yml` from `jc21/nginx-proxy-manager:github-pr-2272` to `jc21/nginx-proxy-manager:github-pr-3212` 
[#3212](https://github.com/NginxProxyManager/nginx-proxy-manager/pull/2312) only adds a new certbot plugin requested in #2086. 

The new DNS Provider doesn't show up in the frontend. Not even deleting the container and `docker compose up` help.

Spinning up a new container and logging into the admin UI, the added certbot-plugin shows up, when adding a new Let's Encrypt Certificate  with

```
docker run -p 127.0.0.1:3081:81 jc21/nginx-proxy-manager:github-pr-3212
```

**Nginx Proxy Manager Version**

v2.9.18

**To Reproduce**
- Use `jc21/nginx-proxy-manager:github-pr-2272` with certificates and proxy rules with compose file as pasted below.
- update tag to `jc21/nginx-proxy-manager:github-pr-3212` in compose file.
- Add new Let's Encrypt Certificate.
  - Choose DNS Provider
  - Namecheap is not an option

**Expected behavior**

updating the docker compose file and redeploying npm with it should update the frontend 
- Use `jc21/nginx-proxy-manager:github-pr-2272` with certificates and proxy rules with compose file as pasted below.
- update tag to `jc21/nginx-proxy-manager:github-pr-3212` in compose file.
- Add new Let's Encrypt Certificate.
  - Choose DNS Provider
  - Namecheap is an option as if I created a new container
 
**Operating System**

Debian Bullseye

**Additional context**

My `docker-compose.yml`
```yaml
version: '3'
services:
  app:
    container_name: nginxproxymanager
    image: 'jc21/nginx-proxy-manager:github-pr-2312' # the only change happend here
    restart: unless-stopped
    ports:
      - '80:80'
      - '127.0.0.1:8111:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
networks:
  default:
    name: reverseproxy
```

My `docker ps` :
```
CONTAINER ID   IMAGE                                     COMMAND                  CREATED          STATUS         PORTS
                      NAMES
c5bd39d22a6b   jc21/nginx-proxy-manager:github-pr-2312   "/init"                  7 minutes ago    Up 6 minutes   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp, 127.0.0.1:8111->81/tcp   nginxproxymanager
c8c1f7981cd8   jc21/nginx-proxy-manager:github-pr-2312   "/init"                  54 minutes ago   Up 4 minutes   80/tcp, 443/tcp, 127.0.0.1:3081->81/tcp
```
