### ISSUE TITLE
Getting a ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by sgtcoder** [NginxProxyManager/nginx-proxy-manager#2318]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
Yes
- Are you sure you're not using someone else's docker image?
No
- Have you searched for similar issues (both open and closed)?
Yes

**Describe the bug**
This is the docker compose file
```
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /root/nginx:/data
      - /root/letsencrypt:/etc/letsencrypt
```
Then I run
```
docker compose -f /root/docker-compose.yml up -d
```

I try to goto the web page: http://10.0.6.23:81 and I get a ERR_CONNECTION_REFUSED.

I tried to even `telnet 10.0.6.23 81` and `telnet 127.0.0.1 81`, I also get connection refused. Some dockers I have this problem with, while others I don't. I also removed all my running dockers and networking. Yes of course I can ping.

**Nginx Proxy Manager Version**
the latest

**To Reproduce**
Described above

**Expected behavior**
The webpage should load

**Screenshots**
[telnet 10.0.6.23 81](https://gyazo.com/56cbf52f192e74866676fcf50a7609a5)

**Operating System**
Debian 11

**Additional context**
Latest of everything
