### ISSUE TITLE
Add ability to configure "worker_processes"

### ISSUE THREAD

**Issue by PingTrip** [NginxProxyManager/nginx-proxy-manager#2388]
**Is your feature request related to a problem? Please describe.**
For a home network/low traffic deployment the current setting of `worker_processes auto;` is overkill since it spawns an nginx process for every core. 

**Describe the solution you'd like**
Provide a mechanism to override the current hard-coded "auto" setting.

**Describe alternatives you've considered**
I tried overriding the parameter via `/data/nginx/custom/root.conf` which resulted in an Nginx error:
`nginx: [emerg] "worker_processes" directive is duplicate in /data/nginx/custom/root.conf:1`.

**Comment by k4my4b** [comment]
Exact same issue here.
An environment variable like `WORKER_PROCESSES` would suffice.
But while we're at it can we please add environment variables for [thread pools](https://www.nginx.com/blog/thread-pools-boost-performance-9x/) as well, thanks!

**Comment by fevernova90** [comment]
Bump up! 

Using this in production of a small growing app. There's no direct way to override `worker_connections`. 1024 is surely not enough.

**Comment by CreeperFace00** [comment]
Having this issue as well, would love to see this implemented!

**Comment by msycn** [comment]
same here please help us to change worker_connections

**Comment by msycn** [comment]
> @msycn That is already possible thanks to the commit @Blooym made. Just put that line in and it will work just fine.`/data/nginx/custom/events.conf`

Wow ,you are my hero ! Thanks for your quick reply!!!

**Comment by ansred** [comment]
@kroese getting the same issue, as reported here:

https://github.com/NginxProxyManager/nginx-proxy-manager/issues/3345

Any idea what is that line for?
`/data/nginx/custom/events.conf`

Do we add it as env in the docker compose? or is it something else?

**Comment by ansred** [comment]
@kroese Here is my docker compose

```
version: "3"

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: Nginx_Proxy_Manager_SQLite
    restart: always
    ports:
      - '80:80'        # Public HTTP Port:
      - '443:443'      # Public HTTPS Port:
      - '81:81'        # Admin Web Port:
    environment:
        DB_SQLITE_FILE: "/data/database.sqlite"
        DISABLE_IPV6: 'true'

    volumes:
      - /volume1/docker/containers/npm/config/data:/data
      - /volume1/docker/containers/npm/config/cert:/etc/letsencrypt

```

I assume, in `/docker/containers/npm/config/data/nginx` just create the directory `/custom` and file `/events.conf`

And no other mapping required and things should work?
