### ISSUE TITLE
JavaScript Knex TypeError in inital provisioning of database

### ISSUE THREAD

**Issue by nickramsbottom** [NginxProxyManager/nginx-proxy-manager#2510]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
The logs for the application image have this over and over again on first startup:

```
/app/node_modules/knex/lib/constants.js:19
  ].concat(keys(CLIENT_ALIASES))
������
           ^
TypeError: keys is not a function
    at Object.<anonymous> (/app/node_modules/knex/lib/constants.js:19:12)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/app/node_modules/knex/lib/helpers.js:10:28)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
./run: line 19:  1300 Aborted                 (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 index.js
```

**Nginx Proxy Manager Version**
v2.9.19

**To Reproduce**
1. Have a Raspberry Pi 3 Model B running Raspbian
2. Use the following docker-compose config from the docs:
```
version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  db:
    image: 'yobasystems/alpine-mariadb:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./data/mysql:/var/lib/mysql
```
3. `docker-compose up -d`
4. look at the logs for `nginx_app_1` container: `docker logs nginx_app_1`

**Expected behavior**
Successful setup of the database.

**Screenshots**
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/21983479/210104982-f9b8c489-c5aa-4547-bc36-389930815e80.png">

**Operating System**
Raspberry Pi 3 Model B, Raspbian GNU/Linux 10 (buster)

**Additional context**
Docker version 20.10.22, build 3a2c30b
