### ISSUE TITLE
Rancher Desktop on Mac - Server Not Starting Permission Errors

### ISSUE THREAD

**Issue by dro-ex** [NginxProxyManager/nginx-proxy-manager#2541]
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
Server will not start using Rancher Desktop on mac.  Server was working on Docker Desktop

**Nginx Proxy Manager Version**
Latest as of 01*14*2022

Error Logs:
```
Enabling IPV6 in hosts: /etc/nginx/conf.d
/etc/nginx/conf.d/include/ssl-ciphers.conf
/etc/nginx/conf.d/include/proxy.conf
/etc/nginx/conf.d/include/letsencrypt-acme-challenge.conf
/etc/nginx/conf.d/include/force-ssl.conf
/etc/nginx/conf.d/include/ip_ranges.conf
/etc/nginx/conf.d/include/block-exploits.conf
/etc/nginx/conf.d/include/assets.conf
/etc/nginx/conf.d/include/resolvers.conf
/etc/nginx/conf.d/production.conf
/etc/nginx/conf.d/default.conf
Enabling IPV6 in hosts: /data/nginx
nginx: [emerg] open() "/data/logs/fallback_error.log" failed (13: Permission denied)
[1/15/2023] [7:30:17 AM] [Global   ] › ✖  error     getaddrinfo ENOTFOUND db
```
**Operating System**
Intel Mac - Rancher Desktop 1.7.0

Docker Compose File:
```
version: "3"
services:
  app:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: npm_app
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
       DB_MYSQL_HOST: "db"
       DB_MYSQL_PORT: 3306
       DB_MYSQL_USER: "xxx"
       DB_MYSQL_PASSWORD: "xxxxxx"
       DB_MYSQL_NAME: "npm"
    volumes:
      - /Users/usermain/appdata/docker/nginx_proxy_manager/data:/data
      - /Users/usermain/appdata/docker/nginx_proxy_manager/etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: "jc21/mariadb-aria:latest"
    container_name: npm_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "xxx"
      MYSQL_PASSWORD: "xxxxxx"
    volumes:
      - /Users/usermain/appdata/docker/nginx_proxy_manager/data/mysql:/var/lib/mysql
```

**Comment by dro-ex** [comment]
After a complete reinstall of rancher desktop i get this:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01_perms.sh: executing... 
Changing ownership of /data/logs to 0:0
[cont-init.d] 01_perms.sh: exited 1.
chown: changing ownership of '/data/logs': Permission denied
!!!!!
 init-stage2 failed.
!!!!!
```

**Comment by dro-ex** [comment]
temporary workaround fix:

changed mapping: 
```
volumes:
  - /Users/usermain/appdata/docker/nginx_proxy_manager/data:/data
  - /Users/usermain/appdata/docker/nginx_proxy_manager/etc/letsencrypt:/etc/letsencrypt
  - /data/logs:/data/logs   <---- added
```
and commented out port:
```
environment:
       DB_MYSQL_HOST: "db"
       #  DB_MYSQL_PORT: 3306
       DB_MYSQL_USER: "xxx"
       DB_MYSQL_PASSWORD: "xxxxxx"
       DB_MYSQL_NAME: "npm"
```
