### ISSUE TITLE
Can't show the Client real ip

### ISSUE THREAD

**Issue by g-marinov** [NginxProxyManager/nginx-proxy-manager#2573]
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes 

**Describe the bug**
No matter what I did can't see the client real IP, I can see only the docker IP.

LOGS:
_**web-address** is the webpage I'm accessing_

```
[31/Jan/2023:08:51:36 +0000] - 200 200 - GET http web-address "/openapi.json" [Client 192.168.208.1] [Length 1384] [Gzip -] [Sent-to 192.168.2.140] "Mozilla/5.0 (Linux; Android 12; SM-S901B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Mobile Safari/537.36" "http://web-address/docs"
[31/Jan/2023:08:51:39 +0000] - 200 200 - GET http web-address "/X-Real-IP" [Client 192.168.208.1] [Length 27] [Gzip -] [Sent-to 192.168.2.140] "Mozilla/5.0 (Linux; Android 12; SM-S901B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Mobile Safari/537.36" "http://web-address/docs"
[31/Jan/2023:08:51:46 +0000] - 200 200 - GET http web-address "/X-Forwarded-For" [Client 192.168.208.1] [Length 27] [Gzip -] [Sent-to 192.168.2.140] "Mozilla/5.0 (Linux; Android 12; SM-S901B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Mobile Safari/537.36" "http://web-address/docs"
```

**Nginx Proxy Manager Version**
jc21/nginx-proxy-manager:latest

```
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
```

**Operating System**
Docker Desktop

**Additional context**
FastApi

```
from typing import Union
from fastapi import FastAPI, Header, Request

app = FastAPI()

@app.get("/X-Forwarded-For")
async def root(request: Request):
    my_header = request.headers.get('X-Forwarded-For')
    return {"message": my_header}

@app.get("/X-Real-IP")
async def root(request: Request):
    my_header = request.headers.get('X-Real-IP')
    return {"message": my_header}
```

**Comment by navhawk80** [comment]
Hi. Had the same issue and just fin out next solution.
Try to use
```
    ports:
      - target: 443
        published: 4443 # Outside port
        mode: host
        protocol: tcp
      - target: 80
        published: 480 # Outside port
        mode: host
        protocol: tcp
      - target: 81
        published: 481 # Outside port
        mode: host
        protocol: tcp
```
For me it works.
