### ISSUE TITLE
after upgrading to v2.10.0 from v2.9.19  Table 'npm.audit_log' doesn't exist 

### ISSUE THREAD

**Issue by remisharrock** [NginxProxyManager/nginx-proxy-manager#2772]
I do have this error after upgrading to v2.10.0 from v2.9.19 :

[3/29/2023] [10:46:41 AM] [Express  ] › ⚠  warning   select `audit_log`.* from `audit_log` order by `created_on` DESC, `id` DESC limit 100 - ER_NO_SUCH_TABLE: Table 'npm.audit_log' doesn't exist

when I navigate to the audit log I have  500 — Internal Error 

thanks for the help

**Comment by remisharrock** [comment]
forgot to mention I use this docker compose file

```
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "************"
      DB_MYSQL_PASSWORD: "****************"
      DB_MYSQL_NAME: "*********************"
    volumes:
      - /root/npm/data:/data
      - /root/npm/letsencrypt:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '******************'
      MYSQL_DATABASE: '******************'
      MYSQL_USER: '*****************'
      MYSQL_PASSWORD: '************************'
    volumes:
      - /root/npm/data/mysql:/var/lib/mysql
```
