### ISSUE TITLE
Is it possible to change the nginx port if running macvlan?

### ISSUE THREAD

**Issue by cwesterfield** [NginxProxyManager/nginx-proxy-manager#2778]
I'm running my instance on my lan and somehow I have it running on 4443. I'd like to change that to 443 so I can try using NPM on my LAN. Is this possible?

```
  nginx-proxy-manager:
    image: jlesage/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    networks:
      LAN:
        ipv4_address: 10.0.1.201
    volumes:
      - /srv/NGINX-PROXY:/config
      - /srv/NGINX-PROXY/data/log:/data/log
    restart: unless-stopped
```

```
bash-5.1# netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:25000           0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.11:38307        0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:4443            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:8181            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      -
tcp        0      0 :::25000                :::*                    LISTEN      -
tcp        0      0 :::3000                 :::*                    LISTEN      -
tcp        0      0 :::4443                 :::*                    LISTEN      -
tcp        0      0 :::8181                 :::*                    LISTEN      -
tcp        0      0 :::8080                 :::*                    LISTEN      -
bash-5.1# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
73: eth0@if2: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
    link/ether 02:42:0a:00:01:c9 brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.201/24 brd 10.0.1.255 scope global eth0
       valid_lft forever preferred_lft forever
bash-5.1# 
```
