### ISSUE TITLE
JSON-Error in Backend while generating SSL-Certificates

### ISSUE THREAD

**Issue by dravorle** [NginxProxyManager/nginx-proxy-manager#2796]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

I am unable to create an SSL certificate for my websites. The API simply returns a 502-Error after a while, showing the message "Communication with the API failed, is NPM running correctly?".
In the Docker-Logs I can see that it fails with the following:

```
[4/2/2023] [8:38:23 PM] [SSL      ] › ℹ  info      Testing http challenge for domain.de
Uncaught SyntaxError: Unexpected token < in JSON at position 5
FROM
bash: line 1:   134 Trace/breakpoint trap   (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 index.js
❯ Starting backend ...
```

If I try a subdomain it fails with another JSON-Error:

```
[4/2/2023] [8:50:06 PM] [SSL      ] › ℹ  info      Testing http challenge for test.domain.de
Uncaught SyntaxError: Unexpected end of JSON input
FROM
bash: line 1:   126 Trace/breakpoint trap   (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 index.js
❯ Starting backend ...
```

I am using the following Compose within a Portainer-Stack:
```
version: '3.8'
services:
  app:
    container_name: NginxProxyManager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '127.0.0.1:81:81' # Admin Web Port # I have tried exposing the port completely, but thats not the problem.
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    # Uncomment the next line if you uncomment anything in the section
    # environment:
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'

    volumes:
      - /Docker/nginx-proxy-manager/data:/data
      - /Docker/nginx-proxy-manager/letsencrypt:/etc/letsencrypt

networks:
  default:
    external: true
    name: Nginx-Proxy
```

I have no idea whats going on, especially because I haven't seen someone have this error before. Everything else works perfectly fine, just anything concerning SSL-Certs is not working. I've also tried previous versions, which result in the same error.

**Nginx Proxy Manager Version**

2.10.1 (and previous ones)
