### ISSUE TITLE
X-Forwarded-Host missing from default proxy.conf

### ISSUE THREAD

**Issue by thor0215** [NginxProxyManager/nginx-proxy-manager#2804]
The default proxy.conf file is missing the X-Forwarded-Host header
https://github.com/NginxProxyManager/nginx-proxy-manager/blob/67208e43cc41f659ae2e68baa58a181a4d5f465b/docker/rootfs/etc/nginx/conf.d/include/proxy.conf#L1-L7

add_header       X-Served-By $host;
proxy_set_header Host $host;
proxy_set_header X-Forwarded-Scheme $scheme;
proxy_set_header X-Forwarded-Proto  $scheme;
proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
proxy_set_header X-Real-IP          $remote_addr;
proxy_pass       $forward_scheme://$server:$port$request_uri;

This should be added to the above config:
proxy_set_header   X-Forwarded-Host   $http_host;

This breaks code-server currently when using the default NGinx Proxy Manager settings
https://github.com/coder/code-server

**Comment by 662** [comment]
X-Forwarded-Port

**Comment by medram** [comment]
Hello everyone, I run into the same issue, and I solved it like this:
```yml
npm:
    image: jc21/nginx-proxy-manager:2.12.1
    ports:
      - "80:80"
      - "443:443"
      - "8090:81"
    environment:
     ...
    volumes:
      - ${NFS_DOCKER_VOLUMES}/npm_volume/data:/data
      - ${NFS_DOCKER_VOLUMES}/npm_volume/letsencrypt:/etc/letsencrypt
      # Fixed by mounting it to this path.       
      - ./configs/server_proxy.conf:/data/nginx/custom/server_proxy.conf
```

My config file `./configs/server_proxy.conf`:

```txt
# Required to pass the real client IP address to the backend services 
real_ip_header CF-Connecting-IP;
```

Note: You can change `CF-Connecting-IP` with anything you want if needed.
