### ISSUE TITLE
Got an error reading communication packets

### ISSUE THREAD

**Issue by radaniba** [NginxProxyManager/nginx-proxy-manager#2838]
Hi everyone
I am using npm deployed through a  portainer stack. Everything worked fine until I had to upgrade my server for more resources.
On stack restarts, i lost connection to npm and it didn't want to start over. I rebuilt the stack hoping to still have access to my data. 
The stack went up, docker images started fine, but when I login to my admin I have the **"bad gateway"** error message in the login screen
I checked the logs for the db and I have these messages 

```
2023-04-18  3:44:48 5 [Warning] Aborted connection 5 to db: 'npm' user: 'npm' host: '172.21.0.3' (Got an error reading communication packets)
```

my docker compose is classic 

```
version: "3.3"
services:
  npm-app:
    image: 'jc21/nginx-proxy-manager:2.9.18'
    container_name: npm-app
    restart: unless-stopped
    ports:
      - '8081:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      DB_MYSQL_HOST: "npm-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      DB_MYSQL_NAME: "npm"
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      # Uncomment the line below if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./npm-data:/data:Z
      - ./letsencrypt:/etc/letsencrypt:Z
    depends_on:
      - npm-db
    networks:
      - npm-network
      - npm-internal

  npm-db:
    image: 'mariadb:latest'
    container_name: npm-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
    volumes:
      - ./npm-data/mysql:/var/lib/mysql:Z
    networks:
      - npm-internal

networks:
  npm-internal:
  npm-network:
    external: true
```

I am thinking maybe because of the restart, something went wrong with the db .

On the app side log I have some permission denied errors 

```
[4/18/2023] [3:52:35 AM] [Global   ] › ✖  error     create table `migrations` (`id` int unsigned not null auto_increment primary key, `name` varchar(255), `batch` int, `migration_time` timestamp) - ER_CANT_CREATE_TABLE: Can't create table `npm`.`migrations` (errno: 13 "Permission denied")
```

Any idea on how to save my admin session without losing data ?

Thanks
