### ISSUE TITLE
How to allow autherized IP only to use the application reverse proxied by nginx proxy manager?

### ISSUE THREAD

**Issue by huangwb8** [NginxProxyManager/nginx-proxy-manager#2857]
Supposed that I have a docker application using port `1234` in my VPS.  

In nginx proxy manager, I set up a reverse proxy `http://172.17.0.1:1234` and a domain `https://domain.com`. By the way, 172.17.0.1 is is the default gateway IP address for containers running on the Docker network.

However, if the IP of VPS was known, this application also could be visited via `http://vps-ip:1234`.  I don't want this happens. I hope `https://domain.com` is the only way to access the application.

I use Ubuntu and UFW.  Any suggestions?

**Comment by NghiaNguyen170192** [comment]
Firstly, you need to create your own `docker network create my-network`. Then in the `docker-compose` or `docker`, you need to state your `hostname` and `my-network` for your container. 
If you configure the `ports` but not the `network`, you accidentally expose your port to public internet.
As my example below, I do not expose `portainer`, just the `npm` container with ports '80,81,443'

```
version: '3'

services:
  npm:
    hostname: npm
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./nginx-proxy-manager/data:/data
      - ./nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      - my-network

  portainer:
    container_name: portainer
    hostname: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    # ports: 
    #   - 8000:8000
    #   - 9443:9443
    networks:
      - nginx-network
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data/data:/data

volumes:
  portainer_data:
    external: true

networks:
  my-network:
    external: yes    
```
Once you setup the docker, go to `Nginx Proxy Manager` and configure your `proxy host`. In the `forward Hostname/IP`, input the `hostname` and the internal container port. 

Check again with `netstat -tlnp` to see if any ports are expose accidentally again.
