### ISSUE TITLE
real ip

### ISSUE THREAD

**Issue by ManuProd** [NginxProxyManager/nginx-proxy-manager#2858]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ManuProd** [comment]
error sorry...

**Comment by medram** [comment]
Hello everyone, I run into the same issue, and I solved it like this:
```yml
npm:
    image: jc21/nginx-proxy-manager:2.12.1
    ports:
      - "80:80"
      - "443:443"
      - "8090:81"
    environment:
     ...
    volumes:
      - ${NFS_DOCKER_VOLUMES}/npm_volume/data:/data
      - ${NFS_DOCKER_VOLUMES}/npm_volume/letsencrypt:/etc/letsencrypt
      # Fixed by mounting it to this path.       
      - ./configs/server_proxy.conf:/data/nginx/custom/server_proxy.conf
```

My config file `./configs/server_proxy.conf`:

```txt
# Required to pass the real client IP address to the backend services 
real_ip_header CF-Connecting-IP;
```

Note: You can change `CF-Connecting-IP` with anything you want if needed.
