### ISSUE TITLE
NPM fails to start : s6-rc fatal error

### ISSUE THREAD

**Issue by Soupolait** [NginxProxyManager/nginx-proxy-manager#2889]
Hi there, since the first timeI installed NPM it never started well. After a reboot of my server the container does start but there’s still this weird error : 
`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service prepare: starting
s6-rc: fatal: timed out
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information. `
I have to go to portainer and recreate the container at each of my server reboot so it starts well.
Here’s the steps to reproduce : 
use this docker compose and just reboot your device where NPM is installed.
_version: '3.8'services:
  app:    
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'  
    volumes:      
         - /home/louise/docker/NGINX/data:/data
         -  /home/louise/docker/NGINX/letsencrypt:/etc/letsencrypt_ 
         
If anyone has any idea about how to fix s6-rc not working (I don’t even know what it is tbh), I take !

**Comment by apriliars3** [comment]
I have same issue

❯ Configuring npmuser ...
id: 'npmuser': no such user
s6-rc: fatal: timed out
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.

**Comment by ansred** [comment]
I have this instance running for many years, after rebooting the host. The host started.

Note: using this tag fixed the issue for me for now # 2.9.22

**Comment by Madame-Louise** [comment]
Since NPM works well when it's first created but not after a reboot I created a script that recreates the container at every startup. Here's the script if anyone's interested (it could definitely need improvements but it works).
[NPM.txt](https://github.com/NginxProxyManager/nginx-proxy-manager/files/11470497/NPM.txt)

**Comment by dlzdwxdt** [comment]
I also have this problem, docker deployment, please let me know if it is solved

❯ Setting ownership ...
s6-rc: fatal: timed out
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.

**Comment by yurividal** [comment]
same problem here. had to roll back to 2.9.22

**Comment by Dremor** [comment]
I'm not entirely sure, but it may be linked to a problem I'm experiencing on TrueNAS Scale, where NPM works on SSDs based pools, and not on HDDs pools. May be a clue to what the problem is coming from.

**Comment by doodlebro** [comment]
This has been an ongoing issue for months, even on 2.9.22 I have to occasionally restart the container manually.

Can we just roll back whatever change caused these constant permissions issues?

**Comment by jackyaz** [comment]
I had to pull jc21/nginx-proxy-manager:2.10.3 specifically, latest seemed to still pull 2.10.2 which still had the error reported here

**Comment by thisisnotfez** [comment]
```
export: fatal: unable to exec /etc/s6/init/init-stage1: No such file or directory
```

Throwing my name into the hat. I get this after rolling back to 2.9.20. Been running for years, and this just started the other day.

```
  nginxpm:
    image: jc21/nginx-proxy-manager:2.9.20
    container_name: nginx-proxy-manager
    #security_opt: #an attempt to fix, didn't work.
    #  - seccomp:unconfined
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 80:80
      - 81:81
      - 443:443
    labels:
      - docker.group=monitor
    volumes:
      - ${LOCALTIME}:${LOCALTIME}:ro
      - ${NGINX_CONF}:/config:rw
      - ${NGINX_CONF}/letsencrypt:/etc/letsencrypt
      - ${NGINX_CONF}/data:/data
      - ${NGINX_CONF}/etc:/etc
    healthcheck:
      test:
        - CMD
        - /bin/check-health
      interval: 10s
      timeout: 3s
    restart: always
```
