### ISSUE TITLE
Using different host/container ports for docker container disables all access to NPM

### ISSUE THREAD

**Issue by schambers** [NginxProxyManager/nginx-proxy-manager#2909]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
Upon using the following compose file, you are unable to access nginx proxy manager on port 81

Example docker compose file:

```
version: '3.8'
services:
    app:
    image: jc21/nginx-proxy-manager:2.9.22
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 80:8080
      - 81:8181
      - 443:4443
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
 ```

In addition, docker port mapping seem to be reversed, this was confirmed by logging into container via /bin/bash:
- curl http://localhost:81 > receive response of NPM landing page
- curl http://localhost:8181 > ERR_CONNECTION_REFUSED

Accessing either of these ports from outside the container yield ERR_CONNECTION_REFUSED responses

**Nginx Proxy Manager Version**
Confirmed with both 2.9.22 and 2.10.3

**To Reproduce**
1. Deploy above docker compose
2. Attempt to access on <ip>:81
3. Receive ERR_CONNECTION_REFUSED in Chrome

**Operating System**
Ubuntu docker host
