### ISSUE TITLE
Can 80 and 443 be changed?

### ISSUE THREAD

**Issue by yzhpxd** [NginxProxyManager/nginx-proxy-manager#2961]
Can 80 and 443 be changed? It should not only be changed in yaml, but also in other places. After the change, the control panel cannot be opened. Ask for advice

**Comment by EctoBoggan** [comment]
The control panel isn't on port 80 nor 443.
It's on port 81 and it cannot be change (I don't know why, can't find the answer).

But 80 and 443 can be easily change like this :

```
version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '6001:80'
      - '6002:443'
      - '81:81'
    volumes:
      - '/path/to/data:/data'
      - '/path/to/letsencrypt:/etc/letsencrypt'
```

Hope it helps.
