### ISSUE TITLE
stream proxy not stable/working

### ISSUE THREAD

**Issue by mr-m0nst3r** [NginxProxyManager/nginx-proxy-manager#2979]
Hey there,

I'm experiencing some strange problems.

I'm using this docker-compose file:
```
version: '3.8'
services:
  app:
    image: 'm0nst3r/nginx-proxy-manager:v1' # just a fork
    restart: unless-stopped
    network_mode: host
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      - "9000-9999:9000-9999" # these ports are not necessary because I'm using `network_mode: host`

    environment:
      DISABLE_IPV6: 'true'

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./snippets:/snippets:ro
      - ./pip.conf:/tmp/npmuserhome/.pip/pip.conf
```

Here's the ports listening on the machine:
```
ubuntu@nginx-proxy-manager:~$ netstat -pantu | grep LIST
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:9197            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:9164            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:9678            0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:81              0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:9889            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:9877            0.0.0.0:*               LISTEN      -
tcp6       0      0 :::3000                 :::*                    LISTEN      -
tcp6       0      0 :::22                   :::*                    LISTEN      -
```

those ports starts with 9 is the stream proxies.

verion info:
```
Version 2.10.2 (86ddd9c) 2023-03-30 23:54:10 UTC, OpenResty 1.21.4.1, debian 10 (buster), Certbot certbot 2.4.0
```

I can connect the stream proxy on the host, but can't use the stream from outside.

I'm saying `not stable`, because it may work, and may not work, I didn't change anything but fould it working after about 4 hours. Sometimes, it's working just now, but not working as soon as I add another.
```
kex_exchange_identification: read: Connection reset by peer
```
<img width="508" alt="image" src="https://github.com/NginxProxyManager/nginx-proxy-manager/assets/38524240/d8796357-dabb-4c44-b249-390726ad0587">

<img width="799" alt="image" src="https://github.com/NginxProxyManager/nginx-proxy-manager/assets/38524240/3a28488a-9eb5-44e3-b339-197a15cb60ff">

I can ping to that IP address:
```
ubuntu@nginx-proxy-manager:~$ ping 172.31.255.4
PING 172.31.255.4 (172.31.255.4) 56(84) bytes of data.
64 bytes from 172.31.255.4: icmp_seq=1 ttl=63 time=1.07 ms
64 bytes from 172.31.255.4: icmp_seq=2 ttl=63 time=0.697 ms
^C
--- 172.31.255.4 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 0.697/0.883/1.070/0.186 ms
```

The host of NPM is an instance on openstack. I got only 1 external ip address, so using NPM to proxy http/https/ssh/etc...
and also, http/https proxies are working great, without problems.

any clue where should I check?
