### ISSUE TITLE
Unable to start npm container...

### ISSUE THREAD

**Issue by BHuck74** [NginxProxyManager/nginx-proxy-manager#2991]
Dear all,

I've spent hours trying to get the following stack working but still encounter the following poor log file: 

**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - No
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
Stack init seems to get stuck...

**Nginx Proxy Manager Version**
Not able to get the stack accessible.

**To Reproduce**

Docker-compose file:

```
version: '3'
services:      
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    restart: always
    image: jc21/nginx-proxy-manager:latest
    ports:
      - "81:81"
      - "80:80"
      - "4000:443"
    volumes:
      - "/mnt/docker/npm/data:/data"
      - "/mnt/docker/npm/letsencrypt:/etc/letsencrypt"
    environment:
      - DB_MYSQL_HOST=nginx-proxy-manager-db
      - DB_MYSQL_PORT=3306
      - DB_MYSQL_USER=XXX
      - DB_MYSQL_PASSWORD=XXX
      - DB_MYSQL_NAME=npm

    networks:
      - proxy_network
      - npm_network
  
  nginx-proxy-manager-db:
    container_name: nginx-proxy-manager-db
    image: jc21/mariadb-aria:10.4.15-innodb
    restart: always
    environment:
      - MYSQL_DATABASE=npm
      - MYSQL_USER=npm
      - MYSQL_PASSWORD=mysqlpass
      - MYSQL_ROOT_PASSWORD=mysqlrootpass
    volumes:
      - "/mnt/docker/npm/mysql:/var/lib/mysql"
    networks:
      - npm_network
    
      
networks:
  npm_network:
    driver: bridge
  proxy_network:
    external: true 
```

** Portainer log file **

```
❯ Configuring npm user ...
❯ Configuring npm group ...
❯ Checking paths ...
❯ Setting ownership ...
```

**Operating System**
Debian 10
