### ISSUE TITLE
Custom configuration snippet file issue at /data/nginx/custom

### ISSUE THREAD

**Issue by ryhkml** [NginxProxyManager/nginx-proxy-manager#3004]
**Checklist**
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
Unable to specify a volume mount. It refers to the [Custom Nginx Configurations](https://nginxproxymanager.com/advanced-config/#custom-nginx-configurations)
```bash
Enabling IPV6 in hosts in: /data/nginx
- /data/nginx/proxy_host/1.conf
- /data/nginx/custom/http_top.conf
sed: cannot rename /data/nginx/custom/sedif27kI: Device or resource busy
s6-rc: warning: unable to start service prepare: command exited 4
```

**Nginx Proxy Manager Version**
v2.10.3

**Additional context**
Here is my docker compose
```yaml
version: "3.9"
services:
  proxy:
    container_name: reverse-proxy-server
    hostname: reverse-proxy-server
    restart: unless-stopped
    image: jc21/nginx-proxy-manager
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
      # Custom configuration snippet file goes here
      - ./http_top.conf:/data/nginx/custom/http_top.conf
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 256M
        reservations:
          cpus: "0.5"
          memory: 64M
    #environment:
      #- PUID=1000
      #- PGID=1000
volumes:
  data:
  letsencrypt:
networks:
  net:
```

**Comment by the1ts** [comment]
To me it looks odd that you are mounting a directory to /data inside the container (at first run this is perhaps empty) then trying to mount a file into /data/nginx/custom/ which doesn't exist. Wouldn't it be easier to make the directories in /data and put the file in there?

**Comment by ryhkml** [comment]
Solved after I tried changing the docker compose configuration

```yaml
version: "3.9"
services:
  proxy:
    container_name: reverse-proxy-server
    hostname: reverse-proxy-server
    restart: unless-stopped
    image: jc21/nginx-proxy-manager
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 256M
        reservations:
          cpus: "0.5"
          memory: 64M
    #environment:
      #- PUID=1000
      #- PGID=1000
networks:
  net:
```
