### ISSUE TITLE
Every time Docker Restarts I loose all settings

### ISSUE THREAD

**Issue by wilecoyte78** [NginxProxyManager/nginx-proxy-manager#3082]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
When docker restarts the image I have to reset admin password again and add all my port forwards

**Nginx Proxy Manager Version**
v2.10.3

**To Reproduce**
1. Start Docker container
2. Go To http://localhost:81/
3. Change email and password
4. Restart computer
5. Start Docker container and all has to re-done

**Expected behavior**
I shouldn't have to keep adding proxies and changing admin setting

**Operating System**
Window 11 WSL Ubuntu 22.04

**Comment by Fuechslein** [comment]
I don't know how proficient you are with docker but are you mouting the data folder to your host system? Because if not, the configs will not persist.

**Comment by Slater91** [comment]
Hello! I am not proficient with Docker (at all), so I have used the suggested basic docker-compose.yml file. Using that, restarting Docker means that I lose all my settings. What should I do differently to preserve my settings? Would a change to the suggested docker-compose.yml file be needed to achieve that? In that case, would it be possible to change the suggested file so that even users who are not proficient with Docker can maintain functionality?

Thank you!

**Comment by wilecoyte78** [comment]
Here is my docker-compose.yml file

```
version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '81:81'
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./mysql:/var/lib/mysql
```

**Comment by BobWs** [comment]
If you didn't mount the docker data folder to a host folder you will loose all your settings! Depending on the system you use you can mount a folder like this: (note: the example is based on Synology docker as I'm using that)
```
    volumes:
      - /volume1/docker/npm/config/config.json:/app/config/production.json
      - /volume1/docker/npm/data:/data
      - /volume1/docker/npm/letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
      - /etc/TZ:/etc/timezone:ro
```
Something like this!

**Comment by wilecoyte78** [comment]
I figured out the issue:

replace DRIVE with drive letter and USER with USERNAME

```
    volumes:
      - /mnt/(DRIVE)/Users/(USERS)/AppData/Local/Docker/wsl/data:/data
```

**Comment by tvaughan73** [comment]
On Windows I used this to get it to work

```
version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - proxy-manager:/data
      - proxy-manager:/etc/letsencrypt
volumes:
  proxy-manager:
    driver: local
```
