### ISSUE TITLE
Need Help with Nginx Proxy Manager Configuration

### ISSUE THREAD

**Issue by csweering** [NginxProxyManager/nginx-proxy-manager#3123]
Hello everyone,

I'm facing a bit of a challenge and could use your assistance. I've recently performed a clean installation of Debian 12 and have successfully set up Docker and Docker Compose. Everything seems to work smoothly with the local IP, but I'm encountering issues accessing it via my domain. Interestingly, it works perfectly when I use TOR to access the server. I've checked the firewall settings and ensured port forwarding is correctly configured. I've also obtained an SSL key.

Below is the script I'm using to install Nginx Proxy Manager (NPM):

```yaml
version: '3'

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "XXXXXX"
      DB_MYSQL_PASSWORD: "XXXXXXX"
      DB_MYSQL_NAME: "XXXXXXX"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'XXXXX'
      MYSQL_DATABASE: 'XXXXXX'
      MYSQL_USER: 'XXXXXXXX'
      MYSQL_PASSWORD: 'XXXXXXX'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
```

I've followed this script to install NPM. Despite my efforts, I'm unable to figure out why the domain access isn't working as expected. I've done some basic troubleshooting, but I'm stuck now. Your insights and guidance would be greatly appreciated.

Thank you all for your time and assistance!

Best regards,
Carlo
