### ISSUE TITLE
DNS challenge with DuckDNS does not work

### ISSUE THREAD

**Issue by Rihan9** [NginxProxyManager/nginx-proxy-manager#3138]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

This isseus is some sort of "reopening" of #2092. We can't request a SSL certificate for a domain hosted on DuckDNS.
In the log we found the following message:
`"The DNS response does not contain an answer to the question: mydomain.duckdns.org. IN TXT"`

**Nginx Proxy Manager Version**

v2.10.3

**To Reproduce**
1. create a hostname on duckDNS and make sure is pointed to the nginx proxy manager installation
2. on tab ssl certificates --> add ssl certificates --> let's encrypt --> compelte the form using dns challange: yes and the required token (see screenshot)
3. the error should pop-up

**Screenshots**

![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/33684020/785ec7cb-5c61-4178-b10a-96c91f0aa684)
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/33684020/e4a95ae7-e413-4827-82a2-1f107560b11d)
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/33684020/d0f0ce78-d883-4ae7-b788-ddd584ec5e12)

**Comment by holocronology** [comment]
I had the same issue earlier today when testing something with duckdns.org. Now, because the duckdns challenge failed, my entire NPM is borked.

![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/65265114/e3d67a50-4f31-4ebb-bb6d-fe1f0d167717)

**Comment by holocronology** [comment]
Did you delete a cert prior to this? I think there is an error in NPM that the database is not updating when certs are deleted. So NPM starting looking for the folder of the deleted cert, but it is not there. SO it ends up in an error loop looking for these deleted files.

**Comment by Rihan9** [comment]
I don't think so. The only think that come to my mind is the renew certifica process. Can it cause the deletion of the old certificate?

**Comment by devedse** [comment]
I'm running into exactly the same issue. I've tried to clean everything up an recreate the certificate but no matter what I tried I keep having this issue.

**Comment by devedse** [comment]
Ok I hacked the solution to work.

Download this file: https://gist.github.com/devedse/b63f79851c44aac27892c95009090325
And mount it in the docker container as a volume:

```
volumes:
      - /home/devedse/dockercomposers/nginxproxymanager/certificate.js:/app/internal/certificate.js:ro
```

My full compose file:
```
services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    volumes:
      - /home/devedse/dockercomposers/nginxproxymanager/data:/data
      - /home/devedse/dockercomposers/nginxproxymanager/letsencrypt:/etc/letsencrypt
      - /home/devedse/dockercomposers/nginxproxymanager/snippets:/config/nginx/snippets:ro
      - /home/devedse/dockercomposers/nginxproxymanager/certificate.js:/app/internal/certificate.js:ro
    network_mode: "host"
```
