### ISSUE TITLE
first login with 502 bad gateway,what should I do

### ISSUE THREAD

**Issue by HaSaKiYasuooo** [NginxProxyManager/nginx-proxy-manager#3328]
this is my docker-compose.yml file
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "(PASSWORD)"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '(PASSWORD)'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: '(PASSWORD)'
    volumes:
      #- ./data/mysql:/var/lib/mysql
      - ./mysql:/var/lib/mysql
------------------------------

when I login with admin@example.com and changeme,I revieve the 502 bad gateway,how can i resolve it?

**Comment by pvnkrockjesvs** [comment]
Same with my install I use for months. Tried a fresh install, same problem as op

**Comment by lastsamurai26** [comment]
how you are opening the Side ? 
http://ip:81 or https://ip:81 ? 

i cant reproduce the issue

**Comment by lastsamurai26** [comment]
I am using this on a Cloud VPS, my compose looks like this: 
```
version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    hostname: proxymanager
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
#      - '81:81' # Admin Web Port
      - '8000:8000'
      - '8001:8001'

    # Uncomment the next line if you uncomment anything in the section
    environment:
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: 'false'
    networks:
        proxy:
          ipv4_address: 172.18.1.253
    volumes:
      - /opt/containers/nginxproxy/data:/data
      - /opt/containers/nginxproxy/letsencrypt:/etc/letsencrypt
      - /opt/containers/nginxproxy/templates/_hsts.conf:/app/templates/_hsts.conf:ro
      - /etc/timezone:/etc/timezone:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
networks:
  proxy:
    external: true
```

after creating a domain for port 81, I deactivate port 81 again so that the NPM dashboard can only be reached via the domain. 

maybe the error is somewhere there
http://IPVPS:81
