### ISSUE TITLE
The 'Custom locations' dose not work as expected with Jellyfin

### ISSUE THREAD

**Issue by Vildnex** [NginxProxyManager/nginx-proxy-manager#3338]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
I set up the Nginx Proxy Manager with my local NAS using this Docker compose file:

```
version: '3.9'
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /path/to/nginx/manager/data:/data
      - /path/to/nginx/manager/encrypt:/etc/letsencrypt
    network_mode: host
```

After that, I set up the the jellyfin docker instance via this docker-compose file:

```
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      - JELLYFIN_PublishedServerUrl=192.168.0.5
    volumes:
      - /movies/jellyfin_config:/config
      - /movies/series:/data/tvshows
      - /movies/movies:/data/movies
    ports:
      - 8096:8096
    devices:
      - "/dev/dri:/dev/dri"
    restart: unless-stopped
```
My local instance of NAS is running on the IP 192.168.0.98 at port 8085 as I set it here:

![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/10352059/0b545973-5418-437c-b220-6a1aba20471c)

After that, I've also set my location for Jellyfin as is it here:

![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/10352059/4c313eb5-f37e-4c00-81b2-81457a2cdfb1)

I've also set up my SSL certificates.

After this whole setup si done I tried to call `https://my_domain:my_port` in order to access the main dashboard from my NAS, and everything worked as expected. 
But when I've tried `https://my_domain:my_port/jellyfin/` I will be redirected to a white blank page. 
More than that when I will try `https://my_domain:my_port/jellyfin` I will be redirected to `https://my_domain/jellyfin/` without `my_port` 

**Logs**

I've checked my logs from the docker container from nginx_manager and at the beginning, I get this error on my log:

```
2023/11/21 13:32:49 [warn] 369#369: could not build optimal proxy_headers_hash, you should increase either proxy_headers_hash_max_size: 512 or proxy_headers_hash_bucket_size: 64; ignoring proxy_headers_hash_bucket_size
2023/11/21 13:32:49 [warn] 371#371: could not build optimal proxy_headers_hash, you should increase either proxy_headers_hash_max_size: 512 or proxy_headers_hash_bucket_size: 64; ignoring proxy_headers_hash_bucket_size
```

**First try**

After further investigation, I've solved this issue because I've found this https://github.com/NginxProxyManager/nginx-proxy-manager/issues/292  old issue which resulted in me creating the following folder structure on my NAS:

 /path/to/nginx/manager/data/nginx/custom/http.conf
 
 This is the content of the `http.conf`:
 
```
proxy_headers_hash_max_size 1024;
proxy_headers_hash_bucket_size 128;

```

But this did not solve the issue yet, not even after a docker restarts with an actual NAS restart just to be sure.

**Logs 2**

After this, I've tried to check my logs from the docker container of nginx manager and I've got this:

![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/10352059/6b10578b-f780-4ee2-86cf-7568b2af871f)

**Nginx Proxy Manager Version**
Version 2.10.4 (fe93cb3) 2023-08-14 23:19:12 UTC

**Second try**

I've deleted that file manually and restarted the container again. It did recreate the same file again and I did get the same log again. But the problem was not solved.

**Final question**

I am not entirely sure if this is a bug or if I am missing something so please can anyone point me in the right direction? I am effectively lost.

**Operating System**
I am running all dose containers under a QNAP NAS
