### ISSUE TITLE
bad gateway for API since 2.11.0

### ISSUE THREAD

**Issue by pifou25** [NginxProxyManager/nginx-proxy-manager#3485]
Hello,

nginx proxy manager container is unhealthy, and admin panel is unavailable, with error message "bad gateway" for the API

since 2.11.0 (and 2.11.1). I get back to v2.10.4 and everything is running fine. Running on RPI3b+ so the ARM arch.

```
 $ curl http://192.168.1.25:81/api/
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

No error into the container logs except this warning at the beginning:

useradd warning: npm's uid 0 outside of the UID_MIN 1000 and UID_MAX 60000 range.

Here is my docker-compose, I dont think there is specific matter about anything except I use an external database:

```
services:

  nginx:
    image: jc21/nginx-proxy-manager:2.10.4
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81' # admin access
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "${MYSQL_NPM_USER}"
      DB_MYSQL_PASSWORD: "${MYSQL_NPM_PASSWORD}"
      DB_MYSQL_NAME: "${MYSQL_NPM_USER}"
    volumes:
      - ./data/nginx:/data
      - ./data/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 1m
      timeout: 3s
```
