### ISSUE TITLE
I can't figure out what's wrong in my config while getting the "bad gateway" error..

### ISSUE THREAD

**Issue by Lynkdev** [NginxProxyManager/nginx-proxy-manager#3550]
I can't figure out what's wrong in my config while getting the "bad gateway" error trying to login after setup. 

Logs show

2024/02/14 08:47:27 [error] 177#177: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.169.53, server: nginxproxymanager, request: "POST /api/tokens HTTP/1.1", upstream: "http://127.0.0.1:3000/tokens", host: "172.16.2.2:81", referrer: "http://172.16.2.2:81/login"

modified permission of mysql to 777 under /data and no change

```
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    networks:
      default:
        # static IP address for nginxproxymanager
        ipv4_address: 172.16.2.2
  db:
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      default:
        # static IP address for database
        ipv4_address: 172.16.2.3

networks:
  default:
    driver: bridge
    ipam:
     config:
       - subnet: 172.16.2.0/24
```

_Originally posted by @Lynkdev in https://github.com/NginxProxyManager/nginx-proxy-manager/issues/2774#issuecomment-1943345086_
