### ISSUE TITLE
SSL, HTTPS, Admin panel - HTTPS

### ISSUE THREAD

**Issue by Arkasha-P** [NginxProxyManager/nginx-proxy-manager#3649]
Всем привет я заметил что из коробки NPM не предоставляет возможность подключение по HTTPS. Хотя я использую этот продукт дома но всё ровно хотел бы обезопасить себя, как говорится "бережного бог бережет".

Так вот почитав достаточно Issue и наткнувшись на треды где ребята спрашивали как же использовать https для NPM. Хотел бы выложить своё решение на эту проблему. 

### Инструкция была написана для тех кто устанавливал NPM через пакетный менеджер типа `apt`

Я использую самоподписанные сертификаты так как я использую NPM исключительно в домашней сети и моя задача зашифровать трафик. Хотя эта процедура может сработать с любыми сертификатами. 

```bash
openssl genrsa -out nginx.ca.key.pem 2048
openssl req -new -x509 -nodes -days 365 -key nginx.ca.key.pem -out nginx.ca.cert.pem
```

теперь сертификат и ключ нужно положить в удобное для вас место я положил в папку `/etc/nginx/ssl`
_я знаю что не рекомендуется ложить ключ и сертификат в одну директорию, вы можете делать как душе захочется._

Затем нужно немного от редактировать файл `/etc/nginx/conf.d/production.conf`

в файле конфигурации пропишите свой порт от 1025-65534 

   ```
   server {
        listen 8001 ssl; # прописываем порт и слово ssl 
        listen [::]:8001 ssl; # прописываем порт и слово ssl 
        server_name nginxproxymanager 192.168.10.5; # здесь указываем dns и ip

        ssl_certificate /etc/nginx/ssl/nginx.ca.cert.pem; # указываем сертификаты и ключи
        ssl_certificate_key /etc/nginx/ssl/nginx.ca.key.pem;
        ...  # далее в штатном режиме
        }
```

перезагружаемся и пробуем зайти в моём случае адрес будет выглядеть следующим образом `https://192.168.10.5:8001`

### Я использую NPM в Docker и запускаю через Docker-Compose. А это говорит о том что я не поленюсь и напишу как всё тоже самое сделать в Docker-Compose. Поехали!

1. Создаём ключ и сертификат 

      ```bash
      openssl genrsa -out nginx.ca.key.pem 2048
      openssl req -new -x509 -nodes -days 365 -key nginx.ca.key.pem -out nginx.ca.cert.pem
      ```

2. далее помещаем файлы `nginx.ca.key.pem` и `nginx.ca.cert.pem` куда хотите у меня этот путь будет выглядеть следующим образом `/opt/nginx/cert/`

3. теперь нам нужно сделать так что бы мы могли редактировать файл конфигурации `production.conf` в основной ОС но при запуске docker-compose.yaml он отправлялся в контейнер. У меня этот файл будет лежать по пути `/opt/nginx/config`. _Здесь хотел бы добавить в этой папке у меня вообще весь конфиг лежит для удобной работы в будущем._ 

4. тут есть нюанс так как нам нужно в основной ОС расположить файлы конфигураций то тут есть два пути:
    - вытащить конфиг файлы из контейнера, файлы находятся по адресу `/etc/nginx/conf.d` что я и сделал через ssh просто из
    контейнера подключился к основной ОС и скинул файлы 
    - или можно скачать с github по адресу "https://github.com/NginxProxyManager/nginx-proxy-manager/tree/develop/docker/rootfs/etc/nginx/conf.d" что я узнал когда писал эту статью.
   
    подведём итоги на данный момент у нас должна быть следующая структура в основной ОС 
    
    ```
    /opt/nginx/cert
       nginx.ca.key.pem
       nginx.ca.cert.pem
    /opt/nginx/conf
       default.conf
       include
       production.conf
    ```

5.  нам нужно переместить в контейнер ключ, сертификат и конфиг. А также открыть порт который мы указали в `/etc/nginx/conf.d/production.conf` Вот как должен выглядеть `docker-compose.yaml`

        ```
        version: '3.8'
        services:
          app:
            image: 'jc21/nginx-proxy-manager:latest'
            restart: unless-stopped
            container_name: nginx
            ports:
              - '80:80'
              - '8001:8001' # наш кастомный порт который будет принимать https запросы
              - '443:443'
            volumes:
              - ./conf:/etc/nginx/conf.d # наш volume который будет передавать актуальный конфиг в контейнер 
              - ./cert:/etc/nginx/ssl # наш volume который будет передавать актуальные ключи и сертификаты в контейнер 
           ```

PS если Вы тоже как и я не любите читать статьи для решения Вашей проблемы а тупа копировать код\команды то мне Вас жать ;>
