### ISSUE TITLE
ER_HOST_NOT_PRIVILEGED Encountered Following docker-compose Tutorial

### ISSUE THREAD

**Issue by w41g87** [NginxProxyManager/nginx-proxy-manager#3656]
Using the `docker-compose.yml` file provided in the [tutorial](https://nginxproxymanager.com/setup/#using-mysql-mariadb-database) documentation yields `ER_HOST_NOT_PRIVILEGED` error in log

**Nginx Proxy Manager Version**
v2.11.1

**To Reproduce**
1. Go to [tutorial](https://nginxproxymanager.com/setup/#using-mysql-mariadb-database)
2. Copy the `docker-compose.yml` file and save it locally
3. Run `docker-compose up`
4. Run `docker-compose logs`

**Expected behavior**
The application connects to the database with no error.

**Screenshots**
<img width="851" alt="image" src="https://github.com/NginxProxyManager/nginx-proxy-manager/assets/31464973/61fec7e8-6e8b-47d5-9214-ee65d387ef4e">
<img width="846" alt="image" src="https://github.com/NginxProxyManager/nginx-proxy-manager/assets/31464973/165b46ae-11b9-4072-911f-a37ab360f065">

**Operating System**
Debian 12

**Additional context**
Also results in `Bad Gateway` error when attempting to login to the webUI.

**Comment by sias32** [comment]
Try using `docker compose up -d` instead of `docker-compose up -d`

**Comment by sias32** [comment]
And remove the `version: "3"` line in your docker-compose.yml or replace to `version: "3.8"`

**Comment by w41g87** [comment]
> Try using `docker compose up -d` instead of `docker-compose up -d`

> And remove the `version: "3"` line in your docker-compose.yml or replace to `version: "3.8"`

Making these two modifications results in the same output

**Comment by BiasedKiwi** [comment]
Same behavior on Ubuntu 22.04. Any solutions?

**Comment by vintalie** [comment]
I found this tutorial strange because it is citing the host in 'service: app:' but it is not defining a 'container_name:'db'', in 'service: db:', maybe this will work
```
  db:
    image: 'jc21/mariadb-aria:latest'
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - ./mysql:/var/lib/mysql
```
And where is the port to expose the database? I don't know how mariaDb works, but that's also strange
maybe adding `expose: - '3306` will help
