### ISSUE TITLE
No secured Web UI in the cluster

### ISSUE THREAD

**Issue by dniald** [NginxProxyManager/nginx-proxy-manager#3758]
Hi everyone,

I'm currently deploying an application on Amazon EKS and using Nginx Proxy Manager to manage my proxy configurations. However, I've encountered an issue where my application is not showing as secured (no HTTPS).

Here's my setup:

Amazon EKS cluster

Nginx Proxy Manager for handling proxy configuration

I've followed the standard setup procedures, but my application still doesn't show as secured when accessed via the browser.
Can anyone provide guidance on what might be causing this issue or what additional steps I might need to take to ensure my application is secured properly?

Do i need to use custom cert in the cluster? If that so, which path need to insert custom cert?
Or what did i miss?

Thanks in advance for your help!

Below are my manifest:

```
#! Client Ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-proxy-manager-ingress
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - np-nginx-manager-xxx.com
      secretName: xxxx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-proxy-manager-service
            port:
              number: 81
      # - path: /
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: nginx-proxy-manager-service
      #       port:
      #         number: 80

```
```
# Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy-manager-deployment
  labels:
    name: nginx-proxy-manager-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy-manager
  template:
    metadata:
      labels:
        app: nginx-proxy-manager
    spec:
      nodeSelector:
        Type: default
        SubnetType: xx
        RunApp: xx
        Env: xx
      containers:
        - name: nginx-proxy-manager-deployment
          image: jc21/nginx-proxy-manager:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 81
            # -  containerPort: 443
          volumeMounts:
            - name: letsencrypt
              mountPath: /etc/letsencrypt
            - name: data
              mountPath: /data
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 100Mi
      volumes:
        - name: letsencrypt
        - name: data

# Service
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-manager-service
  labels:
    name: nginx-proxy-manager-service
  namespace: dev
spec:
  ports:
  - name: web-ui
    port: 81
    targetPort: 81
    protocol: TCP
  - name: http-port
    port: 80
    targetPort: 80
    protocol: TCP
 # - name: https-port
 #  port: 443
 #  targetPort: 443
 #  protocol: TCP
  selector:
    app: nginx-proxy-manager
```

<img width="752" alt="image" src="https://github.com/NginxProxyManager/nginx-proxy-manager/assets/38592307/e91d84aa-5bce-46fa-b11b-b7dab84232c0">
