### ISSUE TITLE
Add environment variable to specify admin UI port

### ISSUE THREAD

**Issue by darko1979** [NginxProxyManager/nginx-proxy-manager#3808]
Currently Admin UI port is hardcoded to port 81. 
I know that you can expose it to another port but I was forced to attach my docker container to host network where port mapping does not work.
I also know that it could be changed by editing configuration after deployment but I don't like that solution (it means I have to do it every time I redeploy the stack).
The easiest solution would be if there was an environment variable that would define admin UI port, for example:

```
version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    network_mode: host
    environment:
      ADMIN_UI_PORT: 8080
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
```
If anybody asks why I had to attach to host network it's because it was they only way for my services to get the real client IP address. When nginx proxy manager is deployed in docker network X-Real-IP header always contains IP of docker network.
