### ISSUE TITLE
Docker not create rules for ports in iptables

### ISSUE THREAD

**Issue by Andymnm** [NginxProxyManager/nginx-proxy-manager#3930]
A project to run a single command `docker compose up -d`. After startup, the rules are applied for ports 80, 81, 443, but not for 8081. Because of this, I can reach the server from an external host on port 8081, but I cannot reach the local address.
```
# telnet localhost 8081
Trying ::1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.
```
```
# telnet 192.168.1.95 8081
Trying 192.168.1.95...
telnet: Unable to connect to remote host: Connection refused
```
```
# sudo firewall-cmd --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: enp1s0
  sources:
  services: dhcpv6-client http https ssh
  ports: 44510/tcp 8081/tcp
  protocols:
  forward: yes
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
```
```
netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN      87324/docker-proxy
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      686/sshd: /usr/sbin
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      87280/docker-proxy
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      87308/docker-proxy
tcp        0      0 0.0.0.0:44510           0.0.0.0:*               LISTEN      87293/docker-proxy
tcp6       0      0 :::8081                 :::*                    LISTEN      87335/docker-proxy
tcp6       0      0 :::22                   :::*                    LISTEN      686/sshd: /usr/sbin
tcp6       0      0 :::80                   :::*                    LISTEN      87286/docker-proxy
tcp6       0      0 :::443                  :::*                    LISTEN      87316/docker-proxy
tcp6       0      0 :::44510                :::*                    LISTEN      87299/docker-proxy
```
```
# docker -v
Docker version 27.1.1, build 6312585
```
docker-compose.yml
```
services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '8081:8081' 
      - '44510:81'

    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "mariadb"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "nginxproxy"
      DB_MYSQL_PASSWORD: "***"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - mariadb

  mariadb:
    container_name: MariaDB
    image: 'jc21/mariadb-aria:latest'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '***'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'nginxproxy'
      MYSQL_PASSWORD: '***'
    volumes:
      - ./mysql:/var/lib/mysql
```
```
# sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:webcache
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:tproxy

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
DOCKER-USER  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain DOCKER (3 references)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             172.18.0.3           tcp dpt:http
ACCEPT     tcp  --  anywhere             172.18.0.3           tcp dpt:81
ACCEPT     tcp  --  anywhere             172.18.0.3           tcp dpt:https
ACCEPT     tcp  --  anywhere             172.18.0.3           tcp dpt:tproxy

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-ISOLATION-STAGE-2 (2 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere
DROP       all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-USER (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere
```
