### ISSUE TITLE
WTF :login 502

### ISSUE THREAD

**Issue by peterwillcn** [NginxProxyManager/nginx-proxy-manager#3965]
WTF : login 502

```
  ngx:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /data/nginx:/data
      - /data/nginx/letsencrypt:/etc/letsencrypt
   ```

![image](https://github.com/user-attachments/assets/1865f6e2-0265-4e3d-a9e8-4aa1a1043c8e)
