### ISSUE TITLE
Show (access) log in web interface

### ISSUE THREAD

**Issue by xanthos84** [NginxProxyManager/nginx-proxy-manager#401]
Easy FR here:

Like Audit Log some kind of Log View for the Reverse Proxy Hosts.

That would be awesome!
Thanks

**Comment by Belafestim** [comment]
you mean like a log of connections and/or visits?
I would like to second that idea!

**Comment by xanthos84** [comment]
yes absolutely!

**Comment by nightcomdev** [comment]
I was asking about the same thing, simple stats. I vote for it!

**Comment by damianog** [comment]
A view for /data/logs/error.log will be very helpfull too.

**Comment by M0E-lnx** [comment]
+1
I'm also looking for this feature.

I need a solution to browse the access logs for each configured host.  I know there are other solutions to this like goaccess for example, but I can't get that to work.  Looks like the log syntax is different than what goaccess is expecting and I can't figure out a way to configure the logging format on nginx-proxy-manager.

**Comment by leon1995** [comment]
Are there any new information to this? It would be really nice to have this feature

**Comment by RiversideRocks** [comment]
Any updates? SSHing into the docker container isn't convenient.

**Comment by kamilkosek** [comment]
Hi all, 
maybe it´s helpful for one or another. I just use [frontail ](https://github.com/mthenw/frontail) in a container for it.
Here´s my dead simple compose file:

```
version: '3'
services:
  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /disks/nginx-proxy-manager/data:/data
      - /disks/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
  frontail:
    image: mthenw/frontail:latest
    restart: always
    ports:
      - "9001:9001"
    volumes:
      - /disks/nginx-proxy-manager/data/logs:/log/npm
    command: '--ui-highlight /log/npm/default-host_access.log /log/npm/default-host_error.log /log/npm/fallback_access.log /log/npm/fallback_error.log /log/npm/letsencrypt-requests_access.log /log/npm/letsencrypt-requests_error.log /log/npm/proxy-host-1_access.log /log/npm/proxy-host-1_error.log /log/npm/proxy-host-2_access.log /log/npm/proxy-host-2_error.log /log/npm/proxy-host-3_access.log /log/npm/proxy-host-3_error.log /log/npm/proxy-host-4_access.log /log/npm/proxy-host-4_error.log /log/npm/proxy-host-5_access.log /log/npm/proxy-host-5_error.log /log/npm/proxy-host-6_access.log /log/npm/proxy-host-6_error.log /log/npm/proxy-host-7_access.log /log/npm/proxy-host-7_error.log /log/npm/proxy-host-8_access.log /log/npm/proxy-host-8_error.log /log/npm/proxy-host-9_access.log /log/npm/proxy-host-9_error.log'
```
