### ISSUE TITLE
Some services works, other get SSL error. Loading good services allows bad services to load. 

### ISSUE THREAD

**Issue by AryehGielchinsky** [NginxProxyManager/nginx-proxy-manager#4046]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

 I've got NPM setup with Docker Compose. I have it pointing to other docker containers on the same host with a shared docker network. For a long time everything worked fine, but recently I've been getting SSL errors for Nextcloud and Immich, while Jellyfin and Gitea work fine. Nextcloud and Immich get SSL_ERROR_UNRECOGNIZED_NAME_ALERT

The weird thing is if I load Jellyfin or Gitea and then Nextcloud or Immich, Nextcloud or Immich will work for for a bit. I checked wireshark, and it looks like Nextcloud and Immich try and fail with TLS 1.2, while Gitea and Jellyfin use TLS 1.3 and succeed. 

Here is my compose: 
```
services:
  app:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    networks:
      - net
    environment:
      - TZ=Asia/Jerusalem
    volumes:
      - /dockers/nginxpm/data:/data
      - /dockers/nginxpm/letsencrypt:/etc/letsencrypt
networks:
  net:
    external: true
```

Everything is on the same domain. I use sub domains to distinguish between services.

Nextcloud Nginx custom config 
```
client_body_buffer_size 512k;
proxy_read_timeout 86400s;
client_max_body_size 0;
```
 Immich Nginx custom config 
`client_max_body_size 50000M;`

 Jellyfin and Gitea don't have Nginx custom Configs. 

**Nginx Proxy Manager Version**

v2.11.3

**To Reproduce**
1. Install NPM with Docker
2. Add some services
3. Use browser to access services
4. Some services give SSL_ERROR_UNRECOGNIZED_NAME_ALERT error.

**Expected behavior**

No SSL error.

**Screenshots**

**Operating System**

Server: Ubuntu Server 22.04
Desktop: Ubuntu Desktop 22.04

**Additional context**

Docker version 27.3.1, build ce12230
Firefox 131.0.2 (64-bit) (deb version)
