### ISSUE TITLE
v3: s6-rc failed to properly bring all the services up!

### ISSUE THREAD

**Issue by dasunsrule32** [NginxProxyManager/nginx-proxy-manager#4057]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:v3` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
Attempting to start v3 with a data path specified, it fails with the following:
```
npm-v3  | ❯ Configuring npm user ...
npm-v3  | ❯ Configuring npm group ...
npm-v3  | ❯ Checking paths ...
npm-v3  | ❯ Setting ownership ...
npm-v3  | ❯ Dynamic resolvers ...
npm-v3  | s6-rc: warning: unable to start service prepare: command exited 127
npm-v3  | /run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
```

**Nginx Proxy Manager Version**
3.0.0a

**To Reproduce**
1. Configure `compose.yml`
```
services:
  npm-v3:
    image: docker.io/jc21/nginx-proxy-manager:v3
    container_name: npm-v3
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ${DATA_PATH}:/data
    deploy:
      resources:
        limits:
          memory: 1G
    env_file:
      - .env
```
`.env` file
```
PUID=1000
PGID=1000
NPM_DISABLE_IPV6=true
DATA_PATH=/mnt/data/npm-v3
```
2. docker compose up -d
3. See error

**Expected behavior**
NPM starts and UI is accessible and ready for configuration.

**Operating System**
TrueNAS SCALE 24.0.4.2 using `jlmkr` and `jails`, not TrueNAS Apps. Basically, it's regular `docker`.

**Additional context**
It starts fine when I don't mount the volume, I've set it to root as well to see if that resolves the issue and it does not.
