### ISSUE TITLE
Can't change steam anymore 

### ISSUE THREAD

**Issue by lastsamurai26** [NginxProxyManager/nginx-proxy-manager#4101]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes 
- Are you sure you're not using someone else's docker image?
  - Yes 
- Have you searched for similar issues (both open and closed)?
  - Yes
  - 
**Describe the bug**
i want to change a stream after saving i get this meesage 
"data must NOT have additional properties, data must NOT have additional properties, data must NOT have additional properties, data must NOT have additional properties, data must NOT have additional properties"

**Nginx Proxy Manager Version**
v2.12.1 © 2024 [jc21.com](https://jc21.com/?utm_source=nginx-proxy-manager). Theme by [Tabler](https://tabler.github.io/?utm_source=nginx-proxy-manager)

**To Reproduce**
1. Go to 'steams
2. Click on 'on of your streams'
3. Save it 

Wiorkaround -> Downgrade to version 2.11.3

**Comment by techteam-pro-discount** [comment]
Do you use docker volumes or docker mounting system paths?

**Comment by lastsamurai26** [comment]
i have tested both and both do not work in the new version

**Comment by XFox111** [comment]
I have the same issue. Editing existing streams causes the error. Here's my docker compose (I'm forwarding the 8022 port, the `nginx-net` network is a `bridge`, and used for attaching other containers):

```yml
networks:
  nginx-net:
    external: true

volumes:
  nginx-proxy_data:
  nginx-proxy_letsencrypt:

services:
  nginx-proxy:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    networks:
      - nginx-net
    ports:
      - 80:80
      - 443:443
#      - 81:81      # Use this if something goes wrong
      - 8022:8022
    volumes:
      - nginx-proxy_data:/data
      - nginx-proxy_letsencrypt:/etc/letsencrypt
    environment:
      DISABLE_IPV6: 'true'
    healthcheck:
      ...
```

There's nothing in docker logs. Rolling back to `2.11.3` resolves the issue
