### ISSUE TITLE
Proxy Host Location with 2 Apache containers

### ISSUE THREAD

**Issue by Kydaix** [NginxProxyManager/nginx-proxy-manager#4142]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
I have the impression that there's a problem with the rental system. I'm just trying to set up 2 Apache containers with Nginx Proxy Manager.

In my case, I'm working in localhost. I can set up a proxy host which is the first Apache container. I then create a “/test” location on it, which redirects to the second container. The setting in the proxy host still works. However, the location doesn't. I can invert the 2 and the roles are reversed! I hope I'm right in reporting this as a bug.

**Nginx Proxy Manager Version**
2.12.1

**To Reproduce**
1. Create a docker-compose.yml with "jc21/nginx-proxy-manager:latest" and two "httpd:latest" with different container names.
2. Link them all through a network.
3. Start the Docker stack and connect to Nginx Proxy Manager.
4. Add a proxy host with the domain name “localhost”, the ip with the name of the first Apache container (“site-1” in my case) on port 80.
5. On the same proxy host, add a “/test” location that redirects to the second Apache container ("site-2" in my case) on port 80.
6. Go to “localhost”, which works, then to "localhost/test" which does not.

**Expected behavior**
When I go to the "/test" location, I should be redirected to my second Apache container.

**Screenshots**
![image](https://github.com/user-attachments/assets/f235bec5-9cfa-49de-a863-1ba0c4b71302)
![image](https://github.com/user-attachments/assets/ef50a105-8ad3-4602-9edb-3ef80feb4580)
![image](https://github.com/user-attachments/assets/13607714-0894-4e71-b0f0-62fb7ab45b3a)
![image](https://github.com/user-attachments/assets/07792eac-f038-4cf0-9ea1-6c578d3d7c68)

**Operating System**
Windows 10 (22H2 - 19045.5073)

**Additional context**
```
services:

  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - web

  site-1:
    image: httpd:latest
    container_name: site-1
    restart: always
    volumes:
      - ./site-1:/usr/local/apache2/htdocs
    networks:
      - web

  site-2:
    image: httpd:latest
    container_name: site-2
    restart: always
    volumes:
      - ./site-2:/usr/local/apache2/htdocs
    networks:
      - web

networks:
  web:
```
