### ISSUE TITLE
Cannot login after initial setup

### ISSUE THREAD

**Issue by ChrisB85** [NginxProxyManager/nginx-proxy-manager#4175]
Hi,

I'm running docker in rootless mode. After initial deployment of NPM I cannot login to web UI. In browser network tab I see that /api request status is: (failed)net::ERR_CONNECTION_RESET - response content is empty.
No message in the docker compose logs. UID and GID of the user which runs the container is 1000. The same thing happens when I remove PUID and PGID envs (I removed both volumes dirs to avoid permissions issues).

My docker-compos.yml file:
```
services:
  app:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '1080:80'
      - '1081:81'
      - '1443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    environment:
      PUID: 1000
      PGID: 1000
```
