### ISSUE TITLE
The connection was reset

### ISSUE THREAD

**Issue by Nightwalker83** [NginxProxyManager/nginx-proxy-manager#4197]
Hi,

The following docker compose file to setup NPM

```
version: '3.9'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - /var/lib/docker/volumes/vaultwarden:/data
        
    ports:
      - "8081:80"
      - "3012:3012"
    environment:
      ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}

  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81'   # Admin Web Port
    volumes:
      - /var/lib/docker/volumes/vaultwarden/nginx/data:/data
      - /var/lib/docker/volumes/vaultwarden/letsencrypt:/etc/letsencrypt

  backup:
    image: ttionya/vaultwarden-backup:latest
    restart: always
    volumes:
      - /var/lib/docker/volumes/vaultwarden:/bitwarden/data/
      - /var/lib/docker/volumes/vaultwarden/vaultwarden-rclone-data:/config/
      - /var/lib/docker/volumes/vaultwarden/vaultwarden-backup/:/.env

volumes:
  vaultwarden-data:
    # Specify the name of the volume where you save the vaultwarden data,
    name: vaultwarden-data
  vaultwarden-rclone-data:
    external: true
    # Specify the name of the volume where you save the rclone configuration,
    name: vaultwarden-rclone-data
```

However, it now does not want to connect to the admin web portal

Every time I have tried recently it gives me the error in the web browser

The connection was reset

The connection to the server was reset while the page was loading.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that browser* is permitted to access the web.

*  I have tried multiple browsers but still receive the error! Not sure why it initially worked and is not working now? However Portainer, is reporting that the NPM container is running. 

Thanks,

Aaron

**Comment by Nightwalker83** [comment]
I managed to solve the problem by adding the db section to the code.

```
version: '3.9'
services:
  vaultwarden:
    image: 'vaultwarden/server:latest'
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - '/var/lib/docker/volumes/vaultwarden:/data'
    ports:
      - '8081:80'
      - '3012:3012'
    environment:
      ADMIN_TOKEN: '${VAULTWARDEN_ADMIN_TOKEN}'
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      DB_MYSQL_HOST: db
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: npm
      DB_MYSQL_PASSWORD: npm
      DB_MYSQL_NAME: npm
    volumes:
      - '/var/lib/docker/volumes/vaultwarden:/data'
      - '/var/lib/docker/volumes/vaultwarden/letsencrypt:/etc/letsencrypt'
    depends_on:
      - db
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: npm
      MYSQL_DATABASE: npm
      MYSQL_USER: npm
      MYSQL_PASSWORD: npm
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - '/var/lib/docker/volumes/vaultwarden/vaultwarden/mysql:/var/lib/mysql'
  backup:
    image: 'ttionya/vaultwarden-backup:latest'
    restart: always
    volumes:
      - '/var/lib/docker/volumes/vaultwarden:/bitwarden/data/'
      - '/var/lib/docker/volumes/vaultwarden/vaultwarden-rclone-data:/config/'
      - '/var/lib/docker/volumes/vaultwarden/vaultwarden-backup/:/.env'
volumes:
  vaultwarden-data:
    name: vaultwarden-data
  vaultwarden-rclone-data:
    external: true
    name: vaultwarden-rclone-data
```
