### ISSUE TITLE
Streams do not work on Raspberry Pi

### ISSUE THREAD

**Issue by Jacksaur** [NginxProxyManager/nginx-proxy-manager#4271]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
Running on a Raspberry Pi, the Streams feature appears to be completely nonfunctional. I can interact with the Streams UI and add streams fine, but they do not have any effect, and trying to connect to something at a proxied port fails every time, even to the Pi's own ports. I've tried on a Pi 4B running 64 Bit Debian, and a Pi 3B running 64 Bit DietPi, both exhibit the same issue. Testing on a Proxmox LXC running Debian with identical settings and docker compose file, works fine. So my configuration is fine, it's just the Pis. There are no mentions of an error in NPM's logs, and no log file for the stream entirely in the log folder.
Perhaps an ARM issue?

**Nginx Proxy Manager Version**
v2.12.1

**To Reproduce**
1. Install NPM onto a Raspberry Pi via Docker.
2. Enter the streams section, and add a stream between two ports.
3. Trying to access the proxied port will always time out. 

**Expected behavior**
Stream would successfully redirect traffic to port to specified IP and port.

**Screenshots**
![](https://iili.io/2vASmHg.png)
```
services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    environment:
      X_FRAME_OPTIONS: "sameorigin"
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    network_mode: host
    restart: unless-stopped
```

**Operating System**
RPi Debian, RPi DietPi.
