### ISSUE TITLE
PostgreSQL Error & Bad Gateway

### ISSUE THREAD

**Issue by Stualyttle** [NginxProxyManager/nginx-proxy-manager#4298]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
When enabling PostgreSQL, the dashboard throws a Bad Gateway-error and the logs print the following:

```txt
[1/14/2025] [8:47:38 PM] [Global   ] › ✖  error     no pg_hba.conf entry for host "xx.xx.xx.xx", user "nginx_proxy_manager", database "nginx_proxy_manager", no encryption error: no pg_hba.conf entry for host "xx.xx.xx.xx", user "nginx_proxy_manager", database "nginx_proxy_manager", no encryption
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:283:98)
    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:122:29)
    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:35:38)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:191:23) {
  length: 183,
  severity: 'FATAL',
  code: '28000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '535',
  routine: 'ClientAuthentication'
}
```

**Nginx Proxy Manager Version**
v2.12.2

**To Reproduce**
1. Go to log in screen
2. Login
4. See error.

**Expected behavior**
Connect to database and login to dashboard

**Screenshots**
![image](https://github.com/user-attachments/assets/f606f1b5-af51-4e08-910b-4411e69e6932)
![image](https://github.com/user-attachments/assets/6713b511-5496-46f1-b28e-507b9b69a803)
PS. Stock compose file, also tried with the advanced vars in the compose file, but same issue.
![image](https://github.com/user-attachments/assets/f77906c5-fa79-4755-b637-e9e88623b9ce)

**Operating System**
Debian 12

**Additional context**
My database is a managed one from Digital Ocean, I think the issue comes from the certificate.
This is how I normally connect to the database: 
`postgresql://project_name:password@xx.xx.com:25060/project_name?connection_limit=5&pool_timeout=360&connect_timeout=360`

**Comment by YTKme** [comment]
I just want to add to this issue as well as I encountered the same error with MariaDB hosted on another server myself.

It seem like the application is not accepting an already available database host? I tried specifying `DB_MYSQL_HOST` as IP and FQDN, but the log shows it is trying to access the database on `npmhost` (local machine docker is running on).

Error:

```
[1/15/2025] [7:51:48 AM] [Global   ] › ✖  error     Access denied for user 'npm'@'npmhost' (using password: YES) Error: Access denied for user 'npm'@'npmhost' (using password: YES)
```

Compose:

```yaml
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # Port Format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Administrator Web Port
    environment:
      # MySQL/MariaDB Connection:
      DB_MYSQL_HOST: "10.1.1.21"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "IHopeThisIsNotYourPassword"
      DB_MYSQL_NAME: "npm"
      # Disable IPv6
      # DISABLE_IPV6: 'true'
    volumes:
      # Volume Format <source-volume>:<target-volume>
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
```
