### ISSUE TITLE
Make A Dark Mode Theme

### ISSUE THREAD

**Issue by ghost** [NginxProxyManager/nginx-proxy-manager#4314]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by anthonyrom** [comment]
Duplicate of #707 (and #2859 which should also be closed, but I don't want to comment there since it would un-stale the issue)

**Comment by lastsamurai26** [comment]
i using Theme.Park (: 
this is what i use 
```
services:
  theme-park:
    image: ghcr.io/themepark-dev/theme.park
    container_name: theme-park
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - TP_URLBASE=themes #optional
    volumes:
      - /opt/containers/themepark:/config #optional
    restart: unless-stopped
    networks:
        proxy:
networks:
  proxy:
   external: true
```
Add this to your NPM docker compose file  to the env'S
      TP_THEME: dark
      TP_DOMAIN: npmdomain.de\/themes
this to the volumes
      - /opt/containers/nginxproxy/themes/98-themepark:/etc/cont-init.d/98-themepark


download this file 
https://raw.githubusercontent.com/themepark-dev/theme.park/refs/heads/master/docker-mods/nginx-proxy-manager/root/etc/cont-init.d/98-themepark
put it into the folder Above

start booth Containers 

add this to your npm domain as custom location 

![Image](https://github.com/user-attachments/assets/1b94486a-f7f1-4e3b-8368-0466e10191f9)
