### ISSUE TITLE
Problem with Real IP forward

### ISSUE THREAD

**Issue by Shinox2k** [NginxProxyManager/nginx-proxy-manager#4486]
Dear Community,

I have recently started a new app project and encountered some challenges along the way. Here is the situation:

Infrastructure Overview:

`User <-> CloudFlare DNS  <-> Router <-> Proxmox VM <-> Ubuntu <-> (Nginx Proxy Manager <-> My Docker APP)`

I want to log the user's IP address along with the forwarded IP in the header. However, after passing through NPM (Nginx Proxy Manager), I lose the forwarded IP address.

Example:
Curl Request from Outside:

NPM:

`[16/Apr/2025:21:31:09 +0000] - 200 200 - GET https xyz.abc.com "/docs" [Client 80.100.100.90] [Length 496] [Gzip 1.92] [Sent-to 10.0.0.3] "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36" "-"`

MyApp(Uvicorn/FastApi):

`INFO:     172.20.0.2:46020 - "GET /docs HTTP/1.1" 200 OK`

As you can see, the actual client IP (80.100.100.90) is missing and is replaced by the IP of the internal service (172.20.0.2), which is crucial for my use case.

My config:

Python uvicorn main.py (only important part)

`if __name__ == "__main__":
    uvicorn.run(
        app,
        host="0.0.0.0",
        port=1337,
        proxy_headers=True,
        forwarded_allow_ips="*",
    )`

Docker compose: 

```
  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - "81:81"
      - "80:80"
      - "443:443"
    volumes:
      - /mnt/drive/nginxproxymanager/data:/data
      - /mnt/drive/nginxproxymanager/letsencrypt:/etc/letsencrypt
```
My app:
```
  xyz:
    image: xyz/xyz:xyz
    restart: unless-stopped
    network_mode: host
```

Tried everything (maybe unsuccesfull cause there were many potential fixes - https://github.com/NginxProxyManager/nginx-proxy-manager/issues/3267)

If there is anything more that its necessary to be known about my configuration im here to provide it
