### ISSUE TITLE
NPM using 80-90% CPU as soon as it starts

### ISSUE THREAD

**Issue by javito1081** [NginxProxyManager/nginx-proxy-manager#4520]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
it started a few days ago, npm is consuming 80-90% of my cpu in 2 process, heres a pic of my htop

https://drive.google.com/file/d/12-ZBtBSNjaHAeP_KC6kEVSnZtHchsYlo/view?usp=sharing

its driving me cracy, i cant make it to be normal again, never seen this b4, logs r useless, theres nothing there, its all like its acting normal

sometimes the name of the command change to nginx worker process is shutting down, but the process id remains the same, if i shutdown npm, my server goes back to normal but that doesnt work all the time, i have it on ubuntu server as a docker with other 12 docker containers, its been runing fine, but the issue started all of a sudden 3 days ago

If i do docker compose -f npm/npm.yml down && docker compose -f npm/npm.yml up -d to restart the container, everything goes back to normal but like i said it doesnt always work, until it starts all over again, sometimes it takes a bit, sometimes it takes longer, but eventually it starts to take 80-90% of my cpu again.

**Nginx Proxy Manager Version**
v2.12.3

**To Reproduce**
As soon as i start the container, my cpu goes to 80-90% usage by NPM

**Expected behavior**
Work as intended with no trafic

**Screenshots**

![Image](https://github.com/user-attachments/assets/22214841-faa7-4034-8cea-976ffa8fc23d)

**Operating System**
Ubuntu Server 24.04

**Additional context**
im using docker compose, heres my file 

```
services:
  npm:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    #image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    container_name: nginx-proxy-manager
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    # Uncomment the next line if you uncomment anything in the section
    environment:
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: 'true'

    volumes:
      - ./npm-data:/data
      - ./npm-letsencrypt:/etc/letsencrypt
```
