### ISSUE TITLE
NPM 2.12.3 does not work with Guacamole 1.5.5

### ISSUE THREAD

**Issue by MnM001** [NginxProxyManager/nginx-proxy-manager#4586]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes 
- Are you sure you're not using someone else's docker image?
  - Yes 
- Have you searched for similar issues (both open and closed)?
  - Yes 

**Describe the bug**
I have added my guacamole docker to NPM version 2.12.3.  (both guacamole and npm live on the same host so I have tried both container name and IP address).

My docker compose section for npm is:

````
    npm:
        image: jc21/nginx-proxy-manager:latest
        container_name: npm
        hostname: npm
        volumes:
            - /docker/containers/npm/config/data:/data
            - /docker/containers/npm/config/letsencrypt:/etc/letsencrypt
        environment:
            - DISABLE_IPV6=true
        networks:
            - nginx
        ports:
            - 80:80
            - 443:443
            - 81:81
        healthcheck:
          test: ["CMD", "/bin/check-health"]
          interval: 30s
          timeout: 3s
        restart: unless-stopped
````

I did not enable any options under details, custom tabs for the guacamole host:

![Image](https://github.com/user-attachments/assets/bf9e387e-5ca0-4a6c-914d-c619a5793abc)

![Image](https://github.com/user-attachments/assets/46ad6924-b7fb-45be-a0e7-5f7149ec99bd)

Under advanced I have 

````
location / {
    proxy_pass http://guacamole:8080;
    proxy_buffering off;
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    access_log off;
}
````
It doesn't with or without the above in the advanced or with WebSockets enabled.

When I go to my URL I get this error:

![Image](https://github.com/user-attachments/assets/53c71f2c-ceb5-4023-87de-1c55a73fea46)

I shut down npm and start swag which has this configuration for guacamole:

````
server {
    listen 443 ssl;

    server_name XXXXXX.*;

    include /config/nginx/ssl.conf;
    include /config/nginx/errors.conf;
    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app guacamole;
        set $upstream_port 8080;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
        proxy_buffering off;
    }
}
````
and it runs just fine. I have tried the above location under npm's advanced but it still didn't work.

Looks like an npm issue. Hopefully can be solved.

**Nginx Proxy Manager Version**
2.12.3
