### ISSUE TITLE
Error: Command failed: /usr/bin/certbot renew

### ISSUE THREAD

**Issue by b0red** [NginxProxyManager/nginx-proxy-manager#563]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
YES
- Are you sure you're not using someone else's docker image?
YES
- If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network?
YES

**Describe the bug**
- A clear and concise description of what the bug is.
When I try to 
- What version of Nginx Proxy Manager is reported on the login page?

**To Reproduce**
1. Open the webpage for the app (http://localhost:85)
2. click on some of the tabs (/nginx/access, /users, /audit-log or /settings)
3. Error is that none of those pages will show up.

**Expected behavior**
When clicking on any of the above mentioned links, nothing happens. I've restarted the app several times, but I still get the same or similar error. THose pages won't load

**Operating System**
- latest version os Ubuntu: VERSION="20.04.1 LTS (Focal Fossa)"
- docker: Docker version 19.03.6, build 369ce74a3c & docker-compose version 1.25.0, build unknown

**Additional context**
docker-compose.yml
`
```
nginxproxymanager:
  image: "jc21/nginx-proxy-manager:latest"
  container_name: nginxproxymanager
  hostname: nginxproxymanager
  restart: always
  depends_on:
    - db
  environment:
    DISABLE_IPV6: 'true' 
    #- MYSQL_ROOT_PASSWORD=${M_ROOT_PASS}
    #- MYSQL_DATABASE_NPM=${MYSQL_DATABASE_NPM}
    #- MYSQL_USER=${M_ROOT_USER}
    #- MYSQL_PASSWORD=${M_ROOT_PASS}
  ports:
    # Public HTTP Port    
    - "80:80"
    # Public HTTPS Port
    - "446:443"  
    # Public Admin Port
    - "85:81"
  volumes:
   - ${USERDIR}/docker/nginxproxymanager/config/config.json:/app/config/production.json
   - ${USERDIR}/docker/nginxproxymanager/data:/data
   - ${USERDIR}/docker/letsencrypt:/etc/letsencrypt  

db:
  image: "jc21/mariadb-aria:10.4"
  restart: always 
  environment:
    MYSQL_ROOT_PASSWORD: "npm" 
    MYSQL_DATABASE: "npm" 
    MYSQL_USER: "npm"
    MYSQL_PASSWORD: "npm"   
  volumes: 
    - ${USERDIR}/docker/nginxproxymanager/mysql:/var/lib/mysql
```
`
**Logs from Portainer:**
Traceback (most recent call last):,
  File "/usr/lib/python3.8/site-packages/certbot/_internal/renewal.py", line 63, in _reconstitute,
    renewal_candidate = storage.RenewableCert(full_path, config),
  File "/usr/lib/python3.8/site-packages/certbot/_internal/storage.py", line 445, in __init__,
    raise errors.CertStorageError(,
certbot.errors.CertStorageError: renewal config file {} is missing a required file reference,
Renewal configuration file /etc/letsencrypt/renewal/npm-8.conf is broken. Skipping.,
0 renew failure(s), 1 parse failure(s),
,
    at ChildProcess.exithandler (child_process.js:303:12),
    at ChildProcess.emit (events.js:315:20),
    at maybeClose (internal/child_process.js:1051:16),
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5),``

**other logs:**
[cont-finish.d] done.,
[s6-finish] waiting for services.,
[s6-finish] sending all processes the TERM signal.,
[s6-finish] sending all processes the KILL signal and exiting.,
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
Disabling IPV6 in hosts,
❯ Disabling IPV6 in hosts: /etc/nginx/conf.d,
  ❯ /etc/nginx/conf.d/include/block-exploits.conf,
  ❯ /etc/nginx/conf.d/include/proxy.conf,
  ❯ /etc/nginx/conf.d/include/force-ssl.conf,
  ❯ /etc/nginx/conf.d/include/letsencrypt-acme-challenge.conf,
  ❯ /etc/nginx/conf.d/include/ssl-ciphers.conf,
  ❯ /etc/nginx/conf.d/include/ip_ranges.conf,
  ❯ /etc/nginx/conf.d/include/assets.conf,
  ❯ /etc/nginx/conf.d/include/resolvers.conf,
  ❯ /etc/nginx/conf.d/production.conf,
  ❯ /etc/nginx/conf.d/default.conf,
Disabling IPV6 in hosts,
❯ Disabling IPV6 in hosts: /data/nginx,
  ❯ /data/nginx/default_host/site.conf,
  ❯ /data/nginx/proxy_host/1.conf,
  ❯ /data/nginx/proxy_host/2.conf,
  ❯ /data/nginx/proxy_host/3.conf,
  ❯ /data/nginx/proxy_host/5.conf,
  ❯ /data/nginx/proxy_host/6.conf,
  ❯ /data/nginx/proxy_host/7.conf,
  ❯ /data/nginx/proxy_host/8.conf,
  ❯ /data/nginx/proxy_host/9.conf,
  ❯ /data/nginx/proxy_host/10.conf,
  ❯ /data/nginx/proxy_host/11.conf,
  ❯ /data/nginx/proxy_host/13.conf,
  ❯ /data/nginx/proxy_host/14.conf,
  ❯ /data/nginx/proxy_host/15.conf,
  ❯ /data/nginx/proxy_host/16.conf,
  ❯ /data/nginx/proxy_host/17.conf,
  ❯ /data/nginx/proxy_host/18.conf,
  ❯ /data/nginx/proxy_host/19.conf,
  ❯ /data/nginx/proxy_host/21.conf,
  ❯ /data/nginx/proxy_host/22.conf,
  ❯ /data/nginx/proxy_host/23.conf,
  ❯ /data/nginx/proxy_host/24.conf,
  ❯ /data/nginx/proxy_host/25.conf,
  ❯ /data/nginx/proxy_host/26.conf,
  ❯ /data/nginx/proxy_host/27.conf,
  ❯ /data/nginx/proxy_host/28.conf,
  ❯ /data/nginx/proxy_host/29.conf,
  ❯ /data/nginx/proxy_host/30.conf,
  ❯ /data/nginx/proxy_host/31.conf,
  ❯ /data/nginx/proxy_host/32.conf,
  ❯ /data/nginx/proxy_host/33.conf,
  ❯ /data/nginx/proxy_host/34.conf,
  ❯ /data/nginx/proxy_host/35.conf,
  ❯ /data/nginx/proxy_host/36.conf,
  ❯ /data/nginx/proxy_host/37.conf,
  ❯ /data/nginx/proxy_host/38.conf,
  ❯ /data/nginx/proxy_host/39.conf,
  ❯ /data/nginx/proxy_host/40.conf,
  ❯ /data/nginx/proxy_host/41.conf,
  ❯ /data/nginx/proxy_host/42.conf,
  ❯ /data/nginx/proxy_host/43.conf,
  ❯ /data/nginx/proxy_host/44.conf,
  ❯ /data/nginx/proxy_host/45.conf,
  ❯ /data/nginx/proxy_host/46.conf,
  ❯ /data/nginx/proxy_host/20.conf,
  ❯ /data/nginx/proxy_host/4.conf,
  ❯ /data/nginx/proxy_host/12.conf,
[8/16/2020] [3:05:42 PM] [Migrate  ] › ℹ  info      Current database version: 20200410143840,
[8/16/2020] [3:05:43 PM] [IP Ranges] › ℹ  info      Fetching IP Ranges from online services...,
[8/16/2020] [3:05:43 PM] [IP Ranges] › ℹ  info      Fetching https://ip-ranges.amazonaws.com/ip-ranges.json,
[8/16/2020] [3:05:50 PM] [IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v4,
[8/16/2020] [3:05:51 PM] [IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v6,
[8/16/2020] [3:05:52 PM] [SSL      ] › ℹ  info      Let's Encrypt Renewal Timer initialized,
[8/16/2020] [3:05:52 PM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...,
[8/16/2020] [3:05:52 PM] [IP Ranges] › ℹ  info      IP Ranges Renewal Timer initialized,
[8/16/2020] [3:05:52 PM] [Global   ] › ℹ  info      Backend PID 206 listening on port 3000 ...,
`QueryBuilder#allowEager` method is deprecated. You should use `allowGraph` instead. `allowEager` method will be removed in 3.0,
`QueryBuilder#eager` method is deprecated. You should use the `withGraphFetched` method instead. `eager` method will be removed in 3.0,
QueryBuilder#omit is deprecated. This method will be removed in version 3.0,
[8/16/2020] [3:05:58 PM] [SSL      ] › ✖  error     Error: Command failed: /usr/bin/certbot renew --non-interactive --quiet --config "/etc/letsencrypt.ini" --preferred-challenges "dns,http" --disable-hook-validation  ,
,
log from dozzle
```
Traceback (most recent call last):,
  File "/usr/lib/python3.8/site-packages/certbot/_internal/renewal.py", line 63, in _reconstitute,
    renewal_candidate = storage.RenewableCert(full_path, config),
  File "/usr/lib/python3.8/site-packages/certbot/_internal/storage.py", line 445, in __init__,
    raise errors.CertStorageError(,
certbot.errors.CertStorageError: renewal config file {} is missing a required file reference,
Renewal configuration file /etc/letsencrypt/renewal/npm-8.conf is broken. Skipping.,
0 renew failure(s), 1 parse failure(s),
,
    at ChildProcess.exithandler (child_process.js:303:12),
    at ChildProcess.emit (events.js:315:20),
    at maybeClose (internal/child_process.js:1051:16),
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5),
```
