### ISSUE TITLE
Dashboard page with all hosts

### ISSUE THREAD

**Issue by rt87** [NginxProxyManager/nginx-proxy-manager#614]
I would like to have a landing page with simple links to all proxy/redirect hosts (and such) that I have entered into my nging proxy manager. Clicking on a link should directly take me to the respective destination. The page should be auto generated, you can choose to use this page in the standard-pages section (i.e. instead of 404, congratulations, ...).

As a bonus: Each host can be configured to either appear on the standard landing page or not ("hidden" hosts).

**Comment by cbruscato** [comment]
Here is how I work this out for now:

```
version: "3"
services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2
    restart: always
    links: 
      - db
    ports:
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - ':81:81'
    volumes:
      - ./config.json:/app/config/production.json
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  db:
    image: jc21/mariadb-aria:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./data/mysql:/var/lib/mysql
    command: --innodb-flush-method=fsync --innodb-use-native-aio=0

  nginx:
    image: nginx
    restart: always
    links: 
      - nginx-proxy-manager
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/www:/var/www/html
    depends_on:
      - nginx-proxy-manager
```
*The command for the mariadb instance is only required if running Docker for Windows, I do, that's why it is there.

my nginx.conf looks like:
```
events{}
http {
  include /etc/nginx/mime.types;
  server {
    listen 80 default_server;
    server_name _;  

    location / {
           root /var/www/html;  
           index index.html; 
     }

  }
}
```

This hosts a nginx instance for a static landing page, that can just be configured on the default host at http://nginx:80. Since the container is linked, it's never exposed to the host network. You can find a variety of HTML5 templates at https://html5up.net. You can then edit the html to serve whatever locations you want from nginx-proxy-manager.

However, I second this request, as all of this configuration would go away with a simple dropdown to configure a landing page, and checkboxes for which locations to expose. I would, however, also like to see Access Lists still incorporated into this, so that this landing page can still be secured, as well as, offering optional anonymous access. However, I think that brings us out into the weeds of people who want to configure both, and have some available only if logged in. To build it right, it probably needs that.
