### ISSUE TITLE
Change listen Port

### ISSUE THREAD

**Issue by michelkoeller** [NginxProxyManager/nginx-proxy-manager#675]
Hi,
I want to have multiple servers on port 25565 (Minecraft). But I can't change the listen port (the default is 80). When I change it under /data/nginx/proxy_host (and the .conf file) it resets every time. The best practice I find is, when you can include this in the UI. Then is the NPM perfect. 
Thanks for this nice Tool. But I can't use it when I can't change the listen port.
With friendly greetings 
Michel

**Comment by Wadera** [comment]
I'm kind of lost. You have problem with change listen ports on your minecraft server setup or Nginx proxy?

If Minecraft - then we can't really help you directly (there is some workaround below). 
If it's Nginx Proxy Manager issue - you need to be more clear with describing your issue ;)

If you spawning multiple VMs / Containers / Dockers on separate, internal IP addresses and all of them works on default port 80 - then solution will be Port Streams, 

On your external IP you can listen on port 25555 and push it into internal IP and port (lets say: 10.20.0.1:25565)
Then next one:  your external IP can listen on 25556 and push it into next internal IP and port (lets say: 10.20.0.2:25565)
etc

**To get it work you need to setup 2 things:**
1. Put some range port forwarding on your router, let' say: 25555 - 25600 into your docker node machine
2.  Modify your composer build file to be able to listen on it:
```
root@myhost:/docker/composer-configs/proxy# cat docker-compose.yml
version: "3"
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - 80:80
      - 81:81
      - 443:443
      - 25555-25600:25555-25600/tcp
      - 25555-25600:25555-25600/udp
...
```

And then rebuild your Nginx Proxy Manager docker:
```
# docker-compose down && docker-compose up -d
```
