### ISSUE TITLE
nginx-proxy-manager + nextcloud:fpm = 502 Bad Gateway

### ISSUE THREAD

**Issue by talesam** [NginxProxyManager/nginx-proxy-manager#928]
I'm using two separate docker-compose files, some with npm and one with nextcloud. I get the npm network to use in the nextcloud, but I have an error when accessing the **502 Bad Gateway nextcloud**.

**Below my nextcloud docker-compose**

```
version: '3.9'

services:
  nextcloud_db:
    image: postgres:13
    container_name: nextcloud_db
    restart: always
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    env_file:
      - db.env

  nextcloud:
    image: nextcloud:fpm
    container_name: nextcloud
    restart: always
    expose:
      - '80'
      - '9000'
    volumes:
      - ./volumes/nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=nextcloud_db
    env_file:
      - db.env
    depends_on:
      - nextcloud_db

networks:
  default:
    external:
      name: nginxproxymanager_default
```

**My conteiners**
![Captura de tela de 2021-03-06 20-17-25](https://user-images.githubusercontent.com/981368/110224335-5f6d9a00-7eb9-11eb-97d8-57cf139c9f0f.png)

Configuration SSL
![Captura de tela de 2021-03-06 20-11-29](https://user-images.githubusercontent.com/981368/110224390-fc303780-7eb9-11eb-8a14-3c073c2d6e71.png)
![Captura de tela de 2021-03-06 20-11-40](https://user-images.githubusercontent.com/981368/110224453-79f44300-7eba-11eb-875c-be88835dd424.png)

![Captura de tela de 2021-03-06 20-25-01](https://user-images.githubusercontent.com/981368/110224410-208c1400-7eba-11eb-95b5-a231bfdd17f4.png)

**Comment by sgb999** [comment]
i posted the same issue, there is a communication error somewhere between the database and the app, no idea how to fix, must be a bug in the program

**Comment by talesam** [comment]
Let's see if anyone finds an answer, I put it well specified.

If using the nextcloud: latest image works, but this image has apache built in, it doesn't make sense, it doesn't!

**Comment by sgb999** [comment]
I think you're confused. It has nothing to do with the image that you are proxying to at all. Its an issue when the app talks to the database, it happens for any docker image you proxy to even if apache is not involved.

**Comment by talesam** [comment]
It's not a problem with the bank, it works for me if I change where nextlcoud is: fpm to nextcloud: latest, everything will work fine, but I don't want to use this image, as it comes with built-in apache.

Again, if I use the "nextcloud" image other than with ngnix, it works perfectly.

**You can test this compose docker that will work:**

```
version: '3.9'

services:
  nextcloud_db:
    image: postgres:13
    container_name: nextcloud_db
    restart: always
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    env_file:
      - db.env

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: always
    volumes:
      - ./volumes/nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=nextcloud_db
    env_file:
      - db.env
    depends_on:
      - nextcloud_db

networks:
  default:
    external:
      name: nginxproxymanager_default
```
      
**db.env** 
```
POSTGRES_PASSWORD=YOU_PASS
POSTGRES_DB=nextcloud
POSTGRES_USER=nextcloud
```

**Comment by l4rm4nd** [comment]
Sometimes the HTTP/2 support can break some stuff. Try disabling it, might help .. might not.

**Comment by talesam** [comment]
> Às vezes, o suporte HTTP / 2 pode quebrar algumas coisas. Tente desativá-lo, pode ajudar ... talvez não.

That's not it, I had already tested it.

**Comment by talesam** [comment]
Nobody knows if it is possible to run the `nextcloud:fpm` image with nginx proxy manager?

It should work, since there is a web server running at npm, right?

How would it be to run npm with this docker-compose?
```
version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud:fpm
    restart: always
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db

  web:
    image: nginx
    restart: always
    ports:
      - 8080:80
    links:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app
      
      ```
